### ISSUE TITLE
IF crash with Skyblocker

### ISSUE THREAD

**Issue by Julienraptor01** [RaphiMC/ImmediatelyFast#101]
Original issue : https://github.com/SkyblockerMod/Skyblocker/issues/215

Steps and Explanation by @AzureAaron

Yep I can reproduce it reliably with skyblocker :
﻿
Steps:
1. Be on your private island & have Fairy Souls Helper disabled
1. Enter the hub
1. Enable the fairy souls helper
1. IF instantly crashes the game

Explanation:
the  "optimized" buffer stuff from ImmediatlyFast can cause crashes when attempting to render things.
﻿
I encountered the crash java.lang.NullPointerException: Cannot invoke "java.nio.ByteBuffer.rewind()" because "this.field_1555" is null from something in my own mod, but based on #215 (and from my own investigation) stuff in Skyblocker can trigger the crash as well.
﻿
It occurs because IF sets the buffer inside of the BufferBuilder to null sometimes (which can never happen in vanilla), so when the buffer is attempted to be rewound it triggers the NullPointerException. 
﻿
﻿Log: [latest.log](https://github.com/RaphiMC/ImmediatelyFast/files/12306650/latest.log)

**Comment by RaphiMC** [comment]
This build should fix it. Please confirm as I didn't test it: https://upload.raphimc.net/file/gqDmMBBUVZIxWMxE/1hbBFVZwS4LqFi6u/ImmediatelyFast-1.1.27-SNAPSHOT%2B1.20.1.jar

**Comment by Julienraptor01** [comment]
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/49841713/47a6cdf0-d8c3-4c0f-80b5-8f55fb7ad097)
version does indeed fix
