### ISSUE TITLE
Crash with MiniHUD's light overlay

### ISSUE THREAD

**Issue by Remi4001** [RaphiMC/ImmediatelyFast#102]
System specs:
- Arch linux 6.4.9
- Nvidia RTX 3070 with 535.98 drivers
- Intel i5 10600k

Mods:
- ImmediatelyFast 1.1.26
- MaLiLib 0.16.1
- MiniHUD 0.27.0

Steps to reproduce:

1. Join a world
2. Enable MiniHUD's light overlay
3. Trigger a large update of the light overlay at once (going up in creative then dropping down works for me)
4. Game crashes due to a segfault in libnvidia-glcore.so

Not sure but could be the same issue as #101. I tested with IF 1.1.24 and could not reproduce the issue, and 1.1.25 crashed the game like #99 and #97, which means the issue must've been introduced in 1.1.26 (or 1.1.25 and was hidden by the other crash).

Game log: [latest.log](https://github.com/RaphiMC/ImmediatelyFast/files/12309448/latest.log)
Additional error message in PrismLauncher: 

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fbe7e7b0c88, pid=43743, tid=43811
#
# JRE version: OpenJDK Runtime Environment (17.0.8+7) (build 17.0.8+7)
# Java VM: OpenJDK 64-Bit Server VM (17.0.8+7, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libnvidia-glcore.so.535.98+0x15b0c88]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/remi/.local/share/PrismLauncher/instances/bugtest/.minecraft/core.43743)
#
# An error report file with more information is saved as:
# /home/remi/.local/share/PrismLauncher/instances/bugtest/.minecraft/hs_err_pid43743.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by Remi4001** [comment]
Same thing with Windows 11

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff1e55a9e0, pid=1160, tid=10980
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.5+8 (17.0.5+8) (build 17.0.5+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (17.0.5+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [nvoglv64.dll+0x14ca9e0]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\remil\AppData\Roaming\PrismLauncher\instances\1.20.1\.minecraft\hs_err_pid1160.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by hexadecimal233** [comment]
Can be reproduced

**Comment by RaphiMC** [comment]
Fixed it. I will release it when I fixed some more issues. Here are dev builds:
https://upload.raphimc.net/file/uiXs1y2bOk7RccQA/wwDHXdZHtNahBj4Y/ImmediatelyFast-1.1.27-SNAPSHOT%2B1.20.1.jar
https://upload.raphimc.net/file/pWoMkr2pC3VJ8O9t/FUGk4z8i1GYHmuLT/ImmediatelyFast-1.1.27-SNAPSHOT%2B1.19.4.jar
https://upload.raphimc.net/file/Tymb41KijTlVs6rG/I0D0LzmkxLlVak08/ImmediatelyFast-1.1.27-SNAPSHOT%2B1.19.2.jar
