### ISSUE TITLE
[ERROR: Crashes on startup] exception thrown net.minecraft.class_148: Rendering overlay

### ISSUE THREAD

**Issue by zndrmn** [RaphiMC/ImmediatelyFast#104]
Crashes on startup, removing a resource pack from options.txt sometimes fixes the problem

[latest.log](https://gist.github.com/zndrmn/0a881fbbb5d2959a59f573aa487f9446#file-gistfile1-txt)
[crash-2023-08-12_04.19.32-client.txt](https://gist.github.com/zndrmn/8f6a9ad8e2f89dab0a5ac1074abdaaf6#file-gistfile1-txt)

**Comment by RaphiMC** [comment]
This crash doesn't seem to be related to IF. It seems like its a problem in sodium

**Comment by zndrmn** [comment]
strange, once I remove IF the problem stops
I can report this to sodium as well ig

**Comment by zndrmn** [comment]
Dashloader moment apparently
