### ISSUE TITLE
Horse hud visual glitch with victus

### ISSUE THREAD

**Issue by Rad586** [RaphiMC/ImmediatelyFast#105]
![2023-08-19_00 00 57](https://github.com/RaphiMC/ImmediatelyFast/assets/99306685/0c6f8733-5158-4bac-9a72-9afdb72e2524)
**Game version:** 1.18.2 fabric
**Environment:** 
cardinal-components-api-4.2.0
Patchouli-1.18.2-71.1-FABRIC
victus-0.1.11+1.18
fabric-api-0.67.1+1.18.2
ImmediatelyFast-1.1.12+1.18.2
**Log:**
[latest.log](https://github.com/RaphiMC/ImmediatelyFast/files/12381120/latest.log)

**Comment by RaphiMC** [comment]
1.18.2 is no longer supported
