### ISSUE TITLE
[1.20.x] Fast Text Lookup breaks rendering for many unicode characters newly supported by Minecraft

### ISSUE THREAD

**Issue by qwerasd205** [RaphiMC/ImmediatelyFast#107]
Most obvious when installed alongside the SymbolChat mod- a great deal of symbols appear as missing glyph boxes. Just as an example, try the croccodile emoji: `🐊`. To reproduce, just launch with ImmediatelyFast installed in 1.20(.1) with the default config and send a `🐊` in the chat to see it shows as a missing glyph box- then close minecraft and disable `fast_text_lookup` in the config, start it again and now the emoji will display correctly.

**Comment by RaphiMC** [comment]
It works for me. Please upload a game log and try it again with no other mods installed

**Comment by qwerasd205** [comment]
Ah, indeed it doesn't happen with just ImmediatelyFast installed. Currently trying to find which mod causes the incompatibility.

**Comment by qwerasd205** [comment]
Unfortunately this appears to be a phantom bug. I returned the configuration to the state it was in originally when I was experiencing the bug (that is, re-enabled `fast_text_lookup`) and it did not re-appear. If I experience the bug again and can get more info on it I suppose I'll try to let you know- but for now I'll close this issue.
