### ISSUE TITLE
Immediately Fast conflicts with memoryleakfix

### ISSUE THREAD

**Issue by ghost** [RaphiMC/ImmediatelyFast#111]
crash report:

ImmediatelyFast breaks version (-∞, 1.1.1] of memoryleakfix, which is present!

Never seen again

**Comment by b12arr0** [comment]
Getting this too after the update to version 1.2.1.

**Comment by Pillow-Fan** [comment]
Same problem here, just installed the mod:
Mod 'ImmediatelyFast' (immediatelyfast) 1.2.1+1.19.2 is incompatible with version 1.1.1 or earlier of mod 'Memory Leak Fix' (memoryleakfix), but a matching version is present: 1.1.1!

**Comment by RaphiMC** [comment]
Already reported: https://github.com/fxmorin/MemoryLeakFix/issues/143
I can't do anything about it since its MemoryLeakFix which causes the problen. Either remove MemoryLeakFix until a new version releases or stay on an old ImmediatelyFast version

**Comment by RaphiMC** [comment]
MemoryLeakFix updated to v1.1.2 which fixes the issue
