### ISSUE TITLE
Load Error with Memory Leak Fix

### ISSUE THREAD

**Issue by forditt** [RaphiMC/ImmediatelyFast#112]
After the last update, the mod stopped running with [Memory Leak Fix
](https://modrinth.com/mod/memoryleakfix)![image](https://github.com/RaphiMC/ImmediatelyFast/assets/105544922/5462633e-5afa-4664-85f5-66897ec360a4)

**Comment by RaphiMC** [comment]
Duplicate of #111
You have to wait for MemoryLeakFix to update
