### ISSUE TITLE
Issues with Font.DisplayMode.SEE_THROUGH

### ISSUE THREAD

**Issue by magicus** [RaphiMC/ImmediatelyFast#126]
We had incompatibility issues between IF and Wynntils, another mod. We have worked around them by changes in Wynntils, but since you claim to have good interoperability with other mods, I thought you wanted to know about this problem, since other mods might run into it.

Our patch is here: https://github.com/Wynntils/Artemis/pull/2177

**Comment by RaphiMC** [comment]
While I claim good mod compatibility and mod compatibility is also a focus, I don't claim 100% and it won't ever be that. IF has very high compatibility for what it does. I appreciate that you let me know of the bug, but its not feasable to fix every issue directly in IF (Especially if it would require injecting into other mods). I also often lack the time to inspect every issue in great detail, thats why I appreciate that you fixed it in Wynntils directly (And SEE_THROUGH was the wrong layer type to begin with. Vanilla MC uses POLYGON_OFFSET at that location). For those reasons I won't look into this further unless the same issue arises in multiple other mods.
