### ISSUE TITLE
1.20.1 Crash while wearing custom modelled armor, and having outline

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [RaphiMC/ImmediatelyFast#127]
Hello!

A combination of situations can cause randomly occuring crashes.
The scenario:
- A player is wearing an armor set with custom 3D model (implemented by AzureLib Armor)
- Outline is drawn around the player (who is wearing the armor)
- Use Shaders

A real life example is the following:
- Install Paladins & Priests mod (with dependencies) + Iris + Complementary Shaders, and ImmediatelyFast
- Switch to third person view
- Wear armor with custom 3D model (for example Crusader armor set)
- Pick a *Holy Wand* and to spam heal (self)

The issue seems to occur consistently **after** pausing the game for like 3-5 minutes, (tabbing out) leaving it to render in the background, than returning the game and trying to self heal.
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/4989469/c98325ef-2a3a-4ddc-a928-b4ba6d5d6e9f)

Crashlog
[crash-2023-10-15_13.00.55-client.txt](https://github.com/RaphiMC/ImmediatelyFast/files/12909431/crash-2023-10-15_13.00.55-client.txt)

**Comment by RaphiMC** [comment]
Fixed it. You can get the dev build here: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/6777737866 or wait until ImmediatelyFast 1.2.7 releases

**Comment by ZsoltMolnarrr** [comment]
Hello @RaphiMC !
According to limited testing I was able to carry out, the issue seems to be resolved.
Thank you very much for the cooperation!
