### ISSUE TITLE
[Feature] Config System

### ISSUE THREAD

**Issue by isXander** [RaphiMC/ImmediatelyFast#13]
It would be beneficial if there was some method of disabling certain optimizations of immediately-fast. 

For example, the gui batching can cause performance issues on older GPUs, I myself have not experienced this issue but others have reported issues with it, much like exordium.

This can be done in two ways, a simple file config like sodium or a more user-friendly config like Debugify.

You could also address this issue by actually fixing the performance problems with older GPUs for gui batching, or even disabling it if an old GPU is detected.

**Comment by RaphiMC** [comment]
I will add an user-friendly config within the next updates. For the GUI batching issue, thats a weird one. Normally batching something and not sending many draw calls to the GPU should make it run faster, but not slower. I don't have that old of a GPU but I will get in contact with the affected players and figure it out

**Comment by ghost** [comment]
In a mod like IF an user facing config system would be bloat. Just add a config file (even that's not really needed either though)

**Comment by RaphiMC** [comment]
I think a config file will be good compromise between not being able to configure anything and a full user interface

**Comment by ghost** [comment]
Like c2me does it

**Comment by Oondanomala** [comment]
If this is added, please add a setting to disable the F3 text this mod adds, i like having a clean F3 menu :)

**Comment by RaphiMC** [comment]
Added in ImmediatelyFast 1.1.3

**Comment by Felix14-v2** [comment]
I have ImmediatelyFast and Cloth-config v10.0.96 installed, but there's no config button
![image](https://user-images.githubusercontent.com/75726196/229240412-54498ce8-060d-4c08-9a69-404607e60084.png)

**Comment by RaphiMC** [comment]
The config isn't supposed to be changed at runtime and it shouldn't really be touched much apart for debugging thats why its only a json file in the fabric config folder
