### ISSUE TITLE
Startup crash/1.20.1 mixin failled 

### ISSUE THREAD

**Issue by Primia** [RaphiMC/ImmediatelyFast#130]
use forge version:47.2.0
ImmediatelyFast-1.2.6

**Comment by RaphiMC** [comment]
Please provide more information like a mod list and a crash log

**Comment by Primia** [comment]
https://mclo.gs/Vikt3sY

**Comment by RaphiMC** [comment]
Try it without all the other mods

**Comment by Primia** [comment]
Without all the other mods is ok.

**Comment by RaphiMC** [comment]
You should find out what mod causes the issue

**Comment by Primia** [comment]
[Joban Client Mod](https://modrinth.com/mod/jcm/versions?l=forge&g=1.20.1)
Finally, I found the problem，Crash with Joban Client Mod.
Crash report:https://mclo.gs/o894oh4
mod list:
Joban-Client-Mod-1.20-1.2.2
architectury-9.1.12-forge
ImmediatelyFast-1.2.6+1.20.2
MTR-forge-1.20.1-3.2.2-hotfix-1

**Comment by RaphiMC** [comment]
The 1.20.2 version of Joban Client Mod is considered experimental by the dev and doesn't even launch in my Forge instance with latest Forge 1.20.2. You can reopen this issue when the mod is out of alpha phase and works properly on 1.20.2
