### ISSUE TITLE
Forge 1.20.2 crash

### ISSUE THREAD

**Issue by notlin4** [RaphiMC/ImmediatelyFast#132]
Forge version: 48.0.30
Log: https://mclo.gs/BqRGwmo

**Comment by RaphiMC** [comment]
No ides why Forge is being bad again, but I found a workaround: Downgrade to Forge 1.20.2 **48.0.17**

**Comment by notlin4** [comment]
Forge 1.20.2 **48.0.17** will work, anything higher will not

**Comment by Lolothepro** [comment]
caused by https://github.com/MinecraftForge/MinecraftForge/commit/ab544a78d3b24786b07b421689a6f20853a49f80

**Comment by RaphiMC** [comment]
The issue is known and being worked on by the Forge dev, but who knows how long it takes until its fixed
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/50594595/16a2cbd1-9891-4583-9524-4831535ec292)

**Comment by RaphiMC** [comment]
Forge fixed it. Use Forge 48.0.33 or newer
