### ISSUE TITLE
Supplementaries incompatibility

### ISSUE THREAD

**Issue by MehVahdJukaar** [RaphiMC/ImmediatelyFast#134]
Hello,
I'm not super familiar with the mod nor i have delved into the code enough but i noticed it is not compatible with supplementaries map additions,  specifically colored maps and possibly mipmapped map textures. Do you have any insight on how the mod works and if it would be possible to have both systems be compatible?

**Comment by IthanMendoza** [comment]
Also this issue extends to the mod called map atlases where the separator lines beetween each map look weird after ImmediatelyFast is installed.

Here some pictures

Before the mod is installed:
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/127630637/d352b148-53de-4b9b-a08d-da7633ea0f7a)


After the mod is installed:
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/127630637/9c873251-69ad-448f-84ae-e2fa78e99c83)

**Comment by MehVahdJukaar** [comment]
are those lines atlas bleeding?

**Comment by MehVahdJukaar** [comment]
so ive looked at the code. here is what i found
- I can add integration on my end by drawing onto the map atlas texture instead
- moonlight lib also adds mipmap to map textures. I believe this mod does not have mipmapped atlases. Could this be added here?
- issue from last image must be atlas bleeding.Could you add the same texture stretching method used by vanilla?

**Comment by RaphiMC** [comment]
I could not reproduce the issue with Map Atlases.
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/50594595/7c799671-5007-4a28-91f2-266e2640e990)
Its probably caused by another mod. If you have more details to that please open a new issue.

Also Supplementaries compatibility is not possible because both mods modify the map rendering code and this can't really work because ImmediatelyFast replaces large parts of the internals. The only way this could work is if Supplementaries adds special code to handle drawing onto the map atlas

**Comment by MehVahdJukaar** [comment]
you are using the fabric version...

**Comment by MehVahdJukaar** [comment]
also supplementaries compatibility is possible, I did it myself with a mixin squared into your mixin code. however that does not add back the mipmap and would be easier if you could just add that natively. Vanilla maps not having mipmap makes no sense and they look much better with it (for example when in item frame from a distance its very noticeable)

**Comment by RaphiMC** [comment]
Is Map Atlases only broken in Forge? You didn't describe that if thats the case. Please open a new issue if its only on the Forge version. I will think about enabling mipmaps by default if there are no drawbacks with that

**Comment by MehVahdJukaar** [comment]
They are pretty much two completely different mods at this point ( for now), as you can also see by the textures. I'm only responsible for that version.
