### ISSUE TITLE
Request Porting for 1.18.2 - Forge

### ISSUE THREAD

**Issue by TqLxQuanZ** [RaphiMC/ImmediatelyFast#135]
I've saw the https://www.curseforge.com/minecraft/mc-mods/immediatelyfast-reforged reforged version is being discontinued due to the official version supports forge as well, but there isn't any version for 1.18.2, only 1.19.2 and above, is it possible to port it backward for 1.18.2 forge version?

**Comment by RaphiMC** [comment]
The 1.18.2 version doesnt need a new backport since it didnt get any updates because I am not maintaining the 1.18.2 version anymore. 1.18.2 is pretty old now and barely used anymore.

**Comment by xFirefalconx** [comment]
Sad, my modpack would benefit from such a thing too. Came here for the same reason. At least I didn't have to ask seeing this is the current situation. Is the unofficial one still some good though, or does it make problems concerning compatibilities/crashes? Will give it a try then.
