### ISSUE TITLE
NeoForge compat

### ISSUE THREAD

**Issue by Lolothepro** [RaphiMC/ImmediatelyFast#144]

**Comment by RaphiMC** [comment]
Currently not easily possible due to issues with the toolchain (Architectury) not fully supporting yarn mappings in NeoForge. Next issue is that Forgix (Currently used to bundle Fabric and Forge into one single jar) does not support NeoForge (And probably won't anytime soon)

**Comment by RaphiMC** [comment]
Done. Scheduled for next release (Roughly when 1.20.3 releases)
