### ISSUE TITLE
Transparency Issues with Hud rendering (Iron's Spells & Spellbooks)

### ISSUE THREAD

**Issue by iron431** [RaphiMC/ImmediatelyFast#148]
### Versions:
**Forge: 1.20.1-47.1.3**
**ImmediatelyFast 1.2.7+1.20.2**
**Iron's Spells 'n Spellbooks 1.20.1-2.1.1**
### Mods:
- Iron's Spell's 'n Spellbooks
- ImmediatelyFast
- Curios (dep of iron's spellbooks)
- Geckolib (dep of iron's spellbooks)
- caelus (dep of iron's spellbooks)
- playeranimator (dep of iron's spellbooks)

Several of the Iron's Spells & Spellbooks (https://legacy.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks) transparent hud elements become fully opaque when using immediately fast

### Spell Bar Overlay
Steps to reproduce:
1. Hold a spellbook (such as the Blood Staff, which has pre-slotted spells)

What it's supposed to look like: 
<img width="653" alt="image" src="https://github.com/RaphiMC/ImmediatelyFast/assets/34083081/79f06e2c-6d15-4ec5-9f08-08e117283cf6">

With ImmediatelyFast:
<img width="650" alt="image" src="https://github.com/RaphiMC/ImmediatelyFast/assets/34083081/82bd1cbc-1979-4c1d-8f4f-6fad75263bbf">
(both items have the same spells equipped)

### Spell Bar and Item Decorator Cooldown Overlay
Steps to reproduce:
1. Obtain a spellbook with spells
3. Cast a spell

What it's supposed to look like:
<img width="646" alt="image" src="https://github.com/RaphiMC/ImmediatelyFast/assets/34083081/2d3e9650-8339-4234-8a8c-1b03b80d1790">

With ImmediatelyFast (Notice Spell bar is opaque; Item is on top of hotbar overlay):
<img width="667" alt="image" src="https://github.com/RaphiMC/ImmediatelyFast/assets/34083081/6c7e8f1f-6bf1-4468-b1f8-20c65fe757bd">

Additional Examples: https://github.com/iron431/Irons-Spells-n-Spellbooks/issues/231

**Comment by iron431** [comment]
I should add, after looking at the hud code, it hasn't been optimized since the direct port from 1.19. i'd appreciate more information on the issue as i'm no rendering expert and i don't know what immediately fast does behind the scenes.

**Comment by lab3** [comment]
Also, when ImmediatelyFast is installed when using Iron's Spells this also happens:

# Heartstop spell without Immediately Fast:
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/1099358/267e6a62-48d2-438c-a90c-8428db298eff)

# Heartstop spell with Immediately Fast:
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/1099358/3cb3e54b-c4db-417c-898a-f1625f09a912)

Here is the list of mods in the test without ImmediatelyFast
```
mod_id,mod_name,mod_version,mod_file,mod_url,display_url,issue_tracker_url
minecraft,Minecraft,1.20.1,client-1.20.1-20230612.114412-srg.jar,,,
caelus,Caelus API,3.1.0+1.20,caelus-forge-3.1.0+1.20.jar,,https://github.com/TheIllusiveC4/Caelus,https://github.com/TheIllusiveC4/Caelus/issues
forge,Forge,47.2.0,forge-1.20.1-47.2.0-universal.jar,,,http://www.minecraftforge.net/
curios,Curios API,5.4.7+1.20.1,curios-forge-5.4.7+1.20.1.jar,,https://www.curseforge.com/minecraft/mc-mods/curios,https://github.com/TheIllusiveC4/Curios/issues
patchouli,Patchouli,1.20.1-84-FORGE,Patchouli-1.20.1-84-FORGE.jar,,,https://github.com/VazkiiMods/Patchouli
geckolib,GeckoLib 4,4.4,geckolib-forge-1.20.1-4.4.jar,,http://geckolib.com/,https://github.com/bernie-g/geckolib/issues
playeranimator,Player Animator,1.0.2-rc1+1.20,player-animation-lib-forge-1.0.2-rc1+1.20.jar,,,
irons_spellbooks,Iron's Spells 'n Spellbooks,1.20.1-2.2.1,irons_spellbooks-1.20.1-2.2.1.jar,,https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks,https://github.com/iron431/Irons-Spells-n-Spellbooks/issues
```

The only change is adding this
```
immediatelyfast,ImmediatelyFast,1.2.8+1.20.4,ImmediatelyFast-Forge-1.2.8+1.20.4.jar,,,https://github.com/RaphiMC/ImmediatelyFast/issues
```

**Comment by lab3** [comment]
We have a couple people a day show up in our discord with this and our only option at the moment is to tell them to remove ImmediatelyFast.  If there is something on our end we can do let's discuss

You can hit up Smalls or Iron in the discord
https://discord.gg/4gDYuJtK

**Comment by RaphiMC** [comment]
Try disabling hud_batching in the config file and check if that fixes it for now

**Comment by lab3** [comment]
Looks like that resolves the heartstop issue.

**Comment by liangmoe** [comment]
Can confirm immediatelyfast version above 1.2.13 also fixed this
![2024-05-07_01 54 51](https://github.com/RaphiMC/ImmediatelyFast/assets/135343248/0de70743-93e1-4a50-a87a-0b3fc3d38bff)
