### ISSUE TITLE
Incorrect Documentation for 1.2.8 NeoForge Version on Modrinth

### ISSUE THREAD

**Issue by Ghastly13** [RaphiMC/ImmediatelyFast#153]
The versions stated compatible with 1.2.8 are 1.20-1.20.4 on Modrinth, however it throws an error on load that it is only compatible with 1.20.2-1.20.4. Additionally, it states that it requires NeoForge to be installed, however incorrectly states that it is not installed. I believe this is an error with the Modrinth documentation, as the changelog states that only 1.20.2 and above are supported.

**Comment by Ghastly13** [comment]
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/83313692/7b77e4b0-1da7-4ebf-8aa9-45cbc962b948)
Oh, here's a screenshot of the ingame errors as well.

**Comment by RaphiMC** [comment]
NeoForge 1.20.1 is just rebranded Forge and thus it can't load NeoForge mods, use the Forge version of ImmediatelyFast instead. I am gonna change the version range on the mod distribution sites
