### ISSUE TITLE
Ask for your permission

### ISSUE THREAD

**Issue by DSLZL** [RaphiMC/ImmediatelyFast#155]
Hello, ImmediatelyFast creators.
I'm DSLZL, and I'm sorry for opening a new issue on your project that is completely unrelated, but I can only contact you on GitHub in China.
I'd like to ask if I can put this ImmediatelyFast you made into my modpack and release it in modrinth, because I don't know much about licenses, so I'm here to ask for your opinion, and if my actions violate your rights, I'm very sorry and delete the modpack and apologize immediately after seeing your reply.
The modpack link in modrinth is: [only-optimized](https://modrinth.com/modpack/only-optimized), if you don't see it, it's because it's still under review.
Sorry to interrupt you, but please forgive me for any inconvenience I may have if I do not obtain your permission.
(This passage is supported by Microsoft Translator, if you agree with my behavior, please do not delete this issue, so that I can provide evidence if I need it)
Thank you so much.

**Comment by RaphiMC** [comment]
Thanks for asking.
The license allows you to distribute ImmediatelyFast in modpacks

**Comment by DSLZL** [comment]
> Thanks for asking. 谢谢你的提问。 The license allows you to distribute ImmediatelyFast in modpacks该许可证允许您在模组包中分发 ImmediatelyFast

Thank you for your reply
