### ISSUE TITLE
Characters on sign text is buggy

### ISSUE THREAD

**Issue by Punkinator2** [RaphiMC/ImmediatelyFast#159]
![Screenshot from 2024-01-03 17-04-52](https://github.com/RaphiMC/ImmediatelyFast/assets/53418907/c27588a9-ae37-46a3-b2a5-f8c668958220)

The text that renders on signs isn't displaying correctly on 1.20.4

**Comment by RaphiMC** [comment]
Do you have experimental_sign_text_buffering enabled in the immediatelyfast config file?

**Comment by Punkinator2** [comment]
> Do you have experimental_sign_text_buffering enabled in the immediatelyfast config file?

It appears I did, changing it back fixed the issue. Sorry to bother you

**Comment by RaphiMC** [comment]
This issue is already known (#117) then
