### ISSUE TITLE
The mod causes villagers sleeves & feet to be visible 

### ISSUE THREAD

**Issue by G-60** [RaphiMC/ImmediatelyFast#162]
I removed the mod and apparently it was the mod causing it.
**Minecraft Version: 1.20.4
Immediately Fast version:**
**Mod version **ImmediatelyFast 1.2.8****
**OS: Windows 10**

### To Reproduce:

1. Launch 1.20.4 with the mod installed
2. Join a singleplayer world
3. Summon a villager

I got sodium and modrenfix and few other mods installed, when i removed Immediately fast it was fixed.

![image](https://github.com/RaphiMC/ImmediatelyFast/assets/131556546/8634c14a-17d0-41ef-946c-6b3a81dee3b3)

**Comment by G-60** [comment]
This scared the 💩 out of me

**Comment by RaphiMC** [comment]
Could not reproduce the issue with only ImmediatelyFast installed:
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/50594595/eb32380d-8beb-4a62-94a4-9de067a4ecb3)

**Comment by RaphiMC** [comment]
Could be a batched entity rendering issue. Try setting debug_only_and_not_recommended_disable_universal_batching in the immediatelyfast.json config file to true (And set it to false again after testing)

**Comment by G-60** [comment]
Hi, after doing that it seems to be working and now they are normal.
I set it back to false again

**Comment by RaphiMC** [comment]
Can you upload a game log so I can see more information regarding your hardware and other mods

**Comment by G-60** [comment]
Sorry i can't give you that, it contains some sensitive informations but ill give you my mod list:
Appleskin
Clean F3
Cloth config API
Coordinates display
dynamic fps
Fabric API
Fabric language Kotlin
Ferritecore
Freelook
Gamma utils (fullbright)
Ksyxis
Litematica
Lithium
Malilib
Midnightlib
Modmenu
Modrenfix
Overlay tweaks
Mouse tweaks
Reese's Sodium Options
Replay mod
ScreenFX
Sodium
Sodium Extra
Very many players
Yetanotherconifglib
Zoomify
kennytvs-epic-force-close-loading-screen-mod-for-fabric

**Comment by RaphiMC** [comment]
Can you try if the issue is still reproducable without all of those mods

**Comment by G-60** [comment]
Yeah they are normal without these mods, looks like a mod is conflicting with immediatly fast

I will test which mod

**Comment by G-60** [comment]
Hello again, it was **Overlay Tweaks**

I will remove this mod for now

**Comment by RaphiMC** [comment]
Please report the issue to Overlay Tweaks as it seems like this mod is messing with translucent rendering and its not something I have the time to look into
