### ISSUE TITLE
Possible Crashes on Fabric 1.20.1 (modpack)

### ISSUE THREAD

**Issue by Sorrow-Scarlet** [RaphiMC/ImmediatelyFast#163]
**400+ mods with immediately Fast, crashing on random occurrance.**

e.g. when i kill a mob or using some weapons, when i play a mod guitar and tap a key on my keyboard.
here is the report.
[crash-2024-01-10_19.36.48-client.txt](https://github.com/RaphiMC/ImmediatelyFast/files/13887106/crash-2024-01-10_19.36.48-client.txt)

i saw :	at net.minecraft.class_329.wrapOperation$hbi000$immediatelyfast$batching(class_329.java:1915) here, and i disabled IF, it's not crashing now.
Wish u can help me :)

**Comment by RaphiMC** [comment]
The error doesn't look like its related to ImmediatelyFast since it happens outside of a method that ImmediatelyFast changes
