### ISSUE TITLE
Visual Glitches with Alex's Caves

### ISSUE THREAD

**Issue by mxnmnm** [RaphiMC/ImmediatelyFast#164]
Minecraft 1.20.1
ImmediatelyFast 1.2.8
Alex's Caves 1.0.9

When using the raygun mobs go invisible:
![2024-01-15_18 19 02](https://github.com/RaphiMC/ImmediatelyFast/assets/8508976/9bd43afe-0b0b-416b-bbdf-458f462345b4)
![2024-01-15_18 19 03](https://github.com/RaphiMC/ImmediatelyFast/assets/8508976/f2501284-3319-4598-8792-41f0c2779fb3)

**Comment by mxnmnm** [comment]
funnily enough when in f5 there are no issues

**Comment by mxnmnm** [comment]
Is there a way for me to get this confirmed? any fixes planned?

**Comment by RaphiMC** [comment]
It will be confirmed once I have time to test it and fixed shortly after if the fix isn't really complicated. Can't give you an ETA since I have barely time to work on IF

**Comment by mxnmnm** [comment]
ah alright well gl

**Comment by mxnmnm** [comment]
Fixed from Alex's end
