### ISSUE TITLE
[Compatability Issue]: Incompatible with resource pack

### ISSUE THREAD

**Issue by Timongcraft** [RaphiMC/ImmediatelyFast#171]
The [resourcepack](https://github.com/JNNGL/VanillaMinimaps/releases/download/v1.0.0/resourcepack.zip) from [VanillaMinimaps](https://github.com/JNNGL/VanillaMinimaps) does not work correctly with this mod installed.

Minecraft: 1.20.4
Fabric Loader: 0.15.3
ImmediatelyFast 1.2.8
VanillaMinimaps (plugin+resource pack): 1.0.0

Minimap (supposed):
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/77288029/f16e8d29-840e-4efe-b3d1-52c97246f12c)

Minimap (actual):
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/77288029/a2f3d098-0a90-4b55-aada-c3011b66199d)

Fullscreen Map (supposed):
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/77288029/327a2f58-80d0-4e79-bbc7-5ce7f80891e9)

Fullscreen Map (actual):
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/77288029/e444bd0a-d3f2-48a9-931f-3b9973406c68)

**Comment by RaphiMC** [comment]
This resource pack heavily abuses core shaders (Including the text shader) and thus is not compatible with any mod trying to improve performance of the thing that the shader uses. You can try disabling hud_batching in the config of ImmediatelyFast, but if that doesn't work uninstall either ImmediatelyFast or the resource pack
