### ISSUE TITLE
did not help performance, in fact it actually slowed it down.

### ISSUE THREAD

**Issue by davidromrell** [RaphiMC/ImmediatelyFast#173]
immediatelyfast (v1.2.10+1.20.4)
Render thread 9.22%
net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.endLastBatch()3.06%
net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.endBatch()2.45%
net.raphimc.immediatelyfast.feature.batching.BatchingBuffers.endHudBatching()1.81%
net.raphimc.immediatelyfast.feature.batching.BatchingBuffers.endDebugHudBatching()1.17%160ms (immediatelyfast)
net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.endBatch()0.41%
net.raphimc.immediatelyfast.feature.core.ImmediateAdapter.getBuffer()0.29%
net.raphimc.immediatelyfast.feature.core.BufferBuilderPool.getAllocatedSize()0.03%

**Comment by RaphiMC** [comment]
You clearly do not know how to interpret spark profiler results. The profiler result you sent looks perfectly normal, as ImmediatelyFast replaces some parts of minecraft's rendering (And thus consumes some CPU time instead of minecraft). Most other optimization mods do that as well

**Comment by davidromrell** [comment]
I
My bad it was another mod that seemed to be yours.

**Comment by xbxct** [comment]
Bad english
