### ISSUE TITLE
1.20-1.20.4 NeoForge builds are not compatible with 1.20.1 NeoForge

### ISSUE THREAD

**Issue by MrFastZombie** [RaphiMC/ImmediatelyFast#178]
The NeoForge builds are marked as 1.20.1 compatible on Modrinth and Curseforge but do not launch successfully. 

I'm guessing the NeoForge builds are not supposed to support 1.20.1 since NeoForge on that version didn't completely split from Forge yet. The newer 1.20.1 compatible Forge builds do seem to work fine with 1.20.1 NeoForge.

The error given when trying to run the NeoForge builds on 1.20.1 is `ImmediatelyFast-NeoForge-1.2.9+1.20.4.jar constructed 0 mods: [], but had 1 mods specified: [immediatelyfast]`. I tested both 1.2.9 and 1.2.10 on an instance with only ImmediatelyFast to verify.

**Comment by Gaming32** [comment]
Well the error message you gave says you tried to launch a 1.20.4 jar.

**Comment by MrFastZombie** [comment]
> Well the error message you gave says you tried to launch a 1.20.4 jar.

The jar is marked as 1.20-1.20.4 on the Modrinth and Curseforge pages. [Here's the Modrinth page for 1.2.10 for example.](https://modrinth.com/mod/immediatelyfast/version/1.2.10+1.20.4-neoforge) 1.20.4 is just the latest version the jar supports as far as I can tell. The Forge version is also a 1.20.4 jar, but it will launch on 1.20.1.

The problem is that the latest NeoForge jars are built for NeoForge versions that are after the breaking changes, and don't seem to work with 1.20.1 NeoForge as a result but are still marked as compatible with that version on the mod pages.

**Comment by RaphiMC** [comment]
This was caused by the auto publishing script. Fixed the version range of the NeoForge jars
