### ISSUE TITLE
Incompatibility with Entity Texture Features/Entity Model Features and custom entity models

### ISSUE THREAD

**Issue by indolentabby** [RaphiMC/ImmediatelyFast#179]
love this mod, but whenever i added it with a resourcepack for custom pigman and zombie models and ETF and EMF to make them work, both just appeared completely invisible while any armor, weapons, and entity shadows remain visible the resourcepack i use comes from vanillatweaks.net
list of potentially relevant mods im using:
Entity Model Features
Entity Texture Features
EntityCulling
MoreCulling (default settings)
FabricAPI
Indium
Lithium
ModernFix (default settings)
Sodium & Sodium Extra
Starlight
i ran the game with all aforementioned mods and a few others installed and entities displayed fine, however the difference in performance was certainly noticeable
entities without custom models work just fine regardless so this seems to specifically affect EMF related textures

**Comment by RaphiMC** [comment]
Can you try this with only the essentials mods to reproduce the bug and upload a resource pack which this can be tested with

**Comment by indolentabby** [comment]
[VanillaTweaks_r182889.zip](https://github.com/RaphiMC/ImmediatelyFast/files/14396484/VanillaTweaks_r182889.zip) these are the isolated entity models in a pack, the pigman one is just a simple remodel of the pre1.16 zombie pigmen while the zombie one includes a bunch of randomized skins
tested with only immediately fast(v1.2.10) entity model features(v1.2.3) and entity texture features(v5.2.3) along with fabric loader v0.15.7 to the same results, game version is 1.20.4
![2024-02-25_16 31 56](https://github.com/RaphiMC/ImmediatelyFast/assets/153468845/fc3970a0-9a1e-4ea1-a07d-ddcffb407db0)

**Comment by PinPanPaint** [comment]
Can confirm this is a thing, however on my end it was only with emissive textures, they disappear completely when used in tandem with This and Entity Texture Features.

**Comment by RaphiMC** [comment]
Update ETF to at least v6.1. This should fix the issue

**Comment by indolentabby** [comment]
tested with same mods as above all updated to latest versions and it works just fine, appreciate what you do
![2024-06-17_12 58 11](https://github.com/RaphiMC/ImmediatelyFast/assets/153468845/ac2820d6-f363-489a-8d5d-d6fd148fc4b6)
