### ISSUE TITLE
Full transparency on tablist (and potentially other locations) for players

### ISSUE THREAD

**Issue by R00tB33rMan** [RaphiMC/ImmediatelyFast#18]
![image](https://user-images.githubusercontent.com/36140389/210254027-fb94ad91-8795-47a6-81cb-bb985bb59f76.png)

Appears to occur on only third layer of tab list but with less players, occurs with more recency. In addition, only is noticeable when the time is set to day, not night (and lightning is more prevalent).

**Comment by RaphiMC** [comment]
Thank you for reporting the issue. I was already working on a fix and it should be fixed by today

**Comment by R00tB33rMan** [comment]
> Thank you for reporting the issue. I was already working on a fix and it should be fixed by today

Excellent. I really appreciate the hard work. This is by far one of the most efficient mods I've seen!

Edit: Can confirm your most recent patch resolves this issue.

**Comment by RaphiMC** [comment]
Fixed in ImmediatelyFast v1.1.5
