### ISSUE TITLE
Alex's Caves radiation

### ISSUE THREAD

**Issue by Kamachaos** [RaphiMC/ImmediatelyFast#184]
when a large-ish mob gets radiation it becomes invisible, (this also happens with smaller mobs when firing the raygun, also mobs like luxtructosaurus and tremorzilla seem to go invisible when not looked at correctly.

**Comment by RaphiMC** [comment]
Please provide more details, like a mod list, game log, screenshots and detailed steps to reproduce the issue

**Comment by Kamachaos** [comment]
apologies! i forgot i put this here (my memory is amazing I know)
I will be setting up a small modlist with only mods to enchance performance and the two mods (give me a little bit)

**Comment by Kamachaos** [comment]
I seemly can't recreate the issue (LOL) so it might just be an entirely different mod causing it OR it could just been already fixed apologies!
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/162135896/7a798781-fa46-46ec-a87a-fc6294926495)
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/162135896/04835fba-745c-4083-a50a-862ede407f61)

**Comment by RaphiMC** [comment]
Going to close the issue. If this happens again in a reproduceable manner, reopen it and provide exact details on how to reproduce it
