### ISSUE TITLE
-1 code erron on minecraft launcher

### ISSUE THREAD

**Issue by MatMIN3** [RaphiMC/ImmediatelyFast#187]
Hi, tried to load the mod alongside with a lot of other mods but the problem seems to be sodium, i tried to load only the basic mods to run iris and fabric and then added ImmediatlyFast and the launcher crashes and gives the code -1 as error

**Comment by RaphiMC** [comment]
Upload the game log

**Comment by MatMIN3** [comment]
And how do i do that?

**Comment by MatMIN3** [comment]
> Upload the game log

[latest.log](https://github.com/RaphiMC/ImmediatelyFast/files/14743079/latest.log)

**Comment by RaphiMC** [comment]
Iris 1.7.0 is not supported yet
