### ISSUE TITLE
Bug with the mod Stylish Effect

### ISSUE THREAD

**Issue by Bruskych** [RaphiMC/ImmediatelyFast#188]
Hello! I'm facing a problem with the mod ImmediatelyFast, Forge version - 1.20.1 (47.2.19), this mod is incompatible with another mod - Stylish Effects (https://www.curseforge.com/minecraft/mc-mods/stylish-effects) . The effect timer began to be displayed incorrectly, it almost disappeared, only the timer of the first effect is displayed correctly, this is clearly visible in the picture. 
<img width="392" alt="picture" src="https://github.com/RaphiMC/ImmediatelyFast/assets/158246943/9a4d0f70-20e7-48fd-b44c-d419486d60bf">

**Comment by liangmoe** [comment]
Same here, I can reproduce this with only immediately fast and stylish effect on forge 1.20.1-47.1.3, set immediatelyfast config "hud_batching" to false solve the issue for me

**Comment by Bruskych** [comment]
> То же самое и здесь, я могу воспроизвести это только с немедленным быстрым и стильным эффектом в forge 1.20.1-47.1.3, установите для немедленной быстрой конфигурации «hud_batching» значение false, решите проблему для меня.

Thank you, this helped! True, the FPS has become a little lower, I hope this will be fixed in the mod itself. Even the FPS dropped a lot, I’ll probably temporarily remove the effects mod and wait for updates

**Comment by peow** [comment]
i wasnt able to reproduce this on Fabric 1.20.1, maybe is a problem with Forge version only

**Comment by liangmoe** [comment]
confirm 1.2.13 fixes this, thanks for the hard work
