### ISSUE TITLE
incompatible with Memory Leak Fix

### ISSUE THREAD

**Issue by Ko4shi** [RaphiMC/ImmediatelyFast#189]
Minecraft 1.19.4
Fabric 0.15.7
With MLF 1.0.0 says "Mod 'ImmediatelyFast' (immediatelyfast) 1.2.11+1.19.4 is incompatible with version 1.1.1 or earlier of mod 'Memory Leak Fix' (memoryleakfix), but a matching version is present: 1.0.0!"
Every other version that is newer than that just crashes the game
Might be the MLF problem but decided to bump you first :3

**Comment by RaphiMC** [comment]
You need to update MemoryLeakFix
