### ISSUE TITLE
[Forge 1.20.1] ImmediatelyFast 1.2.11 fails to load.

### ISSUE THREAD

**Issue by IstasNix** [RaphiMC/ImmediatelyFast#191]
Discovered in a modpack environment when attempting to update versions, but happens with only ImmediatelyFast as well. The crash log below is from a launch which had _only_ ImmediatelyFast installed, Minecraft doesn't make it past the loading stage and says that "The Mod File C:\....jar has mods that were not found."

[crash-2024-04-10_19.47.49-fml.txt](https://github.com/RaphiMC/ImmediatelyFast/files/14940644/crash-2024-04-10_19.47.49-fml.txt)

**Comment by RaphiMC** [comment]
Does it work with ImmediatelyFast 1.2.10?

**Comment by minz1** [comment]
I have ran into the same issue, and it occurs with 1.2.10 as well. Same error.

**Comment by IstasNix** [comment]
I do not have the same experience as minz (they might be on a different version of forge or something?), 1.2.10 works fine for me, both by itself and in the full modpack. It was only when I tried to update to 1.2.11 that I encountered issues.

**Comment by RaphiMC** [comment]
I just tested both versions, and they both load fine in the same NeoForge version as used in the crash report. Where did you download the mod from? Try redownloading it from the official sources (GitHub, Modrinth, CurseForge)

**Comment by IstasNix** [comment]
I had initially downloaded it from CurseForge, that was the version that was crashing. I just tried downloading it from Modrinth and that one worked, so I was just looking at the versioning and trying to narrow it down and I believe I have done so:

On Modrinth, you have two versions of 1.2.11 listed in order as: Forge and Fabric/Quilt.
On CurseForge, though, there are three versions listed as : Fabric, NeoForge, and Forge.

It is that third CurseForge version which is specifically labelled as NeoForge which crashes. I have now downloaded all 5 files/sources from the two mod hosts, and only that version has the error.
EDIT: I also tried the 1.2.10 versions, and it's the same conditions there. CurseForge has three versions, Modrinth only has two. The NeoForge-specific version on CurseForge crashes, all other versions seem to work fine.

**Comment by RaphiMC** [comment]
There is an error on CurseForge where the NeoForge version is falsely seen as compatible when filtering game version, even tho its not when hovering over it:
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/50594595/c873ba27-8056-487f-8a68-c509efc435eb)
NeoForge on 1.20.1 isn't different to Forge, so the Forge 1.20.1 version just works there
