### ISSUE TITLE
Latest Snapshot hotbar rendering issue.

### ISSUE THREAD

**Issue by 13Ralef** [RaphiMC/ImmediatelyFast#193]
![Screenshot_20240420_233407_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/RaphiMC/ImmediatelyFast/assets/144634948/dc314923-1391-419a-9c2f-19ade5aa525c)
![Screenshot_20240420_233415_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/RaphiMC/ImmediatelyFast/assets/144634948/8713c0d0-274d-40c9-b1d2-272fc261a9bd)
So basically it's about last snapshot released on GitHub. As far I've seen it, the problem is only in servers, items don't render in the hotbar (some of em) they only render when you open inventory, and not in the hotbar anyways.

**Comment by RaphiMC** [comment]
Please upload a game log and mod list

**Comment by 13Ralef** [comment]
[latest.log](https://github.com/RaphiMC/ImmediatelyFast/files/15052308/latest.log)
Here's it.

**Comment by RaphiMC** [comment]
This is caused by one of the other mods you have installed

**Comment by 13Ralef** [comment]
Wich one

**Comment by 13Ralef** [comment]
> This is caused by one of the other mods you have installed

Wich one dude

**Comment by RaphiMC** [comment]
> > This is caused by one of the other mods you have installed
> 
> Wich one dude

I don't know, you have over 100 mods installed. You can uninstall half of them and then check if the issue still persists. If not, install the other half and check again. Repeat this until you found the mod

**Comment by MATRIX-feather** [comment]
It's probably an issue that belongs to ImmediatelyFast itself, I can also reproduce this on 1.20.5, with only Fabric API installed on:
![2024-04-25_01 14 09](https://github.com/RaphiMC/ImmediatelyFast/assets/55654482/9ebe8b65-07e3-4216-85a3-27890907a46d)

The compass in the screenshot becomes invisible in the hotbar, where it should appear:
![abb514447b1fb05382b239f91c691472](https://github.com/RaphiMC/ImmediatelyFast/assets/55654482/d8a903ea-ee8e-4c4b-a030-08d438d2cf3c)

[latest.log](https://github.com/RaphiMC/ImmediatelyFast/files/15098040/latest.log)
