### ISSUE TITLE
ImmediatelyFast + Aaron's mod + Smooth Scroll cause various graphics issues on 1.20.5

### ISSUE THREAD

**Issue by nickademas** [RaphiMC/ImmediatelyFast#194]
here are some examples
![obraz](https://github.com/RaphiMC/ImmediatelyFast/assets/46594867/71975554-8526-4a47-804a-6b39afbbaba3)
![obraz](https://github.com/RaphiMC/ImmediatelyFast/assets/46594867/914fa802-b00f-4e01-971b-37523a703fc3)
this combination also causes bugs for other mods, for example voxelmap 
![obraz](https://github.com/RaphiMC/ImmediatelyFast/assets/46594867/a44ad611-f24e-4213-8d5c-daff08e7b1ee)
[latest.log](https://github.com/RaphiMC/ImmediatelyFast/files/15140190/latest.log)
I don't know if it's your mod's fault but I'm posting this here

**Comment by RaphiMC** [comment]
Test without all the other mods. Also you have a resource pack that modifies the GUI core shaders. Those are not supported by ImmediatelyFast and might be responsible for the issues.

**Comment by nickademas** [comment]
![obraz](https://github.com/RaphiMC/ImmediatelyFast/assets/46594867/47ac9f90-d579-41d4-b8ff-ed9844718799)
i don't have any resourcepack
Already tested without other mods, and only the combination of these three causes such problems, any combination of two of these mods does not cause the problem

**Comment by RaphiMC** [comment]
Aaron's mod uses unsupported core shader modifications. It won't be compatible with ImmediatelyFast
