### ISSUE TITLE
ImmediatelyFast crash with Oculus 1.7.0

### ISSUE THREAD

**Issue by ghost** [RaphiMC/ImmediatelyFast#195]
Crash with Minecraft 1.20.1
Neoforge 47.1.105
Mods installed:
- Embeddium 0.3.14
- Oculus 1.7.0
- ImmedietlyFast 1.2.7

**Comment by RaphiMC** [comment]
Upload the game log

**Comment by ghost** [comment]
latest.log: https://pastebin.com/GmZYYguN

**Comment by ghost** [comment]
Oculus very recently updated to have parity with Iris 1.7.0
So this might be why it is crashing. I just wanted to report this update will now crash clients,

**Comment by RaphiMC** [comment]
Your ImmediatelyFast version is ancient. Please update as this issue has already been fixed
