### ISSUE TITLE
Bug (incompatibility?) with xaero's minimap

### ISSUE THREAD

**Issue by rakantoh** [RaphiMC/ImmediatelyFast#197]
i tried this mod if really brings better fps, in 1.20.4 with xaero's minimap works fine, but in 1.20.5 and 1.20.6 have issues, the xaero's minimap background (the map) no shows and only appears a black square, but the "entity points" and frame map shows ok.
1.20.4 with inmediatelyfast
![javaw_2024_04_30_23_19_11_169](https://github.com/RaphiMC/ImmediatelyFast/assets/59809634/a8f87fae-83f9-4bad-8676-b86715c0339b)

1.20.6 with inmediatelyfast (same in 1.20.5)
![javaw_2024_04_30_23_22_34_469](https://github.com/RaphiMC/ImmediatelyFast/assets/59809634/0da1f634-6bae-4722-b11a-9d9201cf9552)

**Comment by FoketzoRAI** [comment]
The same problem on 1.20.6.

Checked all my mods and then I included this mod:

Without:
![2024-05-01_13 00 33](https://github.com/RaphiMC/ImmediatelyFast/assets/32650781/47fd692e-9d26-4fb8-bb95-b393a826c097)

With:
![2024-05-01_12 56 02](https://github.com/RaphiMC/ImmediatelyFast/assets/32650781/0207f406-f0b5-4053-a46c-3320fbed857b)

**Comment by RaphiMC** [comment]
Until a new release is made, you can use this build: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/8908622594

**Comment by FoketzoRAI** [comment]
@RaphiMC unfortunatelly - bugged. (But better than it was before.)

![image](https://github.com/RaphiMC/ImmediatelyFast/assets/32650781/2e1de931-77f2-487a-9fee-8f0ce3a815fe)

**Comment by RaphiMC** [comment]
Can't reproduce this issue

**Comment by FoketzoRAI** [comment]
@RaphiMC Ok looks like it's due to other mod.

Yeah it works. Anyway thanks. 😄

**Comment by rakantoh** [comment]
Still have problems with xaero's minimap, now the map shows small and in mosaic.

without inmediately:
![javaw_2024_05_01_16_49_11_745](https://github.com/RaphiMC/ImmediatelyFast/assets/59809634/a1c7c717-e2b7-4086-8e5b-ded144e286ec)
 with inmediately:
![javaw_2024_05_01_16_48_00_642](https://github.com/RaphiMC/ImmediatelyFast/assets/59809634/d3d9ed18-38dd-4ac3-855a-e0b1c6394729)

**Comment by RaphiMC** [comment]
This is probably caused by another mod, as it works fine for me with only xaero's minimap and IF installed

**Comment by rakantoh** [comment]
> This is probably caused by another mod, as it works fine for me with only xaero's minimap and IF installed

no, i use the same mods, if i delete/disable inmediatelyfast, xaero's minimap works fine. for this reason i post the two screenshots,

**Comment by rakantoh** [comment]
i disable all mods except xaero´s minimap, IF and fabric api, the map no shows in mosaic, but still shows anormally:

![javaw_2024_05_01_16_59_45_193](https://github.com/RaphiMC/ImmediatelyFast/assets/59809634/21106cde-f90f-491a-bb52-975a8e05d80e)
 the black zone it's irregular, and in 1.20.4, inmediatelyfast and xaero´s with the same mods works fine

**Comment by RaphiMC** [comment]
@rakantoh Can you test this build: https://upload.raphimc.net/file/o5vUgYjE4Ufa3kXG/w52wpYJnmBSa2GAX/ImmediatelyFast-Fabric-1.2.13-SNAPSHOT%2B1.20.6.jar

**Comment by rakantoh** [comment]
sorry im busy all day, with the new version in modrinth, the xaero´s works perfect, in 1.20.6, so i think that now the issue is closed now. Thanks.
