### ISSUE TITLE
In some cases, text is too close together

### ISSUE THREAD

**Issue by mrjasonn** [RaphiMC/ImmediatelyFast#198]
It seems like it might be to do with some symbols (tested in Hypixel Skyblock), and it seems like it might be to do with this mod since this mod has had some issues with text being squished before, but maybe the fix didn't fix everything or made some cases have this issue

**Comment by RaphiMC** [comment]
Try with only ImmediatelyFast installed. If it still happens upload game log + screenshots

**Comment by mrjasonn** [comment]
> Try with only ImmediatelyFast installed. If it still happens upload game log + screenshots

@RaphiMC I don't think the mods I'm using change parts of the text rendering that cause this. Meanwhile here is my mod list (maybe it can help): `boosted-brightness-2.2.0+1.20.1.jar fabric-api-0.97.8+1.20.6.jar ImmediatelyFast-Fabric-1.2.12+1.20.5.jar iris-1.7.0+mc1.20.6.jar lithium-fabric-mc1.20.6-0.12.3.jar reeses_sodium_options-1.7.2+mc1.20.5-build.103.jar sodium-extra-0.5.5+mc1.20.6-build.118.jar sodium-fabric-0.5.8+mc1.20.6.jar sodium-shadowy-path-blocks-3.3.0.jar WI-Zoom-1.5-MC1.20.6.jar`. I will look into this deeper as you said when I can. Meanwhile, other people who want this to get fixed faster, please do contribute what is needed if you can as I might not be able to do so as quickly.

**Comment by mrjasonn** [comment]
This seems like a vanilla bug in my detailed testing, if anyone catches some text that is actually squashed compared to vanilla because of this mod, please update this ticket with relevant information. Apologies for accidentally spamming the issue tracker.
