### ISSUE TITLE
ImmediatelyFast + Voxelmap + Smooth Scroll cause chat input field to not render on 1.20.6

### ISSUE THREAD

**Issue by nickademas** [RaphiMC/ImmediatelyFast#200]
also this message is spamming the logs
[19:27:47] [Render thread/WARN]: HUD batching was already active! endHudBatching() was not called before beginHudBatching(). This will cause rendering issues. 
[2024-05-01-5.log](https://github.com/RaphiMC/ImmediatelyFast/files/15179642/2024-05-01-5.log)
setting "hud_batching": to false in the config fixes this
i have also tested this on this build https://github.com/RaphiMC/ImmediatelyFast/actions/runs/8908622594 and then it also makes the game black but it doesn't say anything in log
![obraz](https://github.com/RaphiMC/ImmediatelyFast/assets/46594867/7cd4ecb1-8835-42dc-a74a-331cf5918c84)
[latest.log](https://github.com/RaphiMC/ImmediatelyFast/files/15179620/latest.log) (this is from this snapshot version)

**Comment by RaphiMC** [comment]
Can't reproduce the issue with the same mod list

**Comment by RaphiMC** [comment]
Can you check if the issue is fixed in this build: https://upload.raphimc.net/file/o5vUgYjE4Ufa3kXG/w52wpYJnmBSa2GAX/ImmediatelyFast-Fabric-1.2.13-SNAPSHOT%2B1.20.6.jar

**Comment by nickademas** [comment]
This build fixed that, thanks!
