### ISSUE TITLE
[1.20.4] wont start with optifine

### ISSUE THREAD

**Issue by undeadb0b** [RaphiMC/ImmediatelyFast#202]
if i start minecraft with optifine with immediatlyfast and optifine it crashes works with all my other mods

**Comment by RaphiMC** [comment]
Optifine is not supported

**Comment by undeadb0b** [comment]
damm fast response thx

**Comment by mrjasonn** [comment]
@2009pim2009, if you want an optimisation mod that is good (better than OptiFine), please download Sodium. If you need OptiFine features whilst using Sodium, there are plenty mods that do so. Please look into them if needed.
