### ISSUE TITLE
No F3+2/+3 screen in newest ImmediatelyFast

### ISSUE THREAD

**Issue by NeoXMinecraft** [RaphiMC/ImmediatelyFast#204]
I was making a new modpack and could not open an F3+2 and F3+3 hud. I wasted hours of my time figuring out the problem and eventually I found out that the last version of ImmediatelyFast just removes these hud elements. I think this is a bug and even if it improves performance it needs to be reverted. This is just my opinion and you can do whatever but I feel like this is a bad change.

**Comment by NeoXMinecraft** [comment]
Almost forgot to tell. The f3+2/+3 hud elements work without better f3 mod. And do not work with better f3 mod. This is a mod compatibility issue that only appeared in the latest update of IF. This was the issue in the first place. Sorry for inconvenience.

**Comment by NeoXMinecraft** [comment]
Also I noticed that when I try to open the hud it says this in log: [16:07:43] [Render thread/WARN]:
 HUD batching was already active! endHudBatching() was not called before beginHudBatching(). This will cause rendering issues.

**Comment by NeoXMinecraft** [comment]
[16:05:25] [main/INFO]:
 Loading 10 mods:
	- betterf3 9.0.2
	   \-- fabric-resource-loader-v0 0.11.15+78d798af4f
	- cloth-config 13.0.121
	   \-- cloth-basic-math 0.6.1
	- fabricloader 0.15.10
	   \-- mixinextras 0.3.5
	- immediatelyfast 1.2.13+1.20.4
	   \-- net_lenni0451_reflect 1.3.2
	- java 17
	- minecraft 1.20.4

**Comment by RaphiMC** [comment]
~~@NeoXMinecraft Can you check if this version fixes the issue: https://upload.raphimc.net/file/eObq5oEBjrxdTrpR/QXkN2sSIsE4b7saB/ImmediatelyFast-Fabric-1.2.14-SNAPSHOT%2B1.20.4.jar~~
Edit: It does not

**Comment by RaphiMC** [comment]
Fixed in next release.
You can download dev builds here:
* 1.20.5: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/8940479003
* 1.20: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/8940499274
* 1.19: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/8940533919
