### ISSUE TITLE
Korean sign textures bug

### ISSUE THREAD

**Issue by hybcp118** [RaphiMC/ImmediatelyFast#205]
If you write Korean on the sign, the writing on the sign will break strangely
Since I am Korean, please note that the translation may not be accurate
![2024-05-03_17 09 07](https://github.com/RaphiMC/ImmediatelyFast/assets/168722724/6a7348bb-e722-40ca-99ee-c6b5a1c69f25)

**Comment by RaphiMC** [comment]
You probably have the experimental sign buffering optimization enabled. Its known that this optimization currently doesn't work with non english characters. You can just disable it in the config file (immediatelyfast.json) until its fixed. For reference: #117

**Comment by lota09** [comment]
"experimental_sign_text_buffering": false,
