### ISSUE TITLE
[Bug] [After update] Incompatible with Detail Armor HUD

### ISSUE THREAD

**Issue by MbtMarco** [RaphiMC/ImmediatelyFast#206]
<img width="1440" alt="Screenshot 2024-05-03 alle 17 10 39" src="https://github.com/RaphiMC/ImmediatelyFast/assets/124934175/12197a40-a485-491e-b4b8-5a414f1e7aa7">

Just to show what I am wearing
<img width="1440" alt="Screenshot 2024-05-03 alle 17 10 43" src="https://github.com/RaphiMC/ImmediatelyFast/assets/124934175/f3e2c6b1-ecb9-4ea4-9227-5db670ccef0f">
I am sure it is a bug with Immediately Fast because after removing it, the issue is no longer occurs.

**Comment by RaphiMC** [comment]
Try with the latest dev build and upload the game log:
* 1.20.5: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/8940479003
* 1.20: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/8940499274
* 1.19: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/8940533919

**Comment by MbtMarco** [comment]
https://mclo.gs/ljnBqZh

<img width="1440" alt="Screenshot 2024-05-03 alle 19 25 01" src="https://github.com/RaphiMC/ImmediatelyFast/assets/124934175/95c19a8c-e7a8-4219-bbd1-6f9ec69b5681">
<img width="1440" alt="Screenshot 2024-05-03 alle 19 25 06" src="https://github.com/RaphiMC/ImmediatelyFast/assets/124934175/72a7527d-bd9c-4b2f-9673-dccf7d369a90">

**Comment by RaphiMC** [comment]
Where is the issue in those screenshots?

**Comment by MbtMarco** [comment]
Look at the armor bar, one slot is missing, and gold isnt visible

**Comment by MbtMarco** [comment]
The golden helmet probably doesn't appear because the first HUD slot isn't there

**Comment by MbtMarco** [comment]
<details>
  <summary>With Immediately Fast:</summary>

https://mclo.gs/J1dnDnL
![2024-05-03_20 03 50](https://github.com/RaphiMC/ImmediatelyFast/assets/124934175/e1c7d58a-d655-422a-862c-bd0f5d574ea2)
</details>

<details>
  <summary>Without Immediately Fast:</summary>

https://mclo.gs/VzGeYtD
![2024-05-03_20 06 48](https://github.com/RaphiMC/ImmediatelyFast/assets/124934175/bb94739b-5ab8-4341-b876-690c66e0340a)
</details>

**Comment by RaphiMC** [comment]
Will be fixed in the next release. You can download a dev build here: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/8943550310
