### ISSUE TITLE
Performance comparisons unclear 

### ISSUE THREAD

**Issue by MbtMarco** [RaphiMC/ImmediatelyFast#207]
![Screenshot_20240505_011607_GitHub.jpg](https://github.com/RaphiMC/ImmediatelyFast/assets/124934175/e08d8a76-340c-48fa-90c2-46deca43192a)
 How can Iris improve performance, it's a shader mod. Maybe you reversed the 2nd line with the 3rd.

**Comment by RaphiMC** [comment]
No this is correct. Iris has an entity batching system

**Comment by MbtMarco** [comment]
Oh, sorry, my bad 🙏
