### ISSUE TITLE
problem with the latest update for 1.20.1 on ImmediatelyFast 1.2.14

### ISSUE THREAD

**Issue by MCWither123go** [RaphiMC/ImmediatelyFast#209]
All items that are in your hotbar render with black text insted of vanilla one 

(Fabric issue) 

if you use obi and then crystal one or two times it makes all text black in hotbar like for item numbers :)

**Comment by RaphiMC** [comment]
Upload a screenshot of how it should be and how it is with IF as well as a game log

**Comment by MCWither123go** [comment]
> Upload a screenshot of how it should be and how it is with IF as well as a game log
![Screenshot_1](https://github.com/RaphiMC/ImmediatelyFast/assets/168990888/bed79d5e-6d0c-4b98-be57-7fc89c2d6158)


Alr I will

**Comment by RaphiMC** [comment]
Check if this version fixes the issue: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/8960248917

**Comment by MCWither123go** [comment]
> Check if this version fixes the issue: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/8960248917

alr give me half a minute to do it

**Comment by MCWither123go** [comment]
> Check if this version fixes the issue: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/8960248917

yeah this new version is perfect, thanks its fixed have a great day / night
