### ISSUE TITLE
Inventory Bar Will Disappear if I Enable ImmediatelyFast and JourneyMap at the Same Time.

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [RaphiMC/ImmediatelyFast#210]
ImmediatelyFast 1.2.14
JourneyMap 5.9.30
Here is the screenshot
![2024-05-06_17 35 58](https://github.com/RaphiMC/ImmediatelyFast/assets/42903464/a446c654-1ae8-407b-891a-f9aed43cb445)
And the log.
[latest.log](https://github.com/RaphiMC/ImmediatelyFast/files/15219003/latest.log)

**Comment by RaphiMC** [comment]
Can you test if the issue is still in the latest dev build: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/8960253920

**Comment by Shiroiame-Kusu** [comment]
> Can you test if the issue is still in the latest dev build: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/8960253920
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/42903464/3e082eac-847e-4d73-85a0-89839bf17e52)

![2024-05-06_18 32 18](https://github.com/RaphiMC/ImmediatelyFast/assets/42903464/a434cf35-4f35-46e9-821d-ac3938b89702)
Still not working, sad about this.

**Comment by Shiroiame-Kusu** [comment]
Fixed on JourneyMap side.
[#701](https://github.com/TeamJM/journeymap/issues/701)
