### ISSUE TITLE
Incompatibility with Item Counts

### ISSUE THREAD

**Issue by haaldor** [RaphiMC/ImmediatelyFast#214]
Hi,

Using "ImmediatelyFast" with "Item Counts" mod breaks it - the colour of the numbers is getting changed to black and some texts are moved elsewhere.

How it looks with those two mods:
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/18580752/c373e58d-a583-4b82-b77f-cdf88ead6dfe)
How it looks without "ImmediatelyFast" (and how it should look):
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/18580752/21d2bd88-6302-4c7b-8785-382b4d397f63)

More exactly, with those two mods together, all numbers on slot numbers less or equal to currently chosen slot are changed to black (so, if you have slot 3 chosen, slots 1, 2 and 3 will have black text and all the others have white, normal). Also text added by "Item Counts" is not visible.

**Comment by RaphiMC** [comment]
Already fixed. Downloaded the latest dev builds for your minecraft version: https://github.com/RaphiMC/ImmediatelyFast/actions

**Comment by haaldor** [comment]
Definitely still is an issue, I created fresh installation about 5 minutes before posting this issue, and it was MRE.
Using newest versions available on Modrinth/CurseForge, for version 1.20.1 (forgot to mention that, sorry):
- ImmediatelyFast v.1.2.14
- Item Counts v.1.4.1

So unless there's hidden new version that is not available on Modrinth, CurseForge and here on Github (Releases), it's still a thing as documented on pictures above.

**Comment by RaphiMC** [comment]
As I said, this issue is already fixed but there isn't a release yet on any of the publishing platforms as I won't make a release for every single bugfix. You can get the dev version (1.2.15) for 1.20.1 here: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/9066897186
