### ISSUE TITLE
Нехватка конкретной информации на странице разработки.

### ISSUE THREAD

**Issue by xbxct** [RaphiMC/ImmediatelyFast#215]
Все функции только примерно описаны в конфиг-файле, но нет никаких доказательств, что это будет работать правильно или вообще нужно, как например: "font_atlas_resizing". Помогает ли мод хоть какими-то опциями или же использует дорогостоящие алгоритмы? Разумеется помимо кеширования чего-то там в быстрый буфер.

**Comment by RaphiMC** [comment]
Please write issues in english

**Comment by xbxct** [comment]
You can auto translete this.

**Comment by xbxct** [comment]
All the functions are only roughly described in the config file, but there is no evidence that this will work correctly or at all necessary, such as: "font_atlas_resizing". Does the mod help with any options or does it use expensive algorithms? Of course, in addition to caching something there into a fast buffer.
