### ISSUE TITLE
Chat messages with a lot of components don't render fully

### ISSUE THREAD

**Issue by Ryhon0** [RaphiMC/ImmediatelyFast#218]
My server has a custom plugin, which replaces the vanilla chat and adds features like server side chat heads, which use a lot of components to render them. Using this mod causes only the first visible message to fully render. Tested on 1.2.15+1.20.6-fabric.  
You can join mc.ryhn.link (1.20.2, you might need Via) and send any message in chat to replicate this issue.  
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/21126698/cf9a78d6-798a-4d27-aba5-7633d8149679)
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/21126698/90c846a6-3054-4dc8-b90f-f692601841f0)

**Comment by Boy0000** [comment]
Had this problem aswell and boiled it down to usage of negative space unicodes
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/62521371/4fea0c3d-36e3-43a6-b360-4638092f757d)
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/62521371/93ceed7a-386f-4f7c-91f2-1b56adf61615)

Left is unmodded client | Right is with/without ImmediatlyFast
The text is just 2 unicodes with a negative advance in the middle
Positive advances have no problems

**Comment by RaphiMC** [comment]
@Ryhon0 The issue should be fixed now. Can you test this version: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/9244205033

@Boy0000 can you retest if this also fixes your issue

**Comment by Ryhon0** [comment]
Yup, fixed for me

**Comment by Boy0000** [comment]
works on my end to yeah 👍 
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/62521371/e6b1a112-2e23-4dd6-a132-bf061f126974)
