### ISSUE TITLE
Immedientlyfast creates a glitch for the conifg mod from the fog.

### ISSUE THREAD

**Issue by seryan4ik** [RaphiMC/ImmediatelyFast#222]
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/170634103/4c9cbfad-6878-4b15-95fb-595c4f1f7827)
The immedientlyfast mod is causing the problem, you can just disable it or go to mineraft/config/immediatelyfast.json and change the "hud_batching" value from true to false.

**Comment by RaphiMC** [comment]
Please provide more details, like a mod list, game log and a list of steps to reproduce the issue

**Comment by seryan4ik** [comment]
> Please provide more details, like a mod list, game log and a list of steps to reproduce the issue

install minecraft 1.20.4 + fabric + sodium + fabric.api + immedientlyfast + from the fog
in chat type "/function fromthefog:admin/config"

**Comment by RaphiMC** [comment]
@seryan4ik Can you check if its fixed in this version: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/9244167184

**Comment by seryan4ik** [comment]
> @seryan4ik Can you check if its fixed in this version: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/9244167184

Yes, its fixed, cheers!
