### ISSUE TITLE
new item rendering crash with emi

### ISSUE THREAD

**Issue by loti1234** [RaphiMC/ImmediatelyFast#226]
https://github.com/user-attachments/files/15525413/crash-2024-06-02_14.58.59-client.txt 

https://github.com/user-attachments/files/15525402/latest.log

**Comment by RaphiMC** [comment]
Can you try without any other mods installed except for EMI and IF. Also upload your log + IF config file (.minecraft/config/immediatelyfast.json) after reproducing without all the other mods

**Comment by loti1234** [comment]
ok so if and emi work with eachother its just this modpack crashing
imma reproduce the crash and log since it happened when the game was starting

**Comment by loti1234** [comment]
ok so it now doesn't crash
i think the crash was purely either because of resource packs or me doing stuff too fast when the game was still loading in stuff

**Comment by loti1234** [comment]
imma send log anyway

**Comment by loti1234** [comment]
[debug.log](https://github.com/user-attachments/files/15569587/debug.log)

[latest.log](https://github.com/user-attachments/files/15569589/latest.log)
