### ISSUE TITLE
[1.20.1] ImmediatelyFast 1.2.17 CEM not rendering

### ISSUE THREAD

**Issue by Ll66dar** [RaphiMC/ImmediatelyFast#228]
But version 1.2.15 works fine
![2024-06-10_22 24 00](https://github.com/RaphiMC/ImmediatelyFast/assets/147833042/980f4e0c-aa0d-4846-bc11-b7cd05ac92e1)

**Comment by RaphiMC** [comment]
Please provide more details such as game version, mod list and a game log

**Comment by Ll66dar** [comment]
[debug.log](https://github.com/user-attachments/files/15776970/debug.log)
[latest.log](https://github.com/user-attachments/files/15776972/latest.log)

**Comment by RaphiMC** [comment]
Please try with less mods (only the mods needed to reproduce the issue) as well as provide steps to reproduce the issue myself

**Comment by Ll66dar** [comment]
[debug.log](https://github.com/user-attachments/files/15777102/debug.log)
[latest.log](https://github.com/user-attachments/files/15777103/latest.log)
4 mods

**Comment by Ll66dar** [comment]
1. Launch forge 47.3.1 with mods entity_model_features_forge_1.20.1-2.0.2.jar, entity_texture_features_forge_1.20.1-6.0.1.jar, ImmediatelyFast-Forge-1.2.17+1.20.4.jar
2. download https://www.planetminecraft.com/texture-pack/hector-salamanca-creeper/
3. spawn creeper

**Comment by Ll66dar** [comment]
Entity Texture Features version 6.1. corrected the problem
