### ISSUE TITLE
This mod breaks the GUI with picture-to-picture overlay

### ISSUE THREAD

**Issue by AVuTuVA** [RaphiMC/ImmediatelyFast#23]
This mod breaks the GUI with picture-to-picture overlay
With mod:
![image](https://user-images.githubusercontent.com/66278054/211133555-2335d094-9c0f-47d8-813c-7ae2d2d7b1de.png)
Without mod:
![image](https://user-images.githubusercontent.com/66278054/211133661-b5d1dc7e-2bdf-4f50-8f7e-f9d6dc6c1520.png)

**Comment by AVuTuVA** [comment]
Without mod:
![image](https://user-images.githubusercontent.com/66278054/211133681-ee998558-cafc-4cae-abb2-f7797fc4643c.png)
I have attached this screenshot to make it clearer.

**Comment by RaphiMC** [comment]
Can you send me a link to that mod?

**Comment by HDBuster** [comment]
![immmediate_origins](https://user-images.githubusercontent.com/79605523/211213025-59b94ca9-ff71-4ff6-b2d4-2505280bda1e.png)
Same thing happens on Origin Realms server.

**Comment by RaphiMC** [comment]
Ok thats interesting thanks for finding out that the font_atlas_resizing causes that. As a temporary fix anyone affected can go edit the "config/immediatelyfast.json" file and disable that until I fixed it

**Comment by RaphiMC** [comment]
Should be fixed in ImmediatelyFast 1.1.7
