### ISSUE TITLE
1.20.1 Dissapearing Cross Hair issue 

### ISSUE THREAD

**Issue by S1L3NTTT** [RaphiMC/ImmediatelyFast#235]
Whenever I attack at all it doesnt matter if I hit something or even just hit the air, the attack indicator just dissapears. It's whenever I switch my texture pack but this has happened before and it was immediately fast but I want to use immediately fast so I came abck to it. 
[latest.log](https://github.com/user-attachments/files/15920273/latest.log)

**Comment by RaphiMC** [comment]
Feather client is not supported. Please try to replicate the issue without feather client (and without the other mods). If it doesn't happen without feather client, then you should report it to them, otherwise reopen the issue
