### ISSUE TITLE
Heavy FPS drops when rendering vanilla maps

### ISSUE THREAD

**Issue by MissPotato** [RaphiMC/ImmediatelyFast#236]
Java version 21
IF version 1.2.18
Fabric Loader 0.15.11
OS Linux 6.10.0-rc4-1-MANJARO

No other mods are enabled.
Attached is a zip containing the map, it is just a normal 1:16 map. 
The slowdown happens both in an item frame and in player's hand.

https://mclo.gs/vMyV8rk
[Map.zip](https://github.com/user-attachments/files/15934803/Map.zip)
![Screenshot from 2024-06-21 20-50-02](https://github.com/RaphiMC/ImmediatelyFast/assets/4769820/e803e0bf-ef1d-460c-ac0e-07d553a28e1e)

**Comment by RaphiMC** [comment]
Can't replicate the issue even with the map you uploaded. Could you upload a before/after screenshot of the F3 menu with vanilla and IF

**Comment by MissPotato** [comment]
![2024-06-22_10 47 23](https://github.com/RaphiMC/ImmediatelyFast/assets/4769820/a219f298-5f31-441a-89f1-a11935979ae3)
here is the map without IF

**Comment by RaphiMC** [comment]
Install the spark mod (https://modrinth.com/mod/spark) and run `/sparkc profiler start --thread * --timeout 15` and wait for 15 seconds. Send the generated link on github

**Comment by MissPotato** [comment]
Nothing has changed on my system, but it is now suddenly no longer happening. Despite happening every single time for the last couple of days. If it happens again, I'll run the profiler and provide the generated link.

**Comment by RaphiMC** [comment]
Thanks, I will close the issue for now. Just reopen it if it happens again

**Comment by MissPotato** [comment]
https://spark.lucko.me/dC5xagVEHB

Edit: I seem to be unable to open this issue back up, but here is a profiler of it happening.

**Comment by RaphiMC** [comment]
The profiler result doesn't show any indication of IF causing a slowdown, but rather operating system factors taking up a lot of time. You can disable the map rendering optimization in the config file (.minecraft/config/immediatelyfast.json) because I won't have the time to investigate whats at fault here, especially since this is the first report of the map optimization causing a slowdown

**Comment by MissPotato** [comment]
I'm thinking X11 (X11 is the windowing software aka x.org)and IF just don't play well together. Given the other issue I had talked about in discord with the weird frame times, while lowing the polling rate helped some, the issue is still present. X11 also seems to spike up when moving the mouse with IF installed.
