### ISSUE TITLE
Some items with custom models are invisible in hotbar

### ISSUE THREAD

**Issue by Defetyre** [RaphiMC/ImmediatelyFast#24]
![2023-01-07_21 12 59](https://user-images.githubusercontent.com/88449275/211155137-02c02b9c-a632-4ed6-880e-1f4dbf4a0e18.png)
Its already happened before, but one of the updates fixed it; after updating from 1.1.5 to 1.1.6, the issue came back.
This happens with things like Yttr's Rifle or with Wrench from Create.

**Comment by Defetyre** [comment]
It somewhat depends on which slot you place the items in, and it also affects blocks.

**Comment by RaphiMC** [comment]
Fixed in ImmediatelyFast 1.1.7
