### ISSUE TITLE
Poor performance on wynncraft beta with sodium

### ISSUE THREAD

**Issue by Packsolite** [RaphiMC/ImmediatelyFast#246]
Using ImmediatelyFast with sodium on the wynncraft beta yields significantly worse performance than compared to only sodium.

Screenshot F3 with Sodium + ImmediatelyFast
![image](https://github.com/user-attachments/assets/3a377c77-d0f6-444c-a83a-21cd5b9a4573)

Screenshot F3 with Sodium
![image](https://github.com/user-attachments/assets/d706cc2e-158a-46d3-91d8-907a461a60f0)

As you can see using ImmediatelyFast **decreases fps** while **increasing gpu** usage.

# System Information
NVIDIA RTX 3070
Intel i7-9700k
Windows 11

# Game Information
Minecraft 1.20.2
Sodium 0.5.5
ImmediatelyFast 1.2.18
Java 21.0.1 (Oracle)

**Comment by RaphiMC** [comment]
Upload the game log and a list of steps to reproduce the issue. Additionally install the spark mod and run the /sparkc profiler start - - timeout 30 command with and without ImmediatelyFast and send the results. You should stand still and at the same place while the profiler is running

**Comment by Packsolite** [comment]
**Log**: https://pastebin.com/NkKWXaFa
**Reproduce**: 
1. Install Sodium (and in 2. iteration ImmediatlyFast)
2. Join beta.wynncraft.com
3. Go to X=469 Y=67 Z=-1593 Yaw=0 Pitch=0
4. Check fps with and without ImmediatlyFast

**Profiler results**:
With IF: https://spark.lucko.me/dPrtHEVuSr
Without IF: https://spark.lucko.me/vNUtKo212M

**Edit**: Seems like ImmediatlyFast handles the text_ and item_display entities worse than sodium.
![image](https://github.com/user-attachments/assets/34a4063f-f86b-425c-b963-36e0f35e8c66)

**Comment by RaphiMC** [comment]
Seems like the server is using text rendering in a weird way which causes too many draw calls to be made. As a temporary workaround you can enable `experimental_disable_resource_pack_conflict_handling` in the ImmediatelyFast config (.minecraft/config/immediatelyfast.json) which will fix the lag issue but may introduce visual issues

**Comment by RaphiMC** [comment]
I have optimized the handling of those characters the server is rendering. Can you disable `experimental_disable_resource_pack_conflict_handling` again and test with this version of ImmediatelyFast: https://upload.raphimc.net/file/4KsbKEXF66BJ8kOt/4gNd1YyPEJLPOlzD/ImmediatelyFast-Fabric-1.2.19-SNAPSHOT.zip

**Comment by Packsolite** [comment]
> I have optimized the handling of those characters the server is rendering. Can you disable `experimental_disable_resource_pack_conflict_handling` again and test with this version of ImmediatelyFast: https://upload.raphimc.net/file/4KsbKEXF66BJ8kOt/4gNd1YyPEJLPOlzD/ImmediatelyFast-Fabric-1.2.19-SNAPSHOT.zip

Just tried it out and it's awesome. Fps drops are completly gone now. Great work!
![image](https://github.com/user-attachments/assets/9c2d1d33-1bfc-416a-89c9-024a52b149d4)
