### ISSUE TITLE
Changes Monitor Refresh Rate

### ISSUE THREAD

**Issue by Kruppelfield** [RaphiMC/ImmediatelyFast#248]
When toggling on fullscreen it changes my monitor refresh rate to 60Hz, despite trying out different settings to restore 144Hz.

**Comment by RaphiMC** [comment]
ImmediatelyFast does not change the monitor refresh rate

**Comment by Kruppelfield** [comment]
It does. As soon as I removed this mod, the refresh rate of my monitor didn't change anymore. It somehow affects the resolution and refresh rate.

**Comment by RaphiMC** [comment]
Do you have any other mods installed? The issue you are describing is very unusual and would be the first report of that happening

**Comment by Kruppelfield** [comment]
I used the modpack Fabulously Optimized, with all kinds of mods in it including Immediately Fast. I can't seem to replicate my issue tho for my own investigation of the actual cause of it. So it might have been windows itself making problems, who knows. Guess I will know more if it happens again in the future.
Sorry to bother you, have a good day!
