### ISSUE TITLE
Incompatible with Tubet

### ISSUE THREAD

**Issue by MKLEGOPRO** [RaphiMC/ImmediatelyFast#25]
In the Tubnet server, when playing the game Light Stryke, I can´t see how many players are left in the enemy team in the top menu. Plz fix. The server IP is tubet.gg
In the images the one that only shows how many people are left on my team I have the mod installed.
![2023-01-18_21 18 15](https://user-images.githubusercontent.com/117539010/213289862-a1489677-c97b-4f48-a777-3224792f3711.png)
![2023-01-18_21 32 17](https://user-images.githubusercontent.com/117539010/213289873-0b5c6652-f964-4813-8bbf-d0471c36b4d6.png)

**Comment by RaphiMC** [comment]
Please add more detail to your issue report. Screenshots, the server ip, a comparison with how it should look like, other installed mods

**Comment by MKLEGOPRO** [comment]
> Please add more detail to your issue report. Screenshots, the server ip, a comparison with how it should look like, other installed mods

Done! Also add that it is the latest version of the mod.

**Comment by RaphiMC** [comment]
Should be fixed in ImmediatelyFast 1.1.7
