### ISSUE TITLE
[1.21] Game does not start with ImmediatelyFast and Equipment Compare

### ISSUE THREAD

**Issue by OriginCode** [RaphiMC/ImmediatelyFast#253]
Log: https://mclo.gs/I4PlUMr

Tested with minimal reproducible environment: 4 mods: Fabric API, ImmediatelyFast, Iceberg (dependency of Equipment Compare) and Equipment Compare.

Disabling either ImmediatelyFast or Equipment Compare can solve the problem.

Ref: https://github.com/AHilyard/EquipmentCompare/issues/40

**Comment by cobaltlol2** [comment]
Can confirm this, I have the same problem/

**Comment by AHilyard** [comment]
Just wanted to note that this has been resolved in Equipment Compare/Iceberg as of the latest update.
