### ISSUE TITLE
[Bug] JourneyMap and f3 screen when minimap is enabled. 

### ISSUE THREAD

**Issue by mysticdrew** [RaphiMC/ImmediatelyFast#254]
A user reported this to me, they are running ImmediatelyFast-Fabric-1.2.18+1.21, they issue happens with all versions of JM for 1.21. 
 
The f3 text is light grey when the minimap is enabled and text on the minimap is drawing, infoslots and n|e|s|w points. 
I call `GuiGraphics#drawString` and this happens. When I disable text from drawing, the f3 screen is normal. 
I am not doing anything fancy here. 

![image](https://github.com/user-attachments/assets/6a270f03-a698-41d7-bc30-9e92cd7d5f1e)

**Comment by RaphiMC** [comment]
Try removing all other mods except for ImmediatelyFast and JourneyMap and check if the issue still happens

**Comment by mysticdrew** [comment]
> Try removing all other mods except for ImmediatelyFast and JourneyMap and check if the issue still happens

I verified that it occurs with with only jm, fapi, and IF.

**Comment by RaphiMC** [comment]
> > Try removing all other mods except for ImmediatelyFast and JourneyMap and check if the issue still happens
> 
> I verified that it occurs with with only jm, fapi, and IF.

Upload the game log of that session

**Comment by mysticdrew** [comment]
There are no errors, I'm not at my pc. Might be quicker to toss jm in your dev env to verify. 

Join game, press f3 see problem.

**Comment by tajemniktv** [comment]
Can also confirm. Opening chat somehow makes the F3 text go white as it should instead of light gray

EDIT: Removed edited update, made a new comment

**Comment by tajemniktv** [comment]
Update: 
It... fixed itself? By removing JourneyMap config files, updating JM and/or updating ImmediatelyFast... Not sure if these were even the "fixes" I applied that helped lol Discovered this by accident

**Comment by RaphiMC** [comment]
@mysticdrew Can you also confirm if the issue is fixed?

**Comment by mysticdrew** [comment]
Here is the situation, I found a work around. 
For the minimap text drawing, I was using `GuiGraphics#drawString` which was being broken by IF. 

I switched to using `Font#drawInBatch` which fixed it. 

However, you should also make sure you are not breaking the `GuiGraphics#drawString` methods in IF as that is the standard way of drawing text.

**Comment by RaphiMC** [comment]
I am very certain that `GuiGraphics#drawString` is not broken by IF because minecraft uses it all over the place for its own rendering. I assume there was another factor at play which caused some GL state to get corrupted.

**Comment by mysticdrew** [comment]
> I am very certain that `GuiGraphics#drawString` is not broken by IF because minecraft uses it all over the place for its own rendering. I assume there was another factor at play which caused some GL state to get corrupted.

That is kind of what it seems like. I tried to use RenderDoc to look into it but I didn't come up with much. But my RenderDoc skills are not great. The issue on my end was resolved in beta.19, if you are any good with RenderDoc and can see something happening in beta.18 and IF.
