### ISSUE TITLE
Invisible Crosshair

### ISSUE THREAD

**Issue by mattingg** [RaphiMC/ImmediatelyFast#255]
I am not sure if this is a bug or compatibility thing or not, but i have encountered an issue with this mod. My crosshair does not display when it is installed.

Please see client log here for all the details of version/mods i've got installed.

https://mclo.gs/6FbjTgp - It seems the HUD rendering is messing with the other HUD/GUI plugins that i have. 

I'd like to make a feature suggestion - Could you add a menu with this mod to enable/disable specific optimisations? As i would like to keep it installed, but is kinda hard to play without a crosshair. 

Thank you!

**Comment by RaphiMC** [comment]
Try disabling the `hud_batching` optimization in the config file

**Comment by mattingg** [comment]
That's fixed it for me, Thank you!
