### ISSUE TITLE
Wolf Collars Not Rendering Properly

### ISSUE THREAD

**Issue by CobaltNP** [RaphiMC/ImmediatelyFast#256]
Most of the wolf types are not rendering their collars at all, and some only when looking at them from certain angles. I'm not sure if its based on the type of the wolf because I didn't see the issue consistently with specific types.

https://github.com/user-attachments/assets/d3f6aa22-4c11-4994-ac06-a3fe4147742f

![2024-08-07_17 24 28](https://github.com/user-attachments/assets/19db56da-0d20-484b-8f29-19a474826189)
![2024-08-07_17 24 26](https://github.com/user-attachments/assets/c5e44e89-410f-4ca5-8b62-7d8e6ed02768)

**Comment by RaphiMC** [comment]
Try reproducing the issue only with ImmediatelyFast installed. Upload the game log and the test world if the issue still happens

**Comment by Panpuki** [comment]
I had this same issue as well, the moment I removed ImmediatelyFast the collars rendered properly again. The collars seemed fine on the original wolf texture but on the new 1.20.6 ones it would just disappear and reappear randomly.

**Comment by Panpuki** [comment]
https://github.com/user-attachments/assets/4928385e-9c7c-4a52-baf3-8ee3450e88df

I recorded a video of it in 1.21.1 with only ImmediatelyFast installed. The collars don't seem to render properly. I'm not sure how to get the game logs so sorry about that. I can also confirm this issue exists on the base 1.21 version as well.
