### ISSUE TITLE
[Fabric, 1.21, 1.2.19, crash] Incompatibility with TweakersMore (Rendering item in shulkerbox in hotbar)

### ISSUE THREAD

**Issue by tajemniktv** [RaphiMC/ImmediatelyFast#257]
Started happening after updating to 1.2.19

Environment et al. in logs below:
https://mclo.gs/c6vPb88

Issue on TweakerMore tracker:
https://github.com/Fallen-Breath/tweakermore/issues/73

**Comment by RaphiMC** [comment]
Fixed. You can download the dev build here: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/10317283543
