### ISSUE TITLE
Crash with AE2 encoded pattern items

### ISSUE THREAD

**Issue by shartte** [RaphiMC/ImmediatelyFast#258]
Reported here:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/8132

I don't know what immediatelyfast is doing exactly, but I'd assume it's due to AE2 replacing the model via Mixin when shift is held:
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/main/src/main/java/appeng/hooks/GuiGraphicsHooks.java#L46

**Comment by RaphiMC** [comment]
Already fixed in latest dev build. You can download it here: https://github.com/RaphiMC/ImmediatelyFast/actions
