### ISSUE TITLE
Weird crash with Shulker Preview mod, Fabric 1.20.4

### ISSUE THREAD

**Issue by Hlebuw3k** [RaphiMC/ImmediatelyFast#259]
Game crashed after I put a shulker of 3 elytras into my hotbar, then started crashing immediately after joining the server. This has not happened before, so I don't know why or what could be the reason.
[crash-2024-08-10_19.32.29-client.txt](https://github.com/user-attachments/files/16570324/crash-2024-08-10_19.32.29-client.txt)

I tried to set `"hud_batching": false,` in the config and it seems to have stopped the crashing.

Mod list with links:
<details>
<summary>
Click to expand
</summary>

- [Architectury](https://modrinth.com/mod/lhGA9TYQ) [11.1.17] by shedaniel
- [Xaero's World Map](https://modrinth.com/mod/NcUtCpym) [1.38.8] by xaero96
- [ModernFix](https://modrinth.com/mod/nmDcB62a) [5.17.0+mc1.20.4] by embeddedt
- [Cloth Config v13](https://modrinth.com/mod/9s6osm5g) [13.0.121] by shedaniel
- [ClickThrough](https://modrinth.com/mod/Z5b0cAlD) [1.20.4-fabric0.91.2-0.4.1] by Giselbaer
- [Lithium](https://modrinth.com/mod/gvQqBUqZ) [0.12.1] by JellySquid, 2No2Name
- [Entity Sound Features](https://modrinth.com/mod/IMuO8COj) [0.4] by Traben
- [essential-container](https://modrinth.com/mod/k2ZPuTBm) [1.0.0]
- [Resourcify](https://modrinth.com/mod/RLzHAoZe) [1.4.0] by DeDiamondPro
- [XaeroPlus](https://modrinth.com/mod/EnPUzSTg) [2.21] by rfresh2
- [Inventory Profiles Next](https://modrinth.com/mod/O7RBXm3n) [1.10.10] by mirinimi/blackd
- [LibJF](https://modrinth.com/mod/WKwQAwke) [3.14.3] by JFronny
- [Very Many Players](https://modrinth.com/mod/wnEe9KBa) [0.2.0+beta.7.139] by ishland
- [Mouse Tweaks](https://modrinth.com/mod/aC3cM3Vq) [2.26] by Ivan Molodetskikh (YaLTeR)
- [ViaFabricPlus](https://modrinth.com/mod/rIC2XJV4) [3.1.1] by FlorianMichael/EnZaXD, RK_01
- [Chat Tools](https://modrinth.com/mod/pbnlOdwp) [2.3.2] by 70CentsApple
- [Highlight](https://modrinth.com/mod/Vz96hXMh) [2.2.0] by ThatGravyBoat
- [Forge Config API Port](https://modrinth.com/mod/ohNO6lps) [20.4.3] by Fuzs
- [EntityCulling](https://modrinth.com/mod/NNAgCjsB) [1.6.6] by tr7zw
- [ukulib](https://modrinth.com/mod/Y8uFrUil) [1.1.2+1.20.4] by uku
- [Draggable Lists](https://modrinth.com/mod/aLcHfalx) [1.0.5] by MrMelon54
- [Balm](https://modrinth.com/mod/MBAkmtvl) [9.0.9] by BlayTheNinth
- [Krypton](https://modrinth.com/mod/fQEb0iXm) [0.2.6] by tuxed
- [Fabrishot](https://modrinth.com/mod/3qsfQtE9) [1.12.1] by ramidzkh
- [Durability Notifier](https://www.curseforge.com/projects/277095) [1.8.0] by Mrbysco
- [EnchantmentDescriptions](https://modrinth.com/mod/UVtY3ZAC) [20.1.7] by Darkhax
- [Iris](https://modrinth.com/mod/YL57xq9U) [1.7.2+mc1.20.4] by coderbot, IMS212, Justsnoopy30, FoundationGames
- [FerriteCore](https://modrinth.com/mod/uXXizFIs) [6.0.3] by malte0811
- [Noisium](https://modrinth.com/mod/KuNKN7d2) [2.0.3+mc1.20.2-1.20.4] by Steveplays28
- [ToolTip Fix](https://modrinth.com/mod/2RKFTmiB) [1.1.1-1.20] by kyrptonaught
- [Fadeless](https://modrinth.com/mod/ncKjyGm3) [1.0.1] by UltimateBoomer, DerpDerpling
- [Highlighter](https://modrinth.com/mod/cVNW5lr6) [1.1.9] by Grend
- [Bookshelf](https://modrinth.com/mod/uy4Cnpcm) [23.1.9] by Darkhax
- [Chunk Debug](https://modrinth.com/mod/zQxjhDPq) [1.1.0] by Sensei
- [Xaero's Minimap](https://modrinth.com/mod/1bokaNcj) [24.2.0] by xaero96
- [Simple Voice Chat](https://modrinth.com/mod/9eGKb6K1) [1.20.4-2.5.20] by Max Henkel
- [Zoomify](https://modrinth.com/mod/w7ThoJFB) [2.14.0+1.20.4] by isXander
- [3d-Skin-Layers](https://modrinth.com/mod/zV5r3pPn) [1.6.6] by tr7zw
- [More Chat History](https://modrinth.com/mod/8qkXwOnk) [1.3.0] by JackFred
- [libIPN](https://modrinth.com/mod/onSQdWhM) [4.0.2] by mirinimi/blackd
- [Skip Transitions](https://modrinth.com/mod/Zoz5HQjH) [1.3.3+mc1.20] by TrufflezMC
- [Sodium](https://modrinth.com/mod/AANobbMI) [0.5.8+mc1.20.4] by @jellysquid3
- [BadOptimizations](https://modrinth.com/mod/g96Z4WVZ) [2.1.4] by Thosea
- [UniLib](https://modrinth.com/mod/nT86WUER) [1.0.1] by CDAGaming
- [No Chat Reports](https://modrinth.com/mod/qQyHxfxd) [1.20.4-v2.6.1] by Aizistral
- [Essential Client](https://modrinth.com/mod/sH0dfrKf) [1.4.2] by Sensei
- [SignCopy](https://modrinth.com/mod/cK4nxndh) [1.1.1] by NotRyken
- [Vivecraft](https://modrinth.com/mod/wGoQDPN5) [1.20.4-1.1.11] by fayer3, Ferri_Arnus, IMS, jrbudda, minecraft player, Techjar
- [ModDetectionPreventer](https://modrinth.com/mod/lnxQbnYZ) [1.2.0] by JustAlittleWolf
- [MaLiLib](https://www.curseforge.com/projects/303119) [0.18.3] by masa
- [Litematica](https://www.curseforge.com/projects/308892) [0.17.3] by masa
- [AdvancementInfo](https://modrinth.com/mod/G1epq3jN) [1.20.4-fabric0.91.2-1.4] by Giselbaer
- [Sodium Extra](https://modrinth.com/mod/PtjYWJkn) [0.5.4+mc1.20.4-build.116] by FlashyReese
- [spark](https://modrinth.com/mod/l6YH9Als) [1.10.58] by Luck
- [More Culling](https://modrinth.com/mod/51shyZVL) [1.20.4-0.24.0] by FX - PR0CESS
- [Puzzle](https://modrinth.com/mod/3IuO68q1) [1.6.1+1.20.4] by PuzzleMC, Motschen
- [DCCH](https://modrinth.com/mod/sUbMm93i) [2.0+1.17] by anar4732, Emmaffle
- [Emoji Type](https://modrinth.com/mod/q7vRRpxU) [2.2.3+1.20.4] by CyborgCabbage, Norbiros
- [FastQuit](https://modrinth.com/mod/x1hIzbuY) [3.0.0+1.20.4] by KingContaria
- [RP Renames](https://modrinth.com/mod/hvqcuDMT) [0.8.2] by HiWord9
- [Model Gap Fix](https://modrinth.com/mod/QdG47OkI) [1.14] by Mehvahdjukaar
- [Remove Reloading Screen](https://modrinth.com/mod/ZP7xHXtw) [4.0.3+mc1.20.4-fabric] by dima_dencep
- [technomodel](https://modrinth.com/mod/BX3at1x4) [1.0.4] by thecolonel63
- [Better Statistics Screen](https://modrinth.com/mod/n6PXGAoM) [3.12.6+fabric-1.20.4] by TheCSDev
- [CompleteConfig](https://modrinth.com/mod/GtqG8z1h) [2.5.3] by Lortseam
- [AppleSkin](https://modrinth.com/mod/EsAfCjCV) [2.5.1+mc1.20.3] by squeek502
- [Runtime Resource Pack](https://modrinth.com/mod/USLVyT7V) [0.8.1] by HalfOf2
- [Inventory HUD +](https://www.curseforge.com/projects/357540) [3.4.24] by DmitryLovin
- [Entity Texture Features](https://modrinth.com/mod/BVzZfTc1) [6.1.3] by Traben
- [CraftPresence](https://modrinth.com/mod/DFqQfIBR) [2.5.0] by CDAGaming
- [CreativeCore](https://modrinth.com/mod/OsZiaDHq) [2.11.26] by CreativeMD, AriaFreeze
- [CICADA](https://modrinth.com/mod/IwCkru1D) [0.8.3+1.20.2-1.20.4] by enjarai
- [Mod Menu](https://modrinth.com/mod/mOgUt4GM) [9.2.0] by Prospector, haykam821, TerraformersMC
- [Visuality](https://modrinth.com/mod/rI0hvYcd) [0.7.4+1.20.4] by PinkGoosik
- [BetterF3](https://modrinth.com/mod/8shC1gFX) [9.0.2] by cominixo, TreyRuffy
- [Concurrent Chunk Management Engine](https://modrinth.com/mod/VSNURh3q) [0.2.0+alpha.11.70] by RelativityMC, ishland
- [Debugify](https://modrinth.com/mod/QwxR6Gcd) [1.20.4+1.1] by isXander
- [LambDynamicLights](https://modrinth.com/mod/yBW8D80W) [2.3.4+1.20.4] by LambdAurora
- [Roughly Enough Items](https://modrinth.com/mod/nfn13YXA) [14.1.742] by shedaniel
- [CalcMod](https://modrinth.com/mod/XoHTb2Ap) [fabric-1.20.2-1.3.1] by js802025, shadeydo
- [Dynamic FPS](https://modrinth.com/mod/LQ3K71Q1) [3.6.3] by juliand665, LostLuma
- [Memory Leak Fix](https://modrinth.com/mod/NRjRiSSD) [1.1.5] by FX - PR0CESS
- [MiniHUD](https://www.curseforge.com/projects/244260) [0.30.2] by masa
- [Beenfo](https://modrinth.com/mod/Bta0Pt47) [1.20.4-fabric0.91.2-1.3.4] by Giselbaer
- [Tweakeroo](https://www.curseforge.com/projects/297344) [0.19.2] by masa
- [FabricSkyBoxes](https://modrinth.com/mod/YBz7DOs8) [0.7.3+mc1.20.2] by AMereBagatelle
- [Carpet Mod](https://modrinth.com/mod/TQTTVgYE) [1.4.128+v231205] by gnembon, ...
- [Sign Edit Lite](https://modrinth.com/mod/QvdBkyYv) [1.0.1+mc1.20.4] by Pintér Gábor <pinter.gabor@gmx.at>
- [Controlling](https://modrinth.com/mod/xv94TkTM) [15.0.5] by Jaredlll08
- [Better Ping Display](https://modrinth.com/mod/MS1ZMyR7) [1.1.1] by Quintinity
- [YetAnotherConfigLib](https://modrinth.com/mod/1eAoo2KR) [3.5.0+1.20.4-fabric] by isXander
- [Raised](https://modrinth.com/mod/nCQRBEiR) [4.0.0] by yurisuika
- [Reese's Sodium Options](https://modrinth.com/mod/Bh37bMuy) [1.7.2+mc1.20.4-build.102] by FlashyReese
- [CIT Resewn](https://modrinth.com/mod/otVJckYQ) [1.1.4+1.20.4] by SHsuperCM
- [Enhanced Block Entities](https://modrinth.com/mod/OVuFYfre) [0.10.1+1.20.4] by FoundationGames
- [Continuity](https://modrinth.com/mod/1IjD5062) [3.0.0-beta.5+1.20.2] by PepperCode1
- [Essential Addons](https://modrinth.com/mod/3WQaouc1) [1.3.3] by SuperSanta, Sensei
- [e4mc](https://modrinth.com/mod/qANg5Jrr) [5.1.0] by skyevg
- [Cubes Without Borders](https://modrinth.com/mod/ETlrkaYF) [2.1.1+1.20] by Kir_Antipov
- [ToolStats](https://modrinth.com/mod/vuGFx44e) [19.0.3] by Darkhax
- [Chat Heads](https://modrinth.com/mod/Wb5oqrBJ) [0.12.10] by dzwdz, Fourmisain
- [Show Me Your Skin!](https://modrinth.com/mod/bD7YqcA3) [1.11.0+1.20.4] by enjarai
- [Entity Model Features](https://modrinth.com/mod/4I1XuqiY) [2.1.3] by Traben
- [TCD Commons API](https://modrinth.com/mod/Eldc1g37) [3.12.3+fabric-1.20.4] by TheCSDev
- [Gamma Utils](https://modrinth.com/mod/wdLuzzEP) [1.7.19] by Sjouwer
- [Chest Tracker](https://modrinth.com/mod/ni4SrKmq) [2.4.12+1.20.4] by JackFred
- [Language Reload](https://modrinth.com/mod/uLbm7CG6) [1.6.1+1.20.4] by Jerozgen
- [WorldEdit](https://modrinth.com/mod/1u6JkXh5) [7.3.0+6678-55745ad] by EngineHub
- [Bad Packets](https://modrinth.com/mod/ftdbN0KK) [0.6.1] by deirn
- [OptiGUI](https://modrinth.com/mod/JuksLGBQ) [2.3.0-beta.2] by opekope2
- [Jade](https://modrinth.com/mod/nvQzSEkH) [13.3.1] by Snownee
- [Animatica](https://modrinth.com/mod/PRN43VSY) [0.6.1+1.20.4] by FoundationGames
- [Better Mount HUD](https://modrinth.com/mod/kqJFAPU9) [1.2.2] by Lortseam
- [FabricSkyBoxes Interop](https://modrinth.com/mod/HpdHOPOp) [1.3.6+mc1.20.2-build.52] by FlashyReese
- [Replay Mod](https://modrinth.com/mod/Nv2fQJo5) [1.20.4-2.6.18] by CrushedPixel, johni0702
- [Polytone](https://modrinth.com/mod/3qAYkBMB) [1.20.4-1.18.10] by MehVahdJukaar
- [Plasmo Voice](https://modrinth.com/mod/1bZhdhsH) [2.0.10] by Plasmo
- Essential Dependencies [0]
- [Iceberg](https://modrinth.com/mod/5faXoLqX) [1.1.18] by Grend
- [Carpet TIS Addition](https://modrinth.com/mod/jE0SjGuf) [1.62.0] by Fallen_Breath ...
- [Simple Shulker Preview](https://modrinth.com/mod/MLwpdyw5) [2.4.2] by BVengo
- [MixinTrace](https://modrinth.com/mod/sGmHWmeL) [1.1.1+1.17] by comp500
- [ChatAnimation](https://modrinth.com/mod/DnNYdJsx) [1.0.5] by Ezzenix
- [Fabric API](https://modrinth.com/mod/P7dR8mSH) [0.97.1+1.20.4] by FabricMC
- [Fabric Language Kotlin](https://modrinth.com/mod/Ha28R6CL) [1.12.0+kotlin.2.0.10] by FabricMC
- [Indium](https://modrinth.com/mod/Orvt0mRa) [1.0.31+mc1.20.4] by comp500
- [NotEnoughAnimations](https://modrinth.com/mod/MPCX6s5C) [1.7.4] by tr7zw
- [AmbientSounds](https://modrinth.com/mod/fM515JnW) [5.3.9] by CreativeMD
- [Status Effect Bars](https://modrinth.com/mod/x02cBj9Y) [1.0.4] by Neecko5b84
- [uku's Armor HUD](https://modrinth.com/mod/wF189hn9) [0.4.2+mc1.20.3] by BerdinskiyBear, uku
- [kennytv's epic force close loading screen mod for Fabric](https://modrinth.com/mod/blWBX5n1) [2.2.1] by kennytv
- [Resource Pack Options](https://modrinth.com/mod/TiF5QWZY) [4.7.2] by JFronny
- [CraterLib](https://modrinth.com/mod/Nn8Wasaq) [2.0.3] by HypherionSA, Misha
- [ImmediatelyFast](https://modrinth.com/mod/5ZwdcRci) [1.2.19+1.20.4] by RK_01
</details>

**Comment by RaphiMC** [comment]
Fixed in the latest release (1.2.20)
