### ISSUE TITLE
HUD Batching breaks font of Stylish Effects' widget

### ISSUE THREAD

**Issue by twixstix** [RaphiMC/ImmediatelyFast#26]
With ImmediatelyFast:
![image](https://user-images.githubusercontent.com/28713862/213082290-14351632-598b-4e5c-88a8-2684699f47f3.png)

Without ImmediatelyFast or with HUD batching disabled:
![image](https://user-images.githubusercontent.com/28713862/213082426-66ace11e-98df-45bf-a972-eb9290e7aaec.png)

Tested with ImmediatelyFast 1.1.6 and [Stylish Effects](https://github.com/Fuzss/stylisheffects) 4.3.2.

**Comment by Julienraptor01** [comment]
Same issue on [Skyblocker LIAP](https://modrinth.com/mod/skyblocker-liap) 1.8.2
![Capture d’écran 2023-01-18 100822](https://user-images.githubusercontent.com/49841713/213129816-a0d6d903-c7b7-4a33-94bf-4b46a2839e2a.png)

**Comment by RaphiMC** [comment]
Should be fixed in ImmediatelyFast 1.1.7
