### ISSUE TITLE
Generating buffers is slower by 70x in some cases causing load times to be way longer (Only without sodium)

### ISSUE THREAD

**Issue by forkiesassds** [RaphiMC/ImmediatelyFast#260]
I have been having issues with long loading times on the Downloading Terrain screen. Upon profiling this is due to the fact this mod changes how buffers are generated. This might be an NVIDIA driver issue, unsure about that (I am using an NVIDIA Geforce RTX 3060, on Linux driver 555.58.02). Attached bellow are profiler results with and without the mod. The problem gets worse the higher the render distance is.

![image](https://github.com/user-attachments/assets/0d898403-a00d-49d5-bf6c-27324dba7670)
![image](https://github.com/user-attachments/assets/61b88f1f-bbb7-4830-8460-f01564c07e64)

**Comment by RaphiMC** [comment]
Upload your game log

**Comment by forkiesassds** [comment]
https://mclo.gs/Mg7h7fq 

Please ignore the JVM SIGBUS crash error, this is an NVIDIA driver bug. If this is a problem caused by another mod in my instance and not this one then it might be some sort of incompatibility.

**Comment by RaphiMC** [comment]
Known issue. Install sodium to fix that. I might look into excluding chunk buffers from the optimization

**Comment by forkiesassds** [comment]
Ok then. The only reason why I haven't installed Sodium is because I have been using Embeddium previously, and since the developer has halted development for Fabric 1.20.2+ I have not been using any form of Sodium since Minecraft runs fine on my computer.

**Comment by RaphiMC** [comment]
This is now fixed in the latest version (1.3.1)
