### ISSUE TITLE
Some text renders incorrectly

### ISSUE THREAD

**Issue by JustAlittleWolf** [RaphiMC/ImmediatelyFast#261]
Some text using imprinting, like this (vanilla): 
![image](https://github.com/user-attachments/assets/cb2649fc-871e-452a-b09b-302f293a0ab3)
renders incorrectly with ImmediatelyFast installed. With the mod installed it looks like this:
![image](https://github.com/user-attachments/assets/97012ba8-350a-447c-aee9-4d9a6301cbfb)
It looks like the text shadow is being drawn, when it's not supposed to.

This might be related to https://github.com/RaphiMC/ImmediatelyFast/issues/81

This occurs on a server called wynncraft, where this text trick is used sometimes.

**Comment by RaphiMC** [comment]
Upload game log, ImmediatelyFast config and provide a list of steps how to reproduce this issue

**Comment by JustAlittleWolf** [comment]
[latest_withoutSodium.log](https://github.com/user-attachments/files/16580522/latest_withoutSodium.log)
[latest_withSodium.log](https://github.com/user-attachments/files/16580523/latest_withSodium.log)
[immediatelyfast.json](https://github.com/user-attachments/files/16580526/immediatelyfast.json)

To reproduce:
- use wynncraft texture pack (some of the textures show up bugged, but that doesn't affect the issue)
[c617fc88fa1c736fa0b8b36715dd9b002acc7db4-unpacked.zip](https://github.com/user-attachments/files/16580614/c617fc88fa1c736fa0b8b36715dd9b002acc7db4-unpacked.zip)
- go into a singleplayer world with cheats on
- use a command block to run the following command: https://pastebin.com/raw/AJxtPW8C


With IF:
![image](https://github.com/user-attachments/assets/2dfc785e-7ed9-482d-a811-84f4f876d46b)

Without IF:
![image](https://github.com/user-attachments/assets/fea1ec0d-3f4a-481f-897b-b8699bec4553)

**Comment by RaphiMC** [comment]
Can you check if this version of ImmediatelyFast renders it correctly and didn't introduce any new rendering issues: https://upload.raphimc.net/file/UfSAaJu44T1IPg9X/aBervdxBJk2qlSy2/ImmediatelyFast-Fabric-1.2.21-SNAPSHOT%2B1.21.1.jar

**Comment by JustAlittleWolf** [comment]
Yes this fixes the issue! Thanks for the quick response.
