### ISSUE TITLE
Simplified Chinese text render incorrectly

### ISSUE THREAD

**Issue by Vangeger** [RaphiMC/ImmediatelyFast#262]
I don't know ,but maybe it's the same bug as #261 .
Some text ,like this:
![image](https://github.com/user-attachments/assets/7371f279-11be-4551-845e-05067803a7ac)
display incorrectly.
This occurs on my own PC , when I play the modpack "Simply Optimized".

**Comment by RaphiMC** [comment]
Duplicate of #205
