### ISSUE TITLE
ImmediatlyFast breaks NoShadow in Bossbar

### ISSUE THREAD

**Issue by davidmayr** [RaphiMC/ImmediatelyFast#266]
ImmediatlyFast breaks NoShadow (https://github.com/PuckiSilver/NoShadow) when used in the BossBar. 

This breaks the look of the bossbar on servers like Cytooxien.de. I have confirmed this issue to exist with a clean installation with only ImmediatelyFast installed.

Vanilla:
![grafik](https://github.com/user-attachments/assets/d5d0ac79-5fdc-4d79-940b-cbdd7c3e5f88)

ImmediatelyFast:
![grafik](https://github.com/user-attachments/assets/3770a0db-3e7d-447b-851e-80b70b5fe210)

**Comment by RaphiMC** [comment]
Upload the game log

**Comment by davidmayr** [comment]
> Upload the game log

This is the log from joining cytooxien.de: https://mclo.gs/ry2pmOV
And this is a log (from a newly restarted client) with the texture pack applied on a single player world: https://mclo.gs/teCzi1o

Also, this glitch seems to only apply when negative spaces are used.

To reproduce:

Use the shader pack I provided above and my cut down texture pack I linked below, create the bossbar "test" and add yourself to it and insert this command into a command block: (It's encoded in base64 since GitHub seems to break my Unicode characters...):
```Ym9zc2JhciBzZXQgbWluZWNyYWZ0OnRlc3QgbmFtZSB7ImNvbG9yIjoiIzRFNUMyNCIsImZvbnQiOiJjYWZlc3R1YmU6cm91bmRlZC1iZy1vZmZzZXQiLCJleHRyYSI6W3sidGV4dCI6IlsifSx7ImZvbnQiOiJjYWZlc3R1YmU6c3BhY2UiLCJ0ZXh0Ijoi84+/vyJ9LHsidGV4dCI6IjYifSx7ImZvbnQiOiJjYWZlc3R1YmU6c3BhY2UiLCJ0ZXh0Ijoi84+/vyJ9LHsidGV4dCI6IjYifSx7ImZvbnQiOiJjYWZlc3R1YmU6c3BhY2UiLCJ0ZXh0Ijoi84+/vyJ9LHsidGV4dCI6IjYifSx7ImZvbnQiOiJjYWZlc3R1YmU6c3BhY2UiLCJ0ZXh0Ijoi84+/vyJ9LHsidGV4dCI6IjYifSx7ImZvbnQiOiJjYWZlc3R1YmU6c3BhY2UiLCJ0ZXh0Ijoi84+/vyJ9LHsidGV4dCI6IjYifSx7ImZvbnQiOiJjYWZlc3R1YmU6c3BhY2UiLCJ0ZXh0Ijoi84+/vyJ9LHsidGV4dCI6IjYifSx7ImZvbnQiOiJjYWZlc3R1YmU6c3BhY2UiLCJ0ZXh0Ijoi84+/vyJ9LHsidGV4dCI6IjQifSx7ImZvbnQiOiJjYWZlc3R1YmU6c3BhY2UiLCJ0ZXh0Ijoi84+/vyJ9LHsidGV4dCI6IjMifSx7ImZvbnQiOiJjYWZlc3R1YmU6c3BhY2UiLCJ0ZXh0Ijoi84+/vyJ9LHsidGV4dCI6IlsifV0sInRleHQiOiIifQ==```



Test pack: [cafestube-pack - Kopie.zip](https://github.com/user-attachments/files/16737504/cafestube-pack.-.Kopie.zip)

**Comment by qdpy** [comment]
Same issue!

**Comment by emmanuelvlad** [comment]
Possible regression from https://github.com/RaphiMC/ImmediatelyFast/commit/b79ff58b6784f4f5eb5507c0f681ff43dd1e8859 ?

**Comment by RaphiMC** [comment]
The NoShadow resource pack is modifying core shaders which are not supported by ImmediatelyFast (and even Mojang said that modifying core shaders is not supported).

The fix is pretty simple, so heres a fixed version of the pack: [NoShadow-v2.1.0.zip](https://github.com/user-attachments/files/16788043/NoShadow-v2.1.0.zip)
