### ISSUE TITLE
IF started crashing with oWo lib this month, regardless of version of IF

### ISSUE THREAD

**Issue by Barerock** [RaphiMC/ImmediatelyFast#268]
[latest.log](https://github.com/user-attachments/files/16825729/latest.log)
[crash-2024-08-31_14.52.29-client.txt](https://github.com/user-attachments/files/16825731/crash-2024-08-31_14.52.29-client.txt)

These mods crash alone as well, and it's not 100% of the time, only about 60%, otherwise the game starts and runs fine. These crashes have gotten more frequent this month, and version of IF doesn't seem to matter. oWo hasn't been updated for a long time, so I have not tried backdating it.

**Comment by RaphiMC** [comment]
Seems to be unrelated to IF

**Comment by Barerock** [comment]
It's 100% related if I can reproduce this with only these mods. oWo dev also states that IF is clearly an issue when they're loaded together.

**Comment by RaphiMC** [comment]
Then do that and upload the log
