### ISSUE TITLE
Use more accessor mixins then accesswideners

### ISSUE THREAD

**Issue by mrjasonn** [RaphiMC/ImmediatelyFast#274]
Seems like a good change

**Comment by RaphiMC** [comment]
I don't see why this would be a good change. Accessors just adds more interface classes to the project for no benefit. Accessor mixins are also slightly worse performing during runtime than access wideners.

**Comment by mrjasonn** [comment]
> I don't see why this would be a good change. Accessors just adds more interface classes to the project for no benefit. Accessor mixins are also slightly worse performing during runtime than access wideners.

@RaphiMC Hey, please read [this](https://gist.github.com/lukebemish/f40456f16396e417b592ac47eb3363e9), it gives some information about why accessor mixins would be better, in cases such as safety.

**Comment by RaphiMC** [comment]
> > I don't see why this would be a good change. Accessors just adds more interface classes to the project for no benefit. Accessor mixins are also slightly worse performing during runtime than access wideners.
> 
> @RaphiMC Hey, please read [this](https://gist.github.com/lukebemish/f40456f16396e417b592ac47eb3363e9), it gives some information about why accessor mixins would be better, in cases such as safety.

I glanced over it and couldn't find any good/applicable reasons why I should switch to mixin accessors.

**Comment by Gaming32** [comment]
I doubt accessor mixins are less performant to be honest, but I personally see no reason to switch.

**Comment by RaphiMC** [comment]
> I doubt accessor mixins are less performant to be honest, but I personally see no reason to switch.

The JVM most likely optimizes the casts and method invocations, but it still makes the code look uglier for no benefit
