### ISSUE TITLE
ATM 10 1.6+ Server Issue wherein blocks are breaking instantly regardless of tool (or fist)

### ISSUE THREAD

**Issue by ster-the-pot** [RaphiMC/ImmediatelyFast#280]
Issue when upgrading from 1.4->1.6+ wherein all blocks break near instantly. Can attest that this issue ONLY occurs AFTER dragging over (and replacing) a world file from a previous ATM version.

Steps to recreate:
1) Spin up new 1.6/7 server
2) Accept EULA and Start
3) Delete World File and Drag over previous
4) Start server
5) Login and experience issue

I am not the only one experiencing this, attached below is a reddit post pointing out the exact same issue.

https://www.reddit.com/r/allthemods/comments/1gbcgc9/fast_breaking_with_fist_atm10/

**Comment by PatrioticCross** [comment]
This is an Onion Ring upgraded

**Comment by RaphiMC** [comment]
Not related to ImmediatelyFast
