### ISSUE TITLE
[1.21.3] "experimental_screen_batching" causes slot highlighting to render incorrectly

### ISSUE THREAD

**Issue by ImGRUI** [RaphiMC/ImmediatelyFast#281]
Using "experimental_screen_batching": true causes slot highlighting to be more transparent than it should be.

Fabric 0.16.7
Using only Sodium-beta.3 and ImmediatelyFast 1.3.0

Disabled:

https://github.com/user-attachments/assets/895fd980-dd34-4719-829d-226dc4c64fc5

Enabled:

https://github.com/user-attachments/assets/b9849646-579a-4b91-b8be-0749f40da919

Also can be reproducible in creative menu.

**Comment by RaphiMC** [comment]
Thanks for reporting. Fixed it in the latest builds: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/11531074331
