### ISSUE TITLE
Item does not render properly when on cooldown

### ISSUE THREAD

**Issue by mrjasonn** [RaphiMC/ImmediatelyFast#282]
An item (e.g. ender pearl) does not render properly when on cooldown. I have tested this with IF and without IF only. No other mods were used in testing. Build of IF I used is the one you provided to me that disabled fast buffer upload optimization on macOS.
With IF:
![2024-10-29_22 06 13](https://github.com/user-attachments/assets/31b6e786-5d6e-4062-b893-3295f21de7b1)
Without IF:
![2024-10-29_22 07 09](https://github.com/user-attachments/assets/0a914d0a-6cc8-4272-9f77-d56e45e4c691)
Log with IF: [https://mclo.gs/O9AuIyY](https://mclo.gs/O9AuIyY)
Log without IF: [https://mclo.gs/GOANb2V](https://mclo.gs/GOANb2V)
A lot of the log spam is due to a Hypixel bug.

**Comment by RaphiMC** [comment]
Fixed in latest dev build: https://github.com/RaphiMC/ImmediatelyFast/actions/runs/11581141931
