### ISSUE TITLE
Inventory title rendering order differs from vanilla

### ISSUE THREAD

**Issue by aerulion** [RaphiMC/ImmediatelyFast#287]
On our server, we use custom ui that is made using a custom font as the inventory / container title. If the custom ui texture is overlapping with the bottom inventory text/title, the bottom text should be rendered on top of the top inventory title, at least vanilla handles it that way. When using ImmediatelyFast, the top inventory title will be rendered on top, making the bottom inventory title unreadable if the texture overlaps with it. See attached image for an easier explanation.
![if-bug](https://github.com/user-attachments/assets/0d805a16-4bb8-40e1-be28-5f59889f24f7)

**Comment by RaphiMC** [comment]
Upload the game log, the server resource pack and provide steps to reproduce the issue (For example using a /give command to give a chest with a custom inventory title)

**Comment by aerulion** [comment]
I made a demo pack using just the 2 fonts and a single ui texture, tinted a bit to make it easier to distinguish.
A chest for demo purposes can be created using the following command (all tested in 1.21.3):
`/setblock ~ ~ ~ chest{CustomName:'[{"color":"white","font":"negative_space","text":"h"},{"color":"white","font":"gui","text":"a"}]'} destroy`
[if-bug-pack.zip](https://github.com/user-attachments/files/17681264/if-bug-pack.zip)
[latest.log](https://github.com/user-attachments/files/17681364/latest.log)

**Comment by RaphiMC** [comment]
This should be fixed now. You can get the latest dev build of ImmediatelyFast here: https://github.com/RaphiMC/ImmediatelyFast/actions/workflows/build.yml

**Comment by aerulion** [comment]
The dev build works perfectly, thank you for the quick fix! :)
