### ISSUE TITLE
Title text shadow rendering differs from vanilla

### ISSUE THREAD

**Issue by Septicuss** [RaphiMC/ImmediatelyFast#288]
**Background**
Hey! I'm the developer of the "Tooltips" Spigot plugin. The plugin creates tooltips using resource packs and displays them in titles (more specifically subtitles). This is done by laying multiple layers on top of each other using negative spaces. Consists of the background and the actual text.

**Issue**
In vanilla, the rendering order seems to offset the shadows behind the background. In ImmediatelyFast however, this seems to not be the case.

Without ImmediatelyFast (Vanilla):
![image](https://github.com/user-attachments/assets/ac3079ba-d8cf-4bf9-a096-d16884ba7a85)

With ImmediatelyFast:
![image](https://github.com/user-attachments/assets/53708338-8fd8-4395-968d-42eecaf5c9ee)

**Reproducing the issue**

1. Attached, is a zip file, containing a resource pack namespace folder `tooltips`. This folder can be dragged into any resource packs' `assets` directory.
[tooltips-namespace.zip](https://github.com/user-attachments/files/17685287/tooltips-namespace.zip)

2. Once in-game with the resource pack applied. The following commands can be used to show the tooltip (note: commands too long for chat):
```
/title @s title {"extra":[{"font":"tooltips:space","text":""},{"color":"#ffffff","font":"tooltips:themes/default-two-line","text":""},{"color":"#ffffff","font":"tooltips:space","text":""},{"color":"white","font":"tooltips:lines/-2","text":"Hel"},{"color":"white","font":"tooltips:lines/-2o","text":"l"},{"color":"white","font":"tooltips:lines/-2","text":"o!"},{"color":"white","font":"tooltips:space","text":""},{"color":"white","font":"tooltips:lines/-7","text":"Second"},{"color":"white","font":"tooltips:space","text":""},{"color":"white","font":"tooltips:lines/-7","text":"l"},{"color":"white","font":"tooltips:lines/-7o","text":"ine"}],"text":""}

/title @s subtitle {"text":""}

/title @s times 0 1000000d 0
``` 

3. The result should look like the vanilla one attached in the "Issue".

**Other**

Logs: [game-log.txt](https://github.com/user-attachments/files/17685296/game-log.txt)
Resource pack: [tooltips-namespace.zip](https://github.com/user-attachments/files/17685287/tooltips-namespace.zip)

**Comment by RaphiMC** [comment]
This should be fixed now. You can get the latest dev build of ImmediatelyFast here: https://github.com/RaphiMC/ImmediatelyFast/actions/workflows/build.yml
