### ISSUE TITLE
[Bug] REI GUIs are not at the correct position

### ISSUE THREAD

**Issue by Wudji** [RaphiMC/ImmediatelyFast#291]
from https://github.com/shedaniel/RoughlyEnoughItems/issues/1753

**Comment by RaphiMC** [comment]
Upload the ImmediatelyFast config file

**Comment by RaphiMC** [comment]
Opened a PR on their repo: https://github.com/shedaniel/RoughlyEnoughItems/pull/1768

Not fixable on ImmediatelyFast's side
