### ISSUE TITLE
Chat covers up name of held items in latest version

### ISSUE THREAD

**Issue by FacelessAssassin** [RaphiMC/ImmediatelyFast#295]
MC Version: 1.21.3
Mod Version: 1.3.1+1.21.3-fabric
Description of Issue: When the name of an item appears over the hotbar, if there is chat on the screen at the same time the chat box will hide the name of the item

![2024-12-02_23 40 46](https://github.com/user-attachments/assets/a259a186-d33b-486e-8e78-ec2b8bd98de6)

**Comment by FacelessAssassin** [comment]
Update: I accidentally put the wrong version, it's 1.3.2 and also I tested on a profile with just immediatelyfast and it's a compatibility issue between immediatelyfast and one of my other mods making it not work

**Comment by RaphiMC** [comment]
Upload the game log or a mod list

**Comment by FacelessAssassin** [comment]
https://pastebin.com/mxf8a3Ga
Oddly enough I tested on another profile with the exact same mods and it didn't happen on that one

**Comment by RaphiMC** [comment]
Closing the issue then. You can reopen it if you find a way to consistently reproduce the issue with as few mods as possible
