### ISSUE TITLE
CurseForge upload

### ISSUE THREAD

**Issue by RaptaG** [RaphiMC/ImmediatelyFast#3]
I dislike CF, but somebody had to do this job..

Why?

- Most people use CF -> More popularity for the mod
- CurseForge rewards -> You get paid

**Comment by RaphiMC** [comment]
I don't really like CF and having an additional page where I need to update releases or respond to comments just increases work for me. Is there a particular reason CF is needed? Modrinth is like CF but much better.

**Comment by Julienraptor01** [comment]
> 

i agree however no CF mean that it can't be included in a modpack on CF which is bad since it's still the one site for nearly every player
if you are too lazy to upload by yourself tools do exit
https://github.com/marketplace/actions/publish-minecraft-mods

**Comment by RaptaG** [comment]
> I don't really like CF

So do I.

> Having an additional page where I need to update releases or respond to comments just increases work for me.

You can use [mc-publish](https://github.com/Kir-Antipov/mc-publish) to automate this process.

> Is there a particular reason CF is needed?

Including it in modpacks, such as [Fabulously Optimized](https://github.com/Fabulously-Optimized/fabulously-optimized/issues/490).

**Comment by RaphiMC** [comment]
I will make a CF release in the next couple of days when I have time for that

**Comment by RaphiMC** [comment]
I made a project for the mod on CF: https://www.curseforge.com/minecraft/mc-mods/immediatelyfast
This issue will be closed once it got approved

**Comment by RaphiMC** [comment]
Mod got approved
