### ISSUE TITLE
Rendering glitch with Xaero's Minimap

### ISSUE THREAD

**Issue by embeddedt** [RaphiMC/ImmediatelyFast#30]
I'm testing using the latest versions of Xaero's and ImmediatelyFast on 1.19.2. I have not tried this in a standalone instance yet to confirm the issue still happens there. Other potentially important mods are Sodium, Exordium, and Flywheel.

![image](https://user-images.githubusercontent.com/42941056/213754486-243d99a6-11f1-4f00-8ffe-e9c87699a7be.png)

**Comment by RaphiMC** [comment]
Please try a standalone instance. I assume it might be Exordium

**Comment by Timolino456** [comment]
This is an Exordium issue: https://github.com/tr7zw/Exordium/issues/15

**Comment by Timolino456** [comment]
This is an Exordium issue: https://github.com/tr7zw/Exordium/issues/15

**Comment by RaphiMC** [comment]
I will close the issue then
