### ISSUE TITLE
Item rendering looks weird (Don't know how to explain this)

### ISSUE THREAD

**Issue by stantios** [RaphiMC/ImmediatelyFast#34]
Mod Version: 1.1.8
Loader: Fabric
Loader Version: 0.14.13

Description: Item rendering is all over the place as seen in the screenshots. I'm sure what the problem is or how to solve it
Screenshots - MCC Island: 
![image](https://user-images.githubusercontent.com/98621617/214937782-ad49a906-05a2-4f21-b68e-37c8c1de1ce1.png)

Tubnet: 
![image](https://user-images.githubusercontent.com/98621617/214937954-3a0806e4-6fb1-4a4d-80de-c353921e09c6.png)

My Config: 
![image](https://user-images.githubusercontent.com/98621617/214938055-ccf18b5a-5a6c-4d2c-b885-5b9f0e2a0bb0.png)

**Comment by RaphiMC** [comment]
You have graphical glitches all over the place. Even in places not touched by IF like the chunk rendering. Try updating your GPU driver

**Comment by RaphiMC** [comment]
Also post a full mod list as well

**Comment by stantios** [comment]
Well, you see. I'm on MacOS and the latest update I can update to is 10.13.6 which I'm already on. When using the 1.1.6 version of the mod, everything looks fine

**Comment by RaphiMC** [comment]
Can you try the 1.1.7 version? Also do the graphical glitches happen consistently or randomly?

**Comment by stantios** [comment]
> Also post a full mod list as well

I'm using the mods in Fabulously Optimized and this mod.

**Comment by RaphiMC** [comment]
Can you send your latest.log file or the mod section at the top of it? I want a concrete mod list with their versions

**Comment by stantios** [comment]
Sure! Let me try 1.1.7 first and see if I get the issue

**Comment by stantios** [comment]
> Can you try the 1.1.7 version? Also do the graphical glitches happen consistently or randomly?

I can see the items but the items in my hand are really glitchy and they seem to happen consistently.

MCC Island: 
![image](https://user-images.githubusercontent.com/98621617/214939612-fa3a48eb-effb-4ec1-9fc6-9b750e518775.png)

Tubnet: 
![image](https://user-images.githubusercontent.com/98621617/214939807-80ebf802-086f-4856-b075-2cc9d0597204.png)

**Comment by stantios** [comment]
> Can you send your latest.log file or the mod section at the top of it? I want a concrete mod list with their versions

Here you go: https://mclo.gs/bwvhZ1w

**Comment by RaphiMC** [comment]
This is very odd, can you try replicating this issue with only ImmediatelyFast and no other mods installed.
I also spoke to a person on my discord with MacOS knowledge and I found out that you use a hackintosh with ancient hardware. This might be a configuration I can't support with ImmediatelyFast due to how old your GPU is

**Comment by akemin-dayo** [comment]
~~Are you using a Hackintosh? (I'm not aware of any Apple hardware that includes an i7-870 CPU, but I could be wrong about that.)~~ Never mind, it appears that you're using an `iMac11,3`.

Either way, it appears that your GPU is _really_ old (an ATi Radeon HD 5750 from 2009 using the TeraScale 2 architecture), and is most likely the cause of this issue.

Does this issue occur without ImmediatelyFast present? (※ Rename the `.jar` extension to `.jar.disabled` or something, or simply just move it out of your mods folder temporarily.)

If so, this may be an issue caused by Sodium.

**Comment by stantios** [comment]
Nope, I'm using High Sierra 10.13.6. Also, this issue does not occur when ImmediatlyFast is present as seen here.

MCC Island: 
![image](https://user-images.githubusercontent.com/98621617/214941726-d27d03da-0711-455b-96e4-b293a438a958.png)

Tubnet: 
![image](https://user-images.githubusercontent.com/98621617/214941834-35e0e22d-1578-4ec7-93f7-e5bd0d521079.png)

**Comment by RaphiMC** [comment]
I am not too sure where to go from here. I asume its caused by your ancient GPU. One last thing you can try is setting `debug_only_and_not_recommended_disable_universal_batching` to true and trying it again

**Comment by stantios** [comment]
> This is very odd, can you try replicating this issue with only ImmediatelyFast and no other mods installed. I also spoke to a person on my discord with MacOS knowledge and I found out that you use a hackintosh with ancient hardware. This might be a configuration I can't support with ImmediatelyFast due to how old your GPU is

Yep, here you go: 
![image](https://user-images.githubusercontent.com/98621617/214942971-4dfd7b81-659e-42c6-a1c8-2f0c3f8ebb36.png)
![image](https://user-images.githubusercontent.com/98621617/214943160-6b657882-4aa3-4649-bf11-fa2c96312442.png)

**Comment by RaphiMC** [comment]
I think it might be `fast_buffer_upload`. Disable that and try again. Also revert the previous change because its a debugging only option

**Comment by stantios** [comment]
> I am not too sure where to go from here. I asume its caused by your ancient GPU. One last thing you can try is setting `debug_only_and_not_recommended_disable_universal_batching` to true and trying it again

Yeah, this didn't work

**Comment by stantios** [comment]
> I think it might be `fast_buffer_upload`. Disable that and try again. Also revert the previous change because its a debugging only option

This actually worked.

MCC Island: 
![image](https://user-images.githubusercontent.com/98621617/214944075-8e781700-7b54-4537-84c7-0ec6c2deac46.png)

Tubnet: 
![image](https://user-images.githubusercontent.com/98621617/214944209-f6bcec01-c1ce-4320-b6c0-98f37c5216bf.png)

**Comment by RaphiMC** [comment]
So the issue is resolved now

**Comment by stantios** [comment]
Wait, what does fast buffer uploads do?

**Comment by RaphiMC** [comment]
It speeds up data transfer between CPU and GPU. The artifacts are probably caused by your ancient GPU not liking the approach I take to speed that up

**Comment by stantios** [comment]
Yeah most likely, anyway thanks for helping me out. Appreciate it

**Comment by isXander** [comment]
Can you disable this feature automatically on old hardware?

**Comment by RaphiMC** [comment]
If you can tell me how I am supposed to detect old hardware. Checking the OpenGL version won't get me very far

**Comment by kees-** [comment]
+1 that this repros, and is solved by disabling `fast_buffer_upload`, with an AMD Radeon R9 M370X / MacOS 12.6.5 / 2015 MBP. Playing on 1.19.4. Thanks for identifying the fix here

**Comment by Madis0** [comment]
> If you can tell me how I am supposed to detect old hardware. Checking the OpenGL version won't get me very far

Isn't this just a macOS issue? Or any Mac without a Apple Mx chip.

**Comment by RaphiMC** [comment]
Not sure. I think there a macOS players which use the mod without problems

**Comment by akemin-dayo** [comment]
I can confirm that this is not a macOS-specific issue.

I'm beginning to wonder if this is an issue with AMD GPUs that are GCN 1.0 or older, or something like that. (※ The R9 M370X is one such GPU.)

**Comment by RaphiMC** [comment]
I recoded the fast buffer upload optimization using a more "modern" OpenGL API, so it might now work properly in this case. @Imzxhir Could you please retest (Make sure to delete the IF config): https://upload.raphimc.net/file/JPMTZ7m7w7vc2axZ/wWUsFXDcn27FxRRw/ImmediatelyFast-1.1.16-SNAPSHOT%2B1.20.1.jar
