### ISSUE TITLE
Warns about missing Armor Chroma

### ISSUE THREAD

**Issue by teleheel** [RaphiMC/ImmediatelyFast#39]
Upon start up, the following warning is printed to the log:
`[17:24:52] [main/WARN]: Error loading class: nukeduck/armorchroma/GuiArmor (java.lang.ClassNotFoundException: nukeduck/armorchroma/GuiArmor)`

Mods:
- Fabric Loader 0.14.14 for Minecraft 1.19.2
- ImmediatelyFast-1.1.8+1.19.jar
- sodium-fabric-mc1.19.2-0.4.4+build.18.jar

I would guess this is resolved by installing the Armor Chroma mod, but when not intending to use the mod the warning clutters the log somewhat.

Very minor "issue", fully understand if you won't prioritize fixing it 😄

**Comment by RaphiMC** [comment]
This is not an error. This is an intentional feature of mixins to make optional injectors. You can safely ignore this "warning". There are many mods using this feature and thus cause some warnings at startup. Those are all non critical and can be ignored
