### ISSUE TITLE
Titles are not visible behind chat box when using ImmediatelyFast and Title Fixer

### ISSUE THREAD

**Issue by JustLetterV** [RaphiMC/ImmediatelyFast#40]
I was able to reproduce this with these steps:
1. Installed clean fabric instance with mods ImmediatelyFast, [Title Fixer](https://modrinth.com/mod/title-fixer) and [Cloth Config API](https://modrinth.com/mod/cloth-config) (required by Title Fixer).
2. Created a new world and spammed the chat until it was full of messages.
3. Used command: ```/title @a title "Title text is not showing up behind chat box."```

Result:
![image](https://user-images.githubusercontent.com/75657829/219501911-fc1bfbd4-e15b-4815-b076-3aa470821fa8.png)

Without ImmediatelyFast:
![image](https://user-images.githubusercontent.com/75657829/219502580-9c7e0aaf-9b7e-453b-8504-307e4b207a13.png)

### Fabric/Mod versions:
Minecraft 1.19.3
Fabric loader 0.14.14
ImmediatelyFast 1.1.8
Title Fixer 1.0+1.19.3
Cloth Config 9.0.94

**Comment by RaphiMC** [comment]
Will be fixed in ImmediatelyFast 1.1.9
