### ISSUE TITLE
Crash with Iris and ImmediatelyFast

### ISSUE THREAD

**Issue by isuewo** [RaphiMC/ImmediatelyFast#41]
https://mclo.gs/0IBicIg

How to reproduce:
1. Launch minecraft with Iris, Sodium and ImmediatelyFast (all latest versions on 1.19.3)
2. Try to change a shaderpack setting before joining a world

**Comment by RaphiMC** [comment]
Already known and Iris should have fixed this on their side in the latest development builds

**Comment by isuewo** [comment]
Ah, okay. I asked in the Iris discord and they told me it was a problem on your side

**Comment by RaphiMC** [comment]
Did you ask today? If so please send me a link to the message so I can take a look

**Comment by isuewo** [comment]
https://discord.com/channels/774352792659820594/849360601267830825/1076145834846072952

**Comment by RaphiMC** [comment]
I talked with IMS today and it should be fixed on their side now. So you have to wait until a new build releases

**Comment by isuewo** [comment]
Alright, thanks for the info!

**Comment by RaphiMC** [comment]
This has been fixed with ImmediatelyFast 1.1.9. The fix was a side effect of improving the performance in setups where both Iris and ImmediatelyFast are installed.
