### ISSUE TITLE
Update to support new sodium 0.4.9

### ISSUE THREAD

**Issue by EGOIST1372** [RaphiMC/ImmediatelyFast#42]
as stated in the new version of sodium, immediatelyfast need an update
https://www.curseforge.com/minecraft/mc-mods/sodium/files
NOTE: This version makes internal changes that will likely break mods that try to hook into Sodium (such as Iris, Indium, ImmediatelyFast, etc.) You will need to wait for an updated version of these mods.
thanks in advance <3

**Comment by RaphiMC** [comment]
ImmediatelyFast is already compatible with Sodium 0.4.9

**Comment by EGOIST1372** [comment]
cause I thought since sodium 0.4.9 came after your latest version it's not fully adopted new implementation of sodium
sorry to take your time
thanks again
