### ISSUE TITLE
Issue with Status Effect Bars

### ISSUE THREAD

**Issue by RaptaG** [RaphiMC/ImmediatelyFast#43]
The bars on the HUD don't show up
The mod: https://modrinth.com/mod/status-effect-bars

**Comment by RaphiMC** [comment]
Can you try if this worked on IF 1.1.8

**Comment by RaptaG** [comment]
I think it did not

**Comment by RaptaG** [comment]
But yes I can try

**Comment by RaphiMC** [comment]
Any update? Can you retest with ImmediatelyFast 1.1.10

**Comment by RaptaG** [comment]
Sorry I forgot about this one, will test in the weekend

**Comment by RaptaG** [comment]
It doesn't work on both 1.19.4 IF 1.1.11 & 1.19.3 IF 1.1.7 @RaphiMC

**Comment by RaphiMC** [comment]
Fixed in ImmediatelyFast 1.1.12

**Comment by RaptaG** [comment]
Yay!
