### ISSUE TITLE
Incompatibility with VulkanMod

### ISSUE THREAD

**Issue by Paneled** [RaphiMC/ImmediatelyFast#45]
Hello, just suggesting this incompatibility be added to the list. Not expecting a fix, the game crashes after the Mojang studios logo pops up.

**Comment by RaphiMC** [comment]
Will add it to the list

**Comment by andreasdc** [comment]
Any chance for compability?

**Comment by RaphiMC** [comment]
No

**Comment by andreasdc** [comment]
what's the reason?

**Comment by RaphiMC** [comment]
I am not learning vulkan just to support some mod which doesn't even improve minecraft rendering all that much

**Comment by andreasdc** [comment]
vulkanmod is better than sodium

**Comment by RaphiMC** [comment]
It was a lot worse for me than sodium and its not compatible with 90% of rendering mods. No this is my final decision.

**Comment by andreasdc** [comment]
it was, but you are rude, but your mod gives nice boost as i see

**Comment by RaphiMC** [comment]
How am I rude? I said no and you can't accept that answer and spam the issue now. I can't possibly support every mod in the world just because its better for someone. My mod is open source, you are welcome to add support for VulkanMod yourself.

**Comment by andreasdc** [comment]
do you optimize armor rendering?

**Comment by RaphiMC** [comment]
Please stop commenting off-topic questions. You can join my discord if you want to know more about ImmediatelyFast. But yes armor rendering is optimized
