### ISSUE TITLE
[1.19.4] Armor trims not rendering with certain combinations of equiped slots.

### ISSUE THREAD

**Issue by kikugie** [RaphiMC/ImmediatelyFast#47]
![2023-03-16_08 38 55](https://user-images.githubusercontent.com/50152507/225548113-f041c6db-64e7-44a2-8b84-d7cfc7fb3b42.png)
![2023-03-16_08 38 59](https://user-images.githubusercontent.com/50152507/225548126-e458db8e-5a15-4aa8-8c08-1335aae8619f.png)
![2023-03-16_08 41 02](https://user-images.githubusercontent.com/50152507/225548134-b43bdd90-a122-4a22-81e9-500f0c383a37.png)

## Observed behavior: 
- Using trimmed helmet and boots works correctly;
- Adding trimmed leggings removes trims on helmet and boots;
- Adding trimmed chestplate returns helmet and boot trims, but removes trim on leggings;
- For any step adding not trimmed equipment doesn't affect the result;
- Starting point includes both helmet and boots, but same issue occurs if only one is equipped;
- Screenshots demonstrate issue on armor stands, but it also works on players and other entities;

## Testing setup:
Tested on 1.19.4 on fabric loader 0.14.17 and only mod being loaded is ImmeaditelyFast 1.1.10

**Comment by RaphiMC** [comment]
Should be fixed in ImmediatelyFast 1.1.11
