### ISSUE TITLE
Pie chart text not rendering

### ISSUE THREAD

**Issue by Zhamty** [RaphiMC/ImmediatelyFast#48]
OS: Linux Mint 21.1
MC version: 1.19.4
Mod version: 1.1.10
Sodium version: 0.4.10

**The text on shift+f3 pie chart is not being rendered as shown in the screenshot:** 
![2023-03-17_22 51 22](https://user-images.githubusercontent.com/33164013/226066256-1ec6506c-c054-4312-bea3-d44d8ad63e53.png)

**Comment by RaphiMC** [comment]
Should be fixed in ImmediatelyFast 1.1.11
