### ISSUE TITLE
Crashes in a modpack with many mods

### ISSUE THREAD

**Issue by LittleChest** [RaphiMC/ImmediatelyFast#51]
My Minecraft Version: 1.19.4 with Quilt Mod Loader 0.19
Crash Log:`https://mclo.gs/mL2p48D`
Full Log:`https://mclo.gs/36CRSb4`
By the way, I'm the author of this modpack, and I don't know which mod it conflicts with. 😥

**Comment by RaphiMC** [comment]
Are you sure the crash doesn't occurr without ImmediatelyFast?

**Comment by LittleChest** [comment]
> Are you sure the crash doesn't occurr without ImmediatelyFast?

Sorry, the problem doesn't happen anymore when I switched to Fabric
