### ISSUE TITLE
Optimize FPS limit

### ISSUE THREAD

**Issue by andreasdc** [RaphiMC/ImmediatelyFast#52]
Is it possible to optimize FPS limit to better hold it's value? For example without the limit I have 300 fps, but with 250 FPS limit I have around 220.

**Comment by RaphiMC** [comment]
Out of scope for ImmediatelyFast

**Comment by andreasdc** [comment]
Where to suggest it? What's in scope for IF?

**Comment by RaphiMC** [comment]
Idk where to suggest it. In scope are optimizations to things rendered in immediate mode (Make them render faster)

**Comment by andreasdc** [comment]
Idk how does the limit work, but it would be nice addition I think.
