### ISSUE TITLE
Some optimizations

### ISSUE THREAD

**Issue by andreasdc** [RaphiMC/ImmediatelyFast#54]
I ran spark profiler, maybe some parts could be optimized?
![image](https://user-images.githubusercontent.com/82218780/230734559-e68b1e9e-8f0c-481d-a283-66c36cebef6b.png)

![image](https://user-images.githubusercontent.com/82218780/230734473-d7506928-77ef-415f-83cd-1415b14cecd2.png)
![image](https://user-images.githubusercontent.com/82218780/230734491-f321796c-f920-4b5d-a6e2-bf4ce7020480.png)
![image](https://user-images.githubusercontent.com/82218780/230734504-2305c091-46b5-4a2f-8fae-915292969b60.png)
![image](https://user-images.githubusercontent.com/82218780/230734523-797cd4de-da64-4503-a29f-216fde53a7fa.png)

**Comment by RaphiMC** [comment]
Please stop spamming pointless issues. This issue is entirely useless as you just took some random screenshots of a spark profile result. Some aren't even related to ImmediatelyFast. This is the final warning before I block you from creating new issues

**Comment by andreasdc** [comment]
I totally don't understand. These screenshots are from render thread, you wanted to opitimize rendering.

**Comment by RaphiMC** [comment]
Yes, I know why the rendering is slow, I don't need random screenshots showing me stuff sodium is doing. Most of the things can't even be optimized properly without breaking nearly all mods which touch rendering. Your last issues were all pointless and out of scope for ImmediatelyFast

**Comment by andreasdc** [comment]
I suggested optimizations, I don't understand the reason you attack me. You wanted something in scope, I gave it to you. Write somewhere that you don't want users to suggest you things or something like that.

**Comment by RaphiMC** [comment]
I don't want to be rude but your suggestion is very useless. I can use spark myself and see the problems of minecraft. The things you showed all can't be really optimized much further without breaking the whole game. And given your last issues and comments it seems like you are trolling/spamming the issues

**Comment by andreasdc** [comment]
You are rude from the beginning, I don't want to talk like that, if you don't want spark reports, write it somewhere.

**Comment by RaphiMC** [comment]
In the first issue I told you that VulkanMod isn't getting support (And you commented on a closed issue which already told you that this mod isn't getting any support). And you commented again even tho I twice said no I am not going through the effort to support that mod. Then you created totally unrelated issues to which I said you should stop creating spam issues. Now you create a totally pointless issue simply containing spark screenshots without any information to them. This feels to me like you are trolling. I am pretty sure if you open that same issue on sodiums issue tracker it also would be closed immediately because it doesn't contain anything useful. If you want to make a feature request it should be something concrete which is in the scope of ImmediatelyFast

**Comment by andreasdc** [comment]
What do you see wrong here? I ran the profiler and I asked if this can be optimized.

**Comment by andreasdc** [comment]
Got some more profiler results, can this be optimized? Screen had a lot of entities and text, I think that's what taking the most resources.
![image](https://user-images.githubusercontent.com/82218780/231262125-4773177b-0cd1-49a2-a398-2d80e3fd097f.png)
![image](https://user-images.githubusercontent.com/82218780/231262257-85a31d83-866f-44a7-bd9c-2bf9812cc7cf.png)
![image](https://user-images.githubusercontent.com/82218780/231262384-86dfc0ce-9857-44de-a8bd-9f556797137f.png)
![image](https://user-images.githubusercontent.com/82218780/231262513-97a51ce7-8b07-4370-a792-2a47dcfa3edd.png)
![image](https://user-images.githubusercontent.com/82218780/231262602-34819b55-d15d-410e-a43c-de4e9846c49d.png)
![image](https://user-images.githubusercontent.com/82218780/231262661-21f4dc46-128e-438e-8668-c7b0dc34e29c.png)
