### ISSUE TITLE
Shifting in second + third person causes holograms to become less visible

### ISSUE THREAD

**Issue by R00tB33rMan** [RaphiMC/ImmediatelyFast#55]
![2023-04-08_14 09 21](https://user-images.githubusercontent.com/36140389/230736574-27fc26f7-6d5c-4576-bad5-36bca4661bff.png)

In vanilla, I can confirm that this is not the case.

**Comment by RaphiMC** [comment]
Can you please give more details. What MC Version? What ImmediatelyFast version? What other mods are installed?

**Comment by R00tB33rMan** [comment]
> Can you please give more details. What MC Version? What ImmediatelyFast version? What other mods are installed?

No worries. I'll provide all details. This issue occurs on any version of ImmediatelyFast. I've attempted with even base Quilt/Fabric on 1.18.2, 1.19.2, 1.19.3, and 1.19.4. When removing the mod, this issue no longer persists. It of course also occurs alongside Exordium as well.

This is reproducible by looking at a hologram/nametag and holding "Shift" in second and third person.

**Comment by R00tB33rMan** [comment]
Issue appears to be due to "Who Am I?" Apologies for the confusion!
