### ISSUE TITLE
Horse patterns show through horse armour

### ISSUE THREAD

**Issue by andrwcrr** [RaphiMC/ImmediatelyFast#59]
![2023-05-12_23 59 15](https://github.com/RaphiMC/ImmediatelyFast/assets/128940455/3cc1e535-e7e1-4425-94b6-8e0c32a4ba96)

**Comment by RaphiMC** [comment]
Please provide more details like: IF version, MC version, GPU, other mods

**Comment by andrwcrr** [comment]
![Untitled](https://github.com/RaphiMC/ImmediatelyFast/assets/128940455/edc4343c-357e-4ff1-a42e-b43962f4f472)
ImmediatelyFast version 1.1.12
Minecraft 1.19.4
RTX 2060
I was able to reproduce this with no other mods present (as seen above)

**Comment by andrwcrr** [comment]
I've discovered that Iris has a similar (if not the exact same) issue so maybe these can help:
https://github.com/IrisShaders/Iris/issues/1365
https://github.com/IrisShaders/Iris/issues/1769

**Comment by mrjasonn** [comment]
Still occurs on 1.20.4 with ImmediatelyFast 1.2.10. Am using Sodium, Iris and Sodium Extra.

**Comment by mrjasonn** [comment]
@RaphiMC this issue also is a vanilla parity issue, don't know if you would like to add a tag for that

**Comment by RaphiMC** [comment]
Vanilla parity issue won't get their own tag, they simply don't get the "external-mod" tag since all non external-mod (and not otherwise labeled) issues are vanilla parity issues

**Comment by mrjasonn** [comment]
@RaphiMC any ETA when this would be fixed? If there is, it would be much appreciated.

**Comment by RaphiMC** [comment]
There isn't an ETA since I am pretty busy with real life and don't have much time to work on fixing ImmediatelyFast issues

**Comment by mrjasonn** [comment]
> I've discovered that Iris has a similar (if not the exact same) issue so maybe these can help: [IrisShaders/Iris#1365](https://github.com/IrisShaders/Iris/issues/1365) [IrisShaders/Iris#1769](https://github.com/IrisShaders/Iris/issues/1769)

Maybe @RaphiMC should collaborate with the Iris team, most notably their main developer @IMS212 because they might know quite a lot might be useful in fixing this in both mods at once as it still actually happens with Iris on it's own on 1.20.4 Iris 1.6.17

**Comment by mrjasonn** [comment]
Update: There is a PR in Iris (IrisShaders/Iris#2289) aiming to fix this issue, this info may be useful for fixing this mod.

**Comment by HiiJax** [comment]
I still plan on finding a better way to fix this, but for now I've made [this mod](https://modrinth.com/mod/bad-horse-fix) that fixes the issue. It does require installing Iris though.

**Comment by RaphiMC** [comment]
Thanks for sharing the mod. This will help implementing at least a workaround since a proper fix would be more complicated. Your mod only injects into Iris, but it should be pretty easy to implement something similar in IF.
