### ISSUE TITLE
I think I found an incompatibility with iris and I don't know if that causes crashes 1.19.2

### ISSUE THREAD

**Issue by papillo12** [RaphiMC/ImmediatelyFast#6]
![image](https://user-images.githubusercontent.com/80440525/202930785-6fabbb6b-4eed-4df1-97f3-077d3bab6077.png)

[crash-2022-11-20_16.47.19-client.txt](https://github.com/RaphiMC/ImmediatelyFast/files/10050887/crash-2022-11-20_16.47.19-client.txt)

[latest.log](https://github.com/RaphiMC/ImmediatelyFast/files/10050889/latest.log)

**Comment by RaphiMC** [comment]
The "error" in the screenshot is just a warning, that ImmediatelyFasz won't improve your FPS much further if Iris is installed, but is should not cause any problems having both. The crash is unrelated to ImmediatelyFast
