### ISSUE TITLE
Error loading class: nukeduck/armorchroma/GuiArmor

### ISSUE THREAD

**Issue by TheBossMagnus** [RaphiMC/ImmediatelyFast#61]
Using ImmediatelyFast causes this worn in log [21:21:26] [main/WARN]: Error loading class: nukeduck/armorchroma/GuiArmor (java.lang.ClassNotFoundException: nukeduck/armorchroma/GuiArmor).
Minecraft runs fine.

Logs: https://mclo.gs/Z07MIhB Happens with quilt and fabric, also with just FAPI/QFPAI

**Comment by RaphiMC** [comment]
See https://github.com/RaphiMC/ImmediatelyFast/issues/39
