### ISSUE TITLE
[Bug] Incorrect rendering of strength bars in hotbar on version 1.1.13-1.19.4

### ISSUE THREAD

**Issue by ghost** [RaphiMC/ImmediatelyFast#64]
<p>When I install Immediately Fast 1.1.13, tool strength bars are drawn incorrectly in hotbar, if I remove Immediately Fast 1.1.13 or use version 1.1.12, everything is drawn normally. Rendering strength with the GUI open works fine in all cases.</p>
<p>How it looks like in a hobar:</p>
<img src="https://github.com/RaphiMC/ImmediatelyFast/assets/126811494/8f9ab895-6f24-4b22-82e8-2394a14cd455">
<p>How it looks like in a GUI:</p>
<img src="https://github.com/RaphiMC/ImmediatelyFast/assets/126811494/64a4f534-aa9e-475c-9f2f-62ca266574b4">
<p><a href="https://gist.github.com/AlexChevios/68dfffb08d255480b57642ede77953cf">latest.log</a></p>

**Comment by ghost** [comment]
<p>As a workaround, I found turning off <b>hud batching</b></p>

**Comment by RaphiMC** [comment]
Thanks for discovering the issue before I would have released that version. Here is the updated one (You can enable hud batching again): https://upload.raphimc.net/file/j83tCtgnVHxj2xlF/1cGQvkUzu6I6RSUZ/ImmediatelyFast-1.1.13%2B1.19.4.jar

**Comment by ghost** [comment]
Help in detecting problems from the future :D

**Comment by RaphiMC** [comment]
I made more changes to the underlying architecture. You can update to that version and report any visual issues: https://upload.raphimc.net/file/V1jz8hAuYUc9pwi8/WhHrXKy7I6AX6RH7/ImmediatelyFast-1.1.13%2B1.19.4.jar

**Comment by ghost** [comment]
Thanks, I'll test it tomorrow.
