### ISSUE TITLE
The graphics in the F3 menu are poorly rendered

### ISSUE THREAD

**Issue by Lolothepro** [RaphiMC/ImmediatelyFast#65]
Vanilla:
![2023-06-08_21 08 17](https://github.com/RaphiMC/ImmediatelyFast/assets/68275908/11d78d91-03a1-4477-94c9-51c359f191ae)

![image](https://github.com/RaphiMC/ImmediatelyFast/assets/68275908/4f8d5a50-0ca0-4e79-b705-2623e53bca55)

[ImmediatelyFast](https://github.com/RaphiMC/ImmediatelyFast) + Sodium:

![2023-06-08_21 09 22](https://github.com/RaphiMC/ImmediatelyFast/assets/68275908/19997dd8-5b5e-4ae1-b2fa-bb3e1875117d)

![image](https://github.com/RaphiMC/ImmediatelyFast/assets/68275908/fa5330ee-f3ba-4574-a941-cd9234c1300a)

![image](https://github.com/RaphiMC/ImmediatelyFast/assets/68275908/60931e26-7dd9-4bae-9a59-b26021b1831b)

**Comment by RaphiMC** [comment]
The bug you are reporting is for the missing FPS numbers (text overlay over the graph), right?

**Comment by Lolothepro** [comment]
> The bug you are reporting is for the missing FPS numbers (text overlay over the graph), right?

Yes

**Comment by RaphiMC** [comment]
Fixed in the next release of IF. The issue with items being over the graph is still here, but thats not too large of an issues and I don't want to change too much code just for that
