### ISSUE TITLE
Rendered item bar flashing with exordium 

### ISSUE THREAD

**Issue by vocaloidkiss** [RaphiMC/ImmediatelyFast#66]
Rendered item bar flashing with exordium 
"hud_batching": true,

**Comment by RaphiMC** [comment]
I talked with tr7zw and he came to the conclusion that Exordium development is currently paused. This issue has to be resolved on their end. Linked issue: https://github.com/tr7zw/Exordium/issues/66

**Comment by vocaloidkiss** [comment]
ok。I attempt resolve it myself
