### ISSUE TITLE
Crash when Memory Leak Fix mod is present

### ISSUE THREAD

**Issue by thegatesdev** [RaphiMC/ImmediatelyFast#67]
ImmediatelyFast crashes when paired with MemoryLeakFix. This crash only happens with these two mods together, removing any of the two will make the game run fine.

ImmediatelyFast version 1.1.13
Minecraft version 1.20
MemoryLeakFix version 1.1.0

Crash log: https://paste.ee/p/HrtZJ

Other mods present: Fabric API 0.83.0

Thank you.

**Comment by RaphiMC** [comment]
Try this build: https://upload.raphimc.net/file/YXhJzXvOE0N1fpCG/B723m7apothjaS82/ImmediatelyFast-1.1.14-SNAPSHOT.jar

**Comment by RaphiMC** [comment]
Will be fixed when ImmediatelyFast 1.1.14 releases

**Comment by DeenOConnor** [comment]
Version 1.2.1 reports incompatibility with MemoryLeakFix, is this correct?

**Comment by RaphiMC** [comment]
Yes, MemoryLeakFix is breaking other mods again. You will have to wait for the next MemoryLeakFix release. I can't fix the issue
