### ISSUE TITLE
Exordium incompatibility 1.1.13 regression

### ISSUE THREAD

**Issue by purple512** [RaphiMC/ImmediatelyFast#68]
Hello!

There seems to be an incompatibility with the latest release of ImmediatelyFast (1.1.13) and Exordium (1.1.1). The hotbar does not render:

<img src="https://github.com/RaphiMC/ImmediatelyFast/assets/79816784/7fda58b5-2f59-4aec-97b4-c236df26b56b" width=50% height=50%>

This the previous ImmediatelyFast release (1.1.12) works just fine w/Exordium.

quick specs: Minecraft 1.19.4, Sodium 0.4.10, Iris 1.6.4, and below is a game log showing all info and mod versions: 

[logfile on mclo.gs](https://mclo.gs/4AEIQsr)
[logfile as an attachment](https://github.com/RaphiMC/ImmediatelyFast/files/11714168/latest.log)

**Comment by RaphiMC** [comment]
Duplicate issue: #66 . See that issue for a reason why its broken
