### ISSUE TITLE
Incorrect display of the hearts of riding mobs

### ISSUE THREAD

**Issue by DonaldDab** [RaphiMC/ImmediatelyFast#69]
Minecraft 1.19.4 + fabric API 0.83.0
mods: ImmediatelyFast-1.1.13

![image](https://github.com/RaphiMC/ImmediatelyFast/assets/124441220/8a188a8d-1c72-4619-8701-7c49c512ec6c)

**Comment by RaphiMC** [comment]
Will be fixed when ImmediatelyFast 1.1.14 releases
