### ISSUE TITLE
Horse Markings Flickering While Using ImmediatelyFast

### ISSUE THREAD

**Issue by jamalmarri** [RaphiMC/ImmediatelyFast#7]
### Versions
* Minecraft: 1.19.2
* Quilt Loader: 0.17.6
* ImmediatelyFast: 1.0.4

### Description
When using this mod, I have noticed that certain layered textures, such as the different markings on horses, flicker in and out of existence while moving around the origin of the texture. This was tested with no other mods and can be easily replicated by simply spawning some horses with a variety of markings (a simple spawn egg works) and walking/flying around them while looking at them.

**Comment by RaphiMC** [comment]
I could reproduce the issue and I hope to fix it before 1.19.3 releases

**Comment by RaphiMC** [comment]
Should be fixed in ImmediatelyFast 1.0.5
