### ISSUE TITLE
Figura armour hiding doesn't hide trims

### ISSUE THREAD

**Issue by ibll** [RaphiMC/ImmediatelyFast#70]
In these images, I am wearing netherite armour with an emerald dune trim. My Figura avatar is set to hide my armour.

Figura:
![Without Immediately Fast](https://github.com/RaphiMC/ImmediatelyFast/assets/61601241/2d73c326-f2ec-497d-9e09-b01c68729be4)

Figura + Immediately Fast:
![With Immediately Fast](https://github.com/RaphiMC/ImmediatelyFast/assets/61601241/ab1a4819-05da-43b3-9dcc-018d3b6bd0d0)

The armour is hidden as expected, but the armour trim is still visible!

I have a barebones .minecraft folder with everything set up to demonstrate:
[dot_minecraft.zip](https://github.com/RaphiMC/ImmediatelyFast/files/11741158/dot_minecraft.zip)

Load into the singleplayer world, go to the pause menu and open the blue triangle menu, and ensure the "Bug Showcase" avatar in the left panel is selected. There's trimmed armour in the chest. I can provide full instructions if you don't want to open the zip.

I am also on macOS with an M1 chip using Temurin 17 aarch64 java if it matters. Thanks!

**Comment by RaphiMC** [comment]
Can you check if this version has the bug fixed: https://upload.raphimc.net/file/yYpwWluvYiVsLoWE/pMKHvD6ss0WoFWOh/ImmediatelyFast-1.1.16-SNAPSHOT%2B1.20.1.jar

**Comment by ibll** [comment]
Still doesn't hide trims correctly

**Comment by RaphiMC** [comment]
When I use your figura config and only install the figura mod without ImmediatelyFast the trims aren't hidden. How can I replicate the problem?

**Comment by ibll** [comment]
Wow really? I’m playing on a server with many others using Figura and consistently this issue isn’t present without ImmediatelyFast and is present with it. This is around 12 people and about half of them had ImmediatelyFast installed, and they also had the issue exclusively while it was enabled.

The .minecraft folder includes a version of ImmediatelyFast already, but I imagine you already know this. Maybe just try again? I’m sorry I can’t help more.

**Comment by Fran12334** [comment]
> When I use your figura config and only install the figura mod without ImmediatelyFast the trims aren't hidden. How can I replicate the problem?

Ive also had this issue. By the way you said it i dont think you used a figura avatar that would hide the armor, which is necessary to replicate the problem. i created a simple avatar:
[Hide_armor.zip](https://github.com/RaphiMC/ImmediatelyFast/files/12022804/Hide_armor.zip)
 that you have to drop into .minecraft/figura/avatars/ and then select ingame that shows the issue if you try to wear armor with trims.

**Comment by ibll** [comment]
As I recall there's one included in my instance and instructions on how to select it. I suppose I should've been more clear in my instructions, sorry!

**Comment by Slooshie1** [comment]
I'm also still having this issue on 1.1.24

**Comment by showierdata9978** [comment]
This is happening to me on a non figura user (i do have figura installed)
