### ISSUE TITLE
ImmediatelyFast might have crashed my JVM

### ISSUE THREAD

**Issue by minhperry** [RaphiMC/ImmediatelyFast#71]
[Full JVM crash log](https://mclo.gs/ChtSPnq)

[System Info](https://gist.github.com/minhperry/b7e783cbc7ecf1cd294d3063093caa5d)

This was caused by holding throw to throw out items one by one, first the game freeze, then the whole screen went black and explorer.exe basically "restarted". This also caused my opening Discord to crash as well (if this matters)

Used mods + Xaero Mini and World Map as well as YACL:
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/46137516/8bd3dfe4-be7d-4d73-bbc1-321021b4d9df)

**Comment by RaphiMC** [comment]
Did this happen more than once or do you have a way to get it to crash everytime? Sounds a bit weird to be caused by ImmediatelyFast

**Comment by minhperry** [comment]
I did try to recreate that but none of any attemps can recreate the crash. Probably this is because of my hardware and you can close this issue

**Comment by RaphiMC** [comment]
Yeah probably if it only happened once
