### ISSUE TITLE
Makes hotbar invisible with latest 1.19.4 versions

### ISSUE THREAD

**Issue by HaXrDEV** [RaphiMC/ImmediatelyFast#72]
Title explains it pretty well. The hotbar vanishes when latest version is installed. Need to go all the way back to version 1.1.12 to fix the issue.

Problematic versions: "1.1.15+1.19.4" and "1.1.13+1.19.4"

Modlist: https://wiki.crismpack.net/modpacks/breakneck-optimized/modlist/1.19.4

![image](https://github.com/RaphiMC/ImmediatelyFast/assets/20630404/b1a3b600-65dc-4d03-bfbf-34374a0e967b)

**Comment by RaphiMC** [comment]
Modpack probably includes outdated Exordium. This issue was already fixed by Exordium: https://github.com/tr7zw/Exordium/issues/66

**Comment by HaXrDEV** [comment]
This is not the case. I am using the latest version of Exordium (exordium-fabric-1.1.1-mc1.19.4)

**Comment by RaphiMC** [comment]
1.1.1 is not the latest

**Comment by HaXrDEV** [comment]
Oh darn, a newer version is available on Modrinth. Love that.
Sorry for the troubles.
