### ISSUE TITLE
Core Shaders broken on MCC Island

### ISSUE THREAD

**Issue by Quesodude** [RaphiMC/ImmediatelyFast#74]
Loading up IF 1.1.15 of Minecraft 1.20.1 and logging onto MCC Island shows these results when logging on and looking at the HUD (Image 1)
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/56931297/cc2ec96f-afa2-4fd7-aeff-3a5969439cca)
Results should look like this (Image 2)
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/56931297/2691b3b4-3c6c-4375-8adf-4f2f7edccc64)
Steps to reproduce are to log onto MCC Island, join any game where a HUD is included. This also affects other UI elements like text in the Main Hub etc.

An addition to this: This seems to not occur on Version 1.19.4 with IF 1.1.15, reset config to confirm

**Comment by RaphiMC** [comment]
Can you check if this build fixes the issue: https://upload.raphimc.net/file/zX9rmo122VwZxRiz/z4SkCl4Fq9xFIZu6/ImmediatelyFast-1.1.16-SNAPSHOT%2B1.20.1.jar

**Comment by RaphiMC** [comment]
Closed due to inactivity
