### ISSUE TITLE
GUI bugged out.

### ISSUE THREAD

**Issue by PerhapsAverage** [RaphiMC/ImmediatelyFast#77]
For context: I use VulkanRenderer instead of sodium. It gives me better FPS
The entire GUI is bugged out and idk why QwQ. hotbar and everything else; even skins.
from what i am aware of the inventory isn't bugged out. and searching for blocks is fine. Most mobs are not bugged out.
This only started happening after i realized ImmediatelyFast is compatible with Vulkan.
I switched to sodium and everything looked fine.

**Comment by PerhapsAverage** [comment]
If anyone knows a fix, please share!!

**Comment by RaphiMC** [comment]
I never tested VulkanMod compatibility, the devs of VulkaMod said it supposed to work with the latest version. You should create an issue on their github repo
