### ISSUE TITLE
Glitching and freezing on advancement window

### ISSUE THREAD

**Issue by Madis0** [RaphiMC/ImmediatelyFast#79]
Sometimes it just glitches, sometimes the glitch freeze the entire game. The expanded advancement screen is provided by AdvancementInfo, but that mod itself does not cause the issue (glitches are just easier to see on the bigger area)

IF 1.1.15 on 1.20.1, Fabulously Optimized 5.1.0-beta.5

https://github.com/RaphiMC/ImmediatelyFast/assets/8611110/b0120a64-194f-48b8-9cdd-745702b323ad

[latest.log](https://github.com/RaphiMC/ImmediatelyFast/files/11898331/latest.log) though that doesn't say much

**Comment by RaphiMC** [comment]
Fixed in ImmediatelyFast 1.1.16
