### ISSUE TITLE
Incompatibility with Yttr

### ISSUE THREAD

**Issue by Firestrike1** [RaphiMC/ImmediatelyFast#8]
Opening Yttr's creative tab and clicking on Mechanisms category (Sometimes can take more than one attempt) causes most entities to turn red as if they were hit and had immunity frames.

**Comment by Firestrike1** [comment]
Update: This mod does not causes the issue, but makes it significantly more noticeable, hence why I wrongly assumed that removing your mod fixes it completely

**Comment by RaphiMC** [comment]
Thank you for doing further testing. I will definitely look into that issue in the next couple of days. Now that you know that my mod does not cause this, but Yttr has the issue, you could open an issue on their issue tracker as well so it gets properly fixed

**Comment by Firestrike1** [comment]
https://git.sleeping.town/unascribed/Yttr/issues/37
It's actually been there for quite some time

**Comment by RaphiMC** [comment]
I fixed render layer ordering issues. This probably fixes the magnification effect of ImmediatelyFast. If you test it and it didn't change anything please comment here so I can reopen the issue
