### ISSUE TITLE
ImmediatelyFast does not work with the latest version of Iris

### ISSUE THREAD

**Issue by teddyxlandlee** [RaphiMC/ImmediatelyFast#80]
Here's the crash log: https://paste.ee/p/9af9y

I'm running the [Fabulously Optimized](https://modrinth.com/modpack/fabulously-optimized) modpack (MC: 1.20.1) and it crashes.

I have turned on `mixin.debug.export`, finding out that non of Iris are mixin-ed by other mods.

So that's ImmediatelyFast's problem

**Comment by RaphiMC** [comment]
I could not reproduce the crash using the exact mod versions of your crash report. Could you find out what java runtime distribution you are using by running `java -version` in a CMD window

**Comment by teddyxlandlee** [comment]
Java 17, IBM Semeru OpenJ9

**Comment by RaphiMC** [comment]
Fixed it: https://build.lenni0451.net/view/Mods/job/ImmediatelyFast/lastSuccessfulBuild/artifact/build/libs/ImmediatelyFast-1.1.16-SNAPSHOT+1.20.1.jar

**Comment by SShiRkiT** [comment]
same on 1.19.4
is there any SNAPSHOT version of the IF mod working on 1.19.4? i didnt find one

**Comment by RaphiMC** [comment]
Here is one: https://upload.raphimc.net/file/Qn0aLnMhkd9EQNNu/7otgUbSo1Q8qZ0XX/ImmediatelyFast-1.1.16-SNAPSHOT%2B1.19.4.jar

**Comment by SShiRkiT** [comment]
> Here is one: https://upload.raphimc.net/file/Qn0aLnMhkd9EQNNu/7otgUbSo1Q8qZ0XX/ImmediatelyFast-1.1.16-SNAPSHOT%2B1.19.4.jar

appreciate so much
