### ISSUE TITLE
Font Rendering does not behave like Vanilla in Item Lores

### ISSUE THREAD

**Issue by davidmayr** [RaphiMC/ImmediatelyFast#81]
I found out this mod breaks layered font rendering.
You see on modern minecraft servers that have fancy resourcepack stuff, we use a technique called negative spaces.
With negative spaces, we move text back into previous characters to make some fancy stuff. 

We also use new layer characters in order something has some render issues. 
You can find out more here: https://github.com/AmberWat/NegativeSpaceFont

Negative spaces do appear to work in the mod, **but not correctly in Item Lores**. They do apply (because there are multiple characters in the pink box that all are moved 1px back, since minecraft has a 1px padding between chars), but once characters overlap other characters, it breaks and just does not show the new characters above the other ones. I have, of course, applied a new layer character, but that does also not work with this mod. It works 100% without issues in vanilla minecraft. 

Interestingly, it works if the characters are in a font where the character does not have a provider (when the [] boxes appear showing a missing character). Then it is completely normal

I have attached two images that show a comparison between mod and without the mod
![grafik](https://github.com/RaphiMC/ImmediatelyFast/assets/54715954/007e4476-83f9-442c-989b-66bc00d0a493)
![grafik](https://github.com/RaphiMC/ImmediatelyFast/assets/54715954/f50246f6-8ab5-4d6e-95a8-79e3ed84de9c)

I have tested this with only the Immediately Fast mod loaded, no other mods active.

**Comment by RaphiMC** [comment]
Can you check if enabling debug_only_and_not_recommended_disable_universal_batching in the IF config file fixes the issue?

**Comment by RaphiMC** [comment]
Also can you give me detailed instructions on how to reproduce the issue

**Comment by davidmayr** [comment]
> Can you check if enabling debug_only_and_not_recommended_disable_universal_batching in the IF config file fixes the issue?

That does work, yes.

**Comment by davidmayr** [comment]
> Also can you give me detailed instructions on how to reproduce the issue

Download this texture pack: https://github.com/AmberWat/NegativeSpaceFont
Download this texture pack as well:  https://workupload.com/file/XFWGxW6DeEH

Give yourself this item: 
```/give @p acacia_boat{display:{Name:'[{"text":"Test","italic":false}]',Lore:['{"text": "A", "italic": false, "font":"test:test", "extra": [{"translate": "space.-8", "font": "minecraft:default"},{"translate":"newlayer", "font": "minecraft:default"},{"text": "H", "color": "white", "font": "minecraft:default"}]}','[{"text":"","italic":false}]','[{"text":"","italic":false}]','[{"text":"Hallo Welt","italic":false,"color":"white"}]']}} 1```

Note: I found out this bug seems to only occur when the character the game is rendering over(in this case A) is from a custom font

**Comment by RaphiMC** [comment]
I will look into it, I assume the problem is those tricks rely on the slow rendering of vanilla thats why it breaks with IF (Which draws all the characters at once instead of multiple draw calls)

**Comment by davidmayr** [comment]
Even if it is not fixable, I would be happy with a custom payload command that can disable this custom rendering for the current session(will be reenabled when you leave the server) or something since this breaks a quite important feature for me

**Comment by RaphiMC** [comment]
Should be fixed: https://upload.raphimc.net/file/zX9rmo122VwZxRiz/z4SkCl4Fq9xFIZu6/ImmediatelyFast-1.1.16-SNAPSHOT%2B1.20.1.jar
Please close the issue if all your test cases are fixed in this build.

**Comment by davidmayr** [comment]
Works, thank you!

**Comment by RaphiMC** [comment]
@davidmayr I had to change the existing fix due to performance issues. Could you retest if this version of ImmediatelyFast still handles all the test cases you throw at it correctly: https://upload.raphimc.net/file/4KsbKEXF66BJ8kOt/4gNd1YyPEJLPOlzD/ImmediatelyFast-Fabric-1.2.19-SNAPSHOT.zip

**Comment by davidmayr** [comment]
> @davidmayr I had to change the existing fix due to performance issues. Could you retest if this version of ImmediatelyFast still handles all the test cases you throw at it correctly: https://upload.raphimc.net/file/4KsbKEXF66BJ8kOt/4gNd1YyPEJLPOlzD/ImmediatelyFast-Fabric-1.2.19-SNAPSHOT.zip

I actually never got around to implementing what I initially had planned, when I created that issue, on my server. However, I still tried to test if it works on 1.21 (with sodium and modmenu installed) and I saw the expected results. Both clients(vanilla and modded) rendered the same result.

So I'd say your changes work. Don't quote me on that, tho, because I didn't do extensive testing like I did when I created that issue.
