### ISSUE TITLE
Hello, I am a staff member at DarkRPG and we are wondering if you have any insights in to this.

### ISSUE THREAD

**Issue by KonekoNyarla** [RaphiMC/ImmediatelyFast#82]
Not sure if this is even related to you but we are hoping that you may know something about this but we are getting a bug where after a while items that link together for example: chests, fences and walls don't link or the link is broken.

We are unable to replicate this bug as it happens randomly and we were hoping to see if you maybe had someone who has reported the same thing happening or something of this kind.

here is an image of what I am referring to: https://cdn.discordapp.com/attachments/1077294784877695017/1126606768835940403/image.png

**Comment by RaphiMC** [comment]
This bug is very very unlikely to be caused by ImmediatelyFast as it never interacts with/touches block rendering. Lithium or sodium might could cause it, but probably not. The most plausible thing is that its related to the server sending invalid/broken block states.
