### ISSUE TITLE
[1.20] Memory Leak in BlendFuncDepthFunc

### ISSUE THREAD

**Issue by embeddedt** [RaphiMC/ImmediatelyFast#84]
I have a lot of other client-side mods installed, but it seems that under certain conditions, the stack in this class is not being popped, causing a memory leak over time.

![image](https://github.com/RaphiMC/ImmediatelyFast/assets/42941056/a72f8fd9-df09-4dbe-91d6-9434551d57a0)

Let me know what information would be most helpful to diagnose this. I do have Sodium and Indium installed.

**Comment by RaphiMC** [comment]
Thanks for bringing this to my attention. I accidentally pushed onto the stack in the method that popped it
