### ISSUE TITLE
incompatible with Vulkan mod (again)

### ISSUE THREAD

**Issue by BoraiperXD** [RaphiMC/ImmediatelyFast#85]
It crashed after I opened my launcher for about 5 to 10 seconds to test, but there were no crash logs in the folder :/

Mod Lists-
fabric-api-0.84.0+1.19.4
ImmediatelyFast-1.1.16+1.19.4
VulkanMod_1.19.4-0.3.2

**Comment by RaphiMC** [comment]
Use an older version of IF thats still compatible and report it to the VulkanMod devs

**Comment by BoraiperXD** [comment]
> Use an older version of IF thats still compatible and report it to the VulkanMod devs
Wait, I mean, your latest version of mod is incompatible and not working well to tell you, but the previous version of 1.1.15 was fine and work with Vulkan for me

**Comment by RaphiMC** [comment]
I am myself not interested in maintaining VulkanMod compatibility and thus I don't test if new optimizations break it. If you want VulkanMod compatibility report it to the devs so they can fix it in their mod

**Comment by xbxct** [comment]
Адаптировать мод под другой движок рендера является очень сложной задачей.

**Comment by fireboy637** [comment]
> I am myself not interested in maintaining VulkanMod compatibility and thus I don't test if new optimizations break it. If you want VulkanMod compatibility report it to the devs so they can fix it in their mod

Immediately is compatible again with VulkanMod 0.5.5 in 1.21.5 (by modifying fabric.mod.json to make it load). While this compatibility can change at any time, I don't think this incompatibilitiy should be written into fabric.mod.json. But this possible incompatibility can be pointed out in the mod introduction for players to test for themselves.
