### ISSUE TITLE
Lag spikes with Iris (shaders on) in specific circumstances when using v1.1.16

### ISSUE THREAD

**Issue by S0urceDA** [RaphiMC/ImmediatelyFast#86]
For some reason v1.1.16 doesn't like Iris and creates a bunch of rapid lag spikes right after each other in very specific scenarios. I was also only able to reproduce this with high resolutions like 4K, since 1080p was fine. I suspect this has something to do with the improved fast buffer upload optimization introduced in commit 0599ca6.

To reproduce go to seed 0 and go to coordinates -1050 100 -200 and shift down until ocean floor and then back up, with shaders on (shader I used is reimagined 2.2.1 but I don't think it matters). Also I disabled the debug f3 info but ImmediatelyFast is installed in the video.

https://github.com/RaphiMC/ImmediatelyFast/assets/61162198/c2eada13-0ba8-4510-b97b-fe865f7e3e3f

**Comment by RaphiMC** [comment]
Did you already try and disable the fast buffer upload optimization or remove IF entirely. I wouldn't know how IF could cause that (Especially since its a very specific scenario and only on a 4K screen)

**Comment by S0urceDA** [comment]
Yeah, I disabled the optimization and the spikes were gone.

**Comment by S0urceDA** [comment]
The only mods I used were sodium, iris and immediatelyfast

**Comment by RaphiMC** [comment]
Can you do a spark profiling. (Download the spark mod and run /sparkc profiler start) do whatever to cause the lag and then stop it again and send me the results

**Comment by S0urceDA** [comment]
Ok I did, https://spark.lucko.me/dHqoy36JxF, not sure if it helps any. I only saw flat graphs

**Comment by RaphiMC** [comment]
I can't really see anything too abnormal. I am going to try and reproduce this issue, but it probably won't happen since I don't have a 4K screen to try it on.
I noticed that you are heavily bottlenecked by the windows desktop manager/compositor. Running in real fullscreen should give you a pretty good performance boost and maybe fix the lag.

**Comment by S0urceDA** [comment]
I used nvidia DSR to get 4K, same issue happens if you use [resolutioncontrol+](https://modrinth.com/mod/resolution-control-plus) at 2x render scale. I have 2 monitors, maybe thats the reason I'm bottlenecked?

**Comment by S0urceDA** [comment]
FYI https://spark.lucko.me/MRbBTMJ26Z I redid the spark profile test with v1.1.15.

**Comment by RaphiMC** [comment]
Can you check if the issue is gone with this IF version: https://upload.raphimc.net/file/BtJtDRKELFkdV3uI/8ndnUve21PmgSWcU/ImmediatelyFast-1.1.17-SNAPSHOT%2B1.20.1.jar
Make sure to reenable fast_buffer_upload

**Comment by S0urceDA** [comment]
I tried it and the issue still persists. Maybe the lag spikes were less severe but there were still spikes nonetheless.

**Comment by S0urceDA** [comment]
Unfortunately the issue still persists in v1.1.25.

**Comment by RaphiMC** [comment]
I didn't directly try to fix this, but another Iris issue I introduced with a recent optimization. I will fix this issue at another point when the current released IF version is stable

**Comment by RaphiMC** [comment]
The issue should be fixed: https://upload.raphimc.net/file/2Wl7fjU9BRkHoRsd/fM8QBUNOp4QXjPG0/ImmediatelyFast-1.1.28-SNAPSHOT%2B1.20.1.jar
Can you test it and give me feedback if the lag spikes are now gone

**Comment by S0urceDA** [comment]
Yep, the issue is indeed fixed with that jar. Hoping for a release soon, thanks!
