### ISSUE TITLE
Incompatibility with Armored Elytra

### ISSUE THREAD

**Issue by mrmelon54** [RaphiMC/ImmediatelyFast#88]
Incompatible with my mod [Armored Elytra](https://github.com/MrMelon54/armored_elytra)

A user complained about my mod not working. It looks like rendering of armor trims in a separate pass probably breaks it.

![image](https://github.com/RaphiMC/ImmediatelyFast/assets/48031324/af716c6b-81fc-4ccd-9cf5-e46f07459cf1)

Notice the trim floating in the top right of the screenshot.

**Comment by RaphiMC** [comment]
Similar to #87

**Comment by mrmelon54** [comment]
Looks like this code does the second pass for trims. Not sure exactly how that causes the effect shown in the previous image, but when removing this mod it fixes the issue. According to multiple users in my Discord server.
https://github.com/RaphiMC/ImmediatelyFast/blob/1.20/src/main/java/net/raphimc/immediatelyfast/injection/mixins/core/MixinArmorFeatureRenderer.java
