### ISSUE TITLE
Allow servers to override IF's config to prevent compatibility issues with core shaders in resource packs

### ISSUE THREAD

**Issue by Lumanyx** [RaphiMC/ImmediatelyFast#89]
Many resource-pack-enabled servers use core shaders to create custom UI elements as well as other things.
I'm aware of the fact that IF disables the HUD batching setting when modified core shaders are detected. However, there are also cases where you would also want to have font atlas resizing (or other settings) disabled depending on the server you're playing on (e.g. you have some fragment shader in the resource pack that relies on the original font texture size -> for example checking the RGB data of a certain pixel on the texture)

We mainly run into issues with IF on one of the servers I'm working on. The server in question is Xenyria.net: Things like our custom mini-map & loading screen on our Rush & PaintSquad game mode are completely broken when ImmediatelyFast is installed (with all features enabled by default).

## Problems

I have attached two videos both of how said games are intended to look like and how it looks like with ImmediatelyFast installed.

Here is how our Rush mode is intended to look like (w/o IF): https://www.youtube.com/watch?v=stBTEfKgNyQ
And here is how our Rush mode looks like with IF being installed: https://www.youtube.com/watch?v=2QEsrq_RvZ0 (note the broken mini-map, map intro text, countdown text and loading screen)

Here's another example based on the loading screen of our PaintSquad game:

### With ImmediatelyFast installed
![PS-Broken](https://github.com/RaphiMC/ImmediatelyFast/assets/38817397/a624ab31-36d7-4cdd-81e4-5613cf617220)

### Without ImmediatelyFast (Vanilla)
![PS-WithoutImmediatelyFast](https://github.com/RaphiMC/ImmediatelyFast/assets/38817397/91973101-f9b9-4e32-894a-28d01c1f7a9d)

Disabling all features of IF via the config seems to fix all of the issues we've experienced. 

We also got several bug reports from our community which all lead to ImmediatelyFast with the only solution being to completely remove the mod in order to be able experience our games in the intended way. The issues that were reported are identical to what is shown on in the video and the screenshot. Therefore it would be great if there was some way for the server to somehow control IF's runtime configuration since just telling users to uninstall the mod seems like a bad solution for all parties involved.

## Potential solutions
Here are two possible implementations for handling this:
- Allow overriding IF's config via plugin messages, that way the server can disable certain features to prevent issues with core shaders
- Try to load a file from the current resource pack if it exists (maybe something like a if-override.properties file): The server resource pack can then include said file to override IF's config

I can also offer creating a fork, implementing one of these solutions and then creating a pull request.

**Comment by RaphiMC** [comment]
I like the idea of servers being able to override the config inside the resource pack as they see necessary. Thats really the only way to fix custom resource pack issues. Can you check if only disabling font_atlas_resizing fixes your issues instead of disabling everything. I can't really make everything toggleable at runtime without rewriting the whole mod

**Comment by Lumanyx** [comment]
Hi, I just did some testing and it turns out just disabling font_atlas_resizing and hud_batching also fixes all of the issues I've mentioned. So realistically we only need a way of disabling font_atlas_resizing since hud_batching will be disabled once custom core shaders are detected.

**Comment by RaphiMC** [comment]
Can you test this build with default config: https://upload.raphimc.net/file/5GSTKL4PZor69Qss/tHc5HZwydmtx11EG/ImmediatelyFast-1.1.17-SNAPSHOT%2B1.20.1.jar
I am now disabling font atlas resizing as well when modified core shaders are detected

**Comment by Lumanyx** [comment]
Hi, I've tried out the build you sent on a clean install of Fabric 1.20.1.

Unfortunately the game crashes a few seconds after joining any server: (In this case IF is the only mod in my mods folder)
[latest.log](https://github.com/RaphiMC/ImmediatelyFast/files/12158769/latest.log)

I've also tried to install Sodium on the same installation and it resulted in glitched rendering:
![IF Sodium](https://github.com/RaphiMC/ImmediatelyFast/assets/38817397/60e8e1da-84f1-41d3-bfa0-08f8f0ff0865)

**Comment by RaphiMC** [comment]
Can you try this build: https://build.lenni0451.net/job/ImmediatelyFast/185/artifact/build/libs/ImmediatelyFast-1.1.17-SNAPSHOT+1.20.1.jar
Everything should still be as broken as with IF 1.1.16 (And work when font_atlas_resizing is set to false), but it shouldn't crash like just happened

**Comment by Lumanyx** [comment]
Tried this on a vanilla install with no other mods -> Resulted in a crash:
[latest.log](https://github.com/RaphiMC/ImmediatelyFast/files/12158909/latest.log)

With Sodium installed, no crashes are present but rendering is still messed up (although it got slightly better with this version)

**Comment by RaphiMC** [comment]
What GPU are you using?

**Comment by Lumanyx** [comment]
> What GPU are you using?

NVIDIA GeForce RTX 4090

**Comment by RaphiMC** [comment]
Can you check if it doesn't crash anymore if you disable fast_buffer_upload

**Comment by Lumanyx** [comment]
I've tried to disable fast_buffer_upload but it still crashes (w/o other mods):
[latest.log](https://github.com/RaphiMC/ImmediatelyFast/files/12158956/latest.log)

**Comment by RaphiMC** [comment]
I am going to join the server and check if it also crashes for me

**Comment by RaphiMC** [comment]
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/50594595/142a038a-1a2e-4296-bc2b-758db0de074c)
Doesn't let me join. Does it also crash on other servers?

**Comment by RaphiMC** [comment]
Nvm I could now join if I join on the main port and it did crash

**Comment by RaphiMC** [comment]
The crashing issue got me confused for a bit, but both issues should now be fixed: https://upload.raphimc.net/file/uwU6sfdWSaAa8YZi/E4HVmNwbytK6EiqS/ImmediatelyFast-1.1.17-SNAPSHOT%2B1.20.1.jar
Make sure to reset your config back to default for testing (You can delete it to do that)

**Comment by Lumanyx** [comment]
Hi,
we did some thorough testing on our server and it seems like everything is working fine now with the build you've provided.
Thanks for taking care of this. ^^
