### ISSUE TITLE
Does ImmediatelyFast make having Enhanced Block Entities pointless?

### ISSUE THREAD

**Issue by VeggeieDude** [RaphiMC/ImmediatelyFast#9]
Heya! Does having both this mod and Enhanced Block Entities redundant? Since they both optimize block entities

**Comment by RaphiMC** [comment]
No, Enhanced Block Entities actually makes Block Entities rendered not in immediate mode and thus increase performance in a different way (Making it better then the optimization from ImmediatelyFast). It won't hurt tho to have both mods installed, as ImmediatelyFast optimizes other areas as well which aren't touched by Enhanced Block Entities
