### ISSUE TITLE
160 -> 150 after updating to 1.1.17

### ISSUE THREAD

**Issue by Taleuxss** [RaphiMC/ImmediatelyFast#92]
unhelpful issue probably, ive got bunch of mods installed also but i noticed in my modpack the recent update removed like 10 fps during testing

**Comment by Taleuxss** [comment]
as an addon question, is it bad practice to run this mod with exordium and/or enhanced block entities

**Comment by RaphiMC** [comment]
10 FPS difference is within margin of error / deviation between game launches. Also using both of the mods you mentioned is supported and recommended. It will improve performance even further
