### ISSUE TITLE
GUI is messed up with 1.1.18

### ISSUE THREAD

**Issue by 119z** [RaphiMC/ImmediatelyFast#93]
I'm using Fabric, MC 1.19.4, and when I open the game, the tabs (?) are all messed up. I tested on a new instance with only IF 1.1.18. If I downgrade, everything's fine.

![image](https://github.com/RaphiMC/ImmediatelyFast/assets/55221203/2418584e-2ca0-4d5e-b4cd-356e6c8b46cc)
Using 1.1.18

![image](https://github.com/RaphiMC/ImmediatelyFast/assets/55221203/a9d056c0-ed89-4021-b7bb-fbb9480e221b)
Using 1.1.17

I can provide logs if needed.

**Comment by RaphiMC** [comment]
Can you check if it works using this version: https://upload.raphimc.net/file/GdyM6bN0GJFJke9I/QoXvPdVqzZaTu62i/ImmediatelyFast-1.1.19-SNAPSHOT%2B1.19.4.jar
Also what GPU are you using?

**Comment by 119z** [comment]
That worked! My GPU is Intel Iris Plus Graphics. I'm aware it's not the best, but it's what I got.

![image](https://github.com/RaphiMC/ImmediatelyFast/assets/55221203/5a8614e0-072e-4844-b43a-569c442c5f66)

**Comment by RaphiMC** [comment]
Thanks for reporting that so fast! I will make a new release now
