### ISSUE TITLE
Issues with GUI

### ISSUE THREAD

**Issue by 119z** [RaphiMC/ImmediatelyFast#94]
Just went in game after installing the new update and it seems there's still a few issues.

The box behind the text flickers in and out.
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/55221203/3b0cbbab-c71a-4855-8b66-bd103ac3789b)

Some letters appear missing too.
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/55221203/28282ea8-8f3f-4aae-94d0-b0ff1182f4dd)

Also causes some blocks in the JEI menu to flicker in and out.
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/55221203/841f58c9-a2f1-47a9-a453-10f48c8cf993)

I play with Better F3 and the text at the top also flickers in an out when I call it.
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/55221203/863eee75-7f68-46fa-9464-b7bd7ddee959)

-

I tested on a new instance with only IF 1.1.19 and I noticed that the text here seems to be getting hidden by the buttons.
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/55221203/a5205f25-4d03-405a-91a3-35f3d461ee77)

Depending on where I look, my character's hand also disappears
![2023-07-27_18 07 29](https://github.com/RaphiMC/ImmediatelyFast/assets/55221203/bcdf383c-a6e1-41c9-b93a-b00192e5960a)

Objects in the inventory disappear, as does my hand
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/55221203/ad38c869-0c36-4971-a749-f3550f5b32c7)

The dirt shows up if I look up at the sky, and disappears once I look back down.
![2023-07-27_18 15 24](https://github.com/RaphiMC/ImmediatelyFast/assets/55221203/de059fe2-5d67-4cc4-9edd-f79e7163bf27)
![2023-07-27_18 15 28](https://github.com/RaphiMC/ImmediatelyFast/assets/55221203/75a3fec0-df0e-4bcf-a625-69850152a9bb)

The flickering also happens with the vanilla F3 menu
![2023-07-27_18 07 47](https://github.com/RaphiMC/ImmediatelyFast/assets/55221203/05eeef15-e866-4ac9-88ad-28af5de6c405)

Here's [my log](https://mclo.gs/JWRTzSe) with only IF 1.1.19 installed

**Comment by RaphiMC** [comment]
Whats your GPU?

**Comment by 119z** [comment]
Intel Iris Plus Graphics

**Comment by RaphiMC** [comment]
Disable fast_buffer_upload in the config file for now

**Comment by RaphiMC** [comment]
Can you test this version: https://upload.raphimc.net/file/fLEg017ASVk2J2br/9fqnEZC8pFOmDSFH/ImmediatelyFast-1.1.20-SNAPSHOT%2B1.19.4.jar
Make sure to reenable the fast_buffer_upload optimization

**Comment by RaphiMC** [comment]
If this doesn't fix it try IF 1.1.17 (https://modrinth.com/mod/immediatelyfast/version/1.1.17+1.19.4)

**Comment by 119z** [comment]
All seems fine with this version at a first glance. Thank you so much!

**Comment by RaphiMC** [comment]
Which one, the first or the second? Also can you try this one, because thats the one I am about to release now: https://upload.raphimc.net/file/euRAxVnMUht4YBSs/4xQ528AzPovZv2h0/ImmediatelyFast-1.1.20-SNAPSHOT%2B1.19.4.jar
Please verify if performance is as good as it is with whatever IF version you are currently using

**Comment by RaphiMC** [comment]
Released the version. I assume performance is good and the issue is still fixed. If not please comment on this issue
