### ISSUE TITLE
Lag with some scoreboards

### ISSUE THREAD

**Issue by JustAlittleWolf** [RaphiMC/ImmediatelyFast#95]
Immediatelyfast tanks fps when the leaderboard displays some symbols. For me it dropped the fps from 400 to roughly 100. When using spark to profile the game it shows a 50% CPU usage on the `fixNegativeAdvancedGlyphs` method in `MixinTextRenderer_Drawer.java` (See this link: https://spark.lucko.me/w9ITDSmof3).

How to reproduce:
- Join cytooxien.de
- Enter the "Only Up" minigame
- Watch the FPS drop

Version of ImmediatelyFast: 1.1.24

Mods used:
- animatica 0.6+1.20
- betterpingdisplay 1.1.1
- blur 3.1.0
- borderlessmining 1.1.8+1.20.1
- c2me 0.2.0+alpha.10.96
- capes 1.5.2+1.20
- chat_heads 0.10.19
- chatpatches 201.5.3
- citresewn 1.1.3+1.20
- cloth-config 11.1.106
- continuity 3.0.0-beta.3+1.20.1
- craterlib 1.0.2
- dark-loading-screen 1.6.14
- dynamicfps 2.4.0
- enhancedblockentities 0.9+1.20
- entityculling 1.6.2-mc1.20
- exit_confirm 2.5.0-mc.1.20.1
- fabric-api 0.86.1+1.20.1
- fabric-language-kotlin 1.10.8+kotlin.1.9.0
- fabrication 3.3.1+1.20
- fabricforcelowercase 2.1.0
- fabricloader 0.14.21
- fabricskyboxes 0.7.2+mc1.20.1
- farsight 1.20.1-3.9
- ferritecore 6.0.0
- fixelytrabug 1.1.0
- forcecloseworldloadingscreen 2.1.1
- fsb-interop 1.3.3+mc1.20-build.46
- ias 8.0.2
- indium 1.0.21+mc1.20.1
- iris 1.6.4
- java 17
- krypton 0.2.3
- lazy-language-loader 0.3.3
- lithium 0.11.2
- memoryleakfix 1.1.1
- minecraft 1.20.1
- modify-camera-collision 1.0.0
- modmenu 7.2.1
- moreculling 1.20-0.18.1
- my-beloved-icon 1.0-SNAPSHOT
- nbt_ac 1.1.2
- nbttooltips 0.1.4-1.20.x
- no-telemetry 1.7.0
- no_fog 1.3.4+1.16.5-1.20.1
- nochatreports 1.20.1-v2.2.2
- norefreshscroll 1.0.5
- presencefootsteps 1.9.0
- rebind_narrator 2.0.2
- serverpingerfixer 1.0.1
- simple-rpc 3.2.2
- skinlayers 1.5.4-mc1.20.1
- smoothscrollingeverywhere 3.0.6
- sneaktweak 1.9.1
- sodium 0.4.10+build.27
- spark 1.10.42
- starlight 1.1.2+fabric.dbc156f
- threadtweak 1.20.1-0.1.0
- viafabric 0.4.10+409-main
- visiblebarriers 2.0.6
- waveycapes 1.3.2
- worldedit 7.2.15+6463-5ca4dff
- yet_another_config_lib_v3 3.1.0+1.20
- zoomify 2.11.0

**Comment by RaphiMC** [comment]
How many FPS do you get without IF? Make a spark report of the exact same scene without IF

**Comment by JustAlittleWolf** [comment]
2 Chunks render distance

FPS with ImmediatelyFast: ~200
https://spark.lucko.me/H1fQ6ceRc6

FPS without ImmediatelyFast: ~400
https://spark.lucko.me/bWqok0SZnf

**Comment by JustAlittleWolf** [comment]
Did not tank the fps that much this time (even though I was on the same spot with the same settings when first encountering the issue), but for being a performance mod it should definitely not *decrease* performance.

**Comment by RaphiMC** [comment]
Can you send the game log please

**Comment by JustAlittleWolf** [comment]
[withImmediatelyFast.log](https://github.com/RaphiMC/ImmediatelyFast/files/12233771/immediatelyFast.log)
[withoutImmediatelyFast.log](https://github.com/RaphiMC/ImmediatelyFast/files/12233772/withoutImmediatelyFast.log)
I just noticed I swapped the spark links as well, fixed it now

**Comment by RaphiMC** [comment]
Can you check if this issue is fixed by installing this version of ImmediatelyFast: https://upload.raphimc.net/file/4KsbKEXF66BJ8kOt/4gNd1YyPEJLPOlzD/ImmediatelyFast-Fabric-1.2.19-SNAPSHOT.zip

**Comment by JustAlittleWolf** [comment]
Unfortunately not, I don't have access to the server where the issue occurred anymore.
