### ISSUE TITLE
Crash with Mini-hud

### ISSUE THREAD

**Issue by bendy1234** [RaphiMC/ImmediatelyFast#97]
crash report: [crash-2023-08-04_18.21.43-client.txt](https://github.com/RaphiMC/ImmediatelyFast/files/12265387/crash-2023-08-04_18.21.43-client.txt)

crashed when I turned on "OverlayBiomeBorders" from mini-hud

Mods
- fabric-api-0.86.1+1.20.1
- ImmediatelyFast-1.1.25+1.20.1
- malilib-fabric-1.20.1-0.16.1
- minihud-fabric-1.20.1-0.27.0

**Comment by RaphiMC** [comment]
Can you check if its fixed in this version: https://upload.raphimc.net/file/xga23BacpLg51HG6/jNn2GVOUtdlMhtF2/ImmediatelyFast-1.1.26-SNAPSHOT%2B1.20.1.jar

**Comment by bendy1234** [comment]
> Can you check if its fixed in this version: https://upload.raphimc.net/file/xga23BacpLg51HG6/jNn2GVOUtdlMhtF2/ImmediatelyFast-1.1.26-SNAPSHOT%2B1.20.1.jar

it's fixed in that version
