### ISSUE TITLE
Large custom font characters break on IF 1.1.17+

### ISSUE THREAD

**Issue by MultiverShaun** [RaphiMC/ImmediatelyFast#98]
Large custom characters in the default.json file of my resource pack break on any version of ImmediatelyFast above 1.1.16. This also happens when IF is the only mod. It also happens in titles and in chat.
## With IF 1.1.17+:
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/68468439/47323e4b-779c-4e67-89ac-36b9d740cbab)
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/68468439/ce53e58f-c4bb-43d9-ab0c-4648cc538e84)
## Without IF/IF 1.1.16 and below:
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/68468439/cd64807f-5854-4360-883b-83e7afe228f5)
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/68468439/91a6c641-37e6-4a72-b963-0dd20fe4d66c)

Notice how the custom diamond (♢) symbols remain functional.

## Characters in default.json
```
{
    "file": "permafrost:font/permafrost_small_caps.png",
    "chars": ["\ue242"],
    "height": 11,
    "ascent": 10,
    "type": "bitmap"
},
{
    "file": "permafrost:font/permafrost.png",
    "chars": ["\ue237"],
    "height": 14,
    "ascent": 5,
    "type": "bitmap"
}
```

## Steps to reproduce

1. Create large custom font characters with a resource pack
2. Run Minecraft with ImmediatelyFast 1.1.17 or above
3. Notice how said custom characters will not work

## Misc. Info
Game version: 1.20.1
Loader: Quilt
IF version: IF 1.1.17-1.1.25

**Comment by RaphiMC** [comment]
Does the bug also happen in 1.1.25? Did you test that? Also can you provide a whole resource pack for me to download / the server address so I can test it myself

**Comment by MultiverShaun** [comment]
> Does the bug also happen in 1.1.25? Did you test that? Also can you provide a whole resource pack for me to download / the server address so I can test it myself

Yes, it happens on ImmediatelyFast 1.1.25 too.
Here's the resource pack minus all the non-font related stuff:
[IF_Font_Issue_Resource_Pack.zip](https://github.com/RaphiMC/ImmediatelyFast/files/12266652/IF_Font_Issue_Resource_Pack.zip)

**Comment by RaphiMC** [comment]
The pack doesn't load. It unloads immediately again due to multiple errors

**Comment by MultiverShaun** [comment]
> The pack doesn't load. It unloads immediately again due to multiple errors

Really sorry, this one should work:
[IF_Font_Issue_Resource_Pack.zip](https://github.com/RaphiMC/ImmediatelyFast/files/12266768/IF_Font_Issue_Resource_Pack.zip)

**Comment by RaphiMC** [comment]
![image](https://github.com/RaphiMC/ImmediatelyFast/assets/50594595/678ef0c2-3928-455e-8e47-3fbc7755e91d)
Can't reproduce the issue. The image renders fine if I write that character in the chat

**Comment by MultiverShaun** [comment]
> ![image](https://user-images.githubusercontent.com/50594595/258577040-678ef0c2-3928-455e-8e47-3fbc7755e91d.png) Can't reproduce the issue. The image renders fine if I write that character in the chat

Just tested that pack myself and the issue is in fact gone. I'm fairly certain the issue has something to do with my actual resource pack's shaders then, probably unrelated to IF. Sorry to bother you! I'll close this issue now.

**Comment by TehBrian** [comment]
Not sure if this is related, but ImmediatelyFast 1.2.6 seems to remove vanilla Minecraft's bitmap texture limitation of 256x256. Is that intended behavior?

**Comment by RaphiMC** [comment]
Yes this is intended as the default is way too small for fitting many high resolution characters on a single glyph page

**Comment by TehBrian** [comment]
Gotcha. I didn't see that documented on any of the mod's pages, so I wasn't sure.
