### ISSUE TITLE
Game is crashing when using light level overlay from minihud [1.1.25 | 1.20.1]

### ISSUE THREAD

**Issue by IFedor-F** [RaphiMC/ImmediatelyFast#99]
Since version 1.1.25, the game crashes while using Light overlay in water from [Minihud](https://github.com/maruohon/minihud)
[Minecraft Log](https://mclo.gs/Q7f8VKl)
[Video](https://github.com/RaphiMC/ImmediatelyFast/assets/116349244/ff160a16-6712-4bb5-a3f4-a80b5e57ce11)

**Comment by RaphiMC** [comment]
Will be fixed in the next release which I will upload today
